// Auto-generated by codegen.py from binding_defs.json — DO NOT EDIT
#include "engine/reflect/component_reflection.h"

#include <typeindex>

#include "engine/reflect/reflect.h"

#include "engine/ecs/transform.h"
#include "engine/ecs/components_3d.h"
#include "engine/ecs/components_3d_tree.h"
#include "engine/ecs/components_3d_terrain_tile.h"
#include "engine/ecs/components_3d_navmesh.h"
#include "engine/ecs/components_3d_render.h"
#include "engine/ecs/components_3d_foliage.h"
#include "engine/ecs/components_3d_physics.h"
#include "engine/ecs/components_3d_sky.h"
#include "engine/ecs/components_3d_impostor.h"
#include "engine/scene/world_partition.h"
#include "engine/render/hlod/hlod_system.h"
#include "engine/render/virtual_texture/virtual_texture.h"
#include "engine/render/gi/lightmap_baker.h"
#include "engine/ecs/components_3d_character.h"
#include "engine/ecs/components_3d_animation.h"
#include "engine/render/particles/gpu_particle_system.h"
#include "engine/ecs/ui.h"
#include "engine/ecs/sprite.h"
#include "engine/ecs/light_2d.h"
#include "engine/ecs/audio.h"
#include "engine/ecs/script.h"

namespace dse::reflect {

namespace {

void RegisterTransform() {
    using ::TransformComponent;
    auto t = DSE_REFLECT_TYPE(TransformComponent);
    t.field("position", &TransformComponent::position);
    t.field("rotation", &TransformComponent::rotation);
    t.field("scale", &TransformComponent::scale);
}

void RegisterCamera3D() {
    using dse::Camera3DComponent;
    auto t = DSE_REFLECT_TYPE(Camera3DComponent);
    t.field("fov", &Camera3DComponent::fov).range(1.0, 179.0);
    t.field("near_clip", &Camera3DComponent::near_clip).range(0.001, 100.0);
    t.field("far_clip", &Camera3DComponent::far_clip).range(1.0, 100000.0);
    t.field("enabled", &Camera3DComponent::enabled);
    t.field("priority", &Camera3DComponent::priority);
    t.field("aspect_ratio", &Camera3DComponent::aspect_ratio).range(0.1, 10.0);
}

void RegisterMeshRenderer() {
    using dse::MeshRendererComponent;
    DSE_REFLECT_ENUM(dse::MeshRendererComponent::MaterialDataSource)
        .value("ComponentFallback", dse::MeshRendererComponent::MaterialDataSource::ComponentFallback)
        .value("MaterialInstance", dse::MeshRendererComponent::MaterialDataSource::MaterialInstance)
        ;

    auto t = DSE_REFLECT_TYPE(MeshRendererComponent);
    t.field("color", &MeshRendererComponent::color).color();
    t.field("visible", &MeshRendererComponent::visible);
    t.field("metallic", &MeshRendererComponent::metallic).range(0.0, 1.0);
    t.field("roughness", &MeshRendererComponent::roughness).range(0.0, 1.0);
    t.field("emissive", &MeshRendererComponent::emissive).color();
    t.field("receive_shadow", &MeshRendererComponent::receive_shadow);
    t.field("mesh_path", &MeshRendererComponent::mesh_path);
    t.field("shader_variant", &MeshRendererComponent::shader_variant);
    t.field("material_data_source", &MeshRendererComponent::material_data_source);
}

void RegisterDirectionalLight3D() {
    using dse::DirectionalLight3DComponent;
    auto t = DSE_REFLECT_TYPE(DirectionalLight3DComponent);
    t.field("direction", &DirectionalLight3DComponent::direction);
    t.field("color", &DirectionalLight3DComponent::color).color();
    t.field("intensity", &DirectionalLight3DComponent::intensity).range(0.0, 100.0);
    t.field("ambient_intensity", &DirectionalLight3DComponent::ambient_intensity).range(0.0, 4.0);
    t.field("cast_shadow", &DirectionalLight3DComponent::cast_shadow);
    t.field("shadow_strength", &DirectionalLight3DComponent::shadow_strength).range(0.0, 1.0);
    t.field("enabled", &DirectionalLight3DComponent::enabled);
    t.field("cascade_splits", &DirectionalLight3DComponent::cascade_splits);
    t.field("cascade_split_lambda", &DirectionalLight3DComponent::cascade_split_lambda).range(0.0, 1.0);
}

void RegisterPointLight() {
    using dse::PointLightComponent;
    auto t = DSE_REFLECT_TYPE(PointLightComponent);
    t.field("color", &PointLightComponent::color).color();
    t.field("intensity", &PointLightComponent::intensity).range(0.0, 100.0);
    t.field("radius", &PointLightComponent::radius).range(0.0, 1000.0);
    t.field("enabled", &PointLightComponent::enabled);
    t.field("cast_shadow", &PointLightComponent::cast_shadow);
    t.field("falloff", &PointLightComponent::falloff).range(0.0, 8.0);
}

void RegisterSpotLight() {
    using dse::SpotLightComponent;
    auto t = DSE_REFLECT_TYPE(SpotLightComponent);
    t.field("color", &SpotLightComponent::color).color();
    t.field("intensity", &SpotLightComponent::intensity).range(0.0, 100.0);
    t.field("radius", &SpotLightComponent::radius).range(0.0, 1000.0);
    t.field("inner_cone_angle", &SpotLightComponent::inner_cone_angle).range(0.0, 90.0);
    t.field("outer_cone_angle", &SpotLightComponent::outer_cone_angle).range(0.0, 90.0);
    t.field("direction", &SpotLightComponent::direction);
    t.field("enabled", &SpotLightComponent::enabled);
    t.field("cast_shadow", &SpotLightComponent::cast_shadow);
    t.field("falloff", &SpotLightComponent::falloff).range(0.0, 8.0);
}

void RegisterSkyLight() {
    using dse::SkyLightComponent;
    auto t = DSE_REFLECT_TYPE(SkyLightComponent);
    t.field("up_color", &SkyLightComponent::up_color).color();
    t.field("down_color", &SkyLightComponent::down_color).color();
    t.field("intensity", &SkyLightComponent::intensity).range(0.0, 16.0);
    t.field("enabled", &SkyLightComponent::enabled);
}

void RegisterTree() {
    using dse::TreeComponent;
    auto t = DSE_REFLECT_TYPE(TreeComponent);
    t.field("enabled", &TreeComponent::enabled);
    t.field("density", &TreeComponent::density).range(0.0, 1.0).tooltip("Trees per square meter");
    t.field("spawn_radius", &TreeComponent::spawn_radius).range(1.0, 1000.0);
    t.field("chunk_size", &TreeComponent::chunk_size).range(1.0, 256.0);
    t.field("min_scale", &TreeComponent::min_scale);
    t.field("max_scale", &TreeComponent::max_scale);
    t.field("lod1_distance", &TreeComponent::lod1_distance);
    t.field("cull_distance", &TreeComponent::cull_distance);
    t.field("wind_strength", &TreeComponent::wind_strength);
    t.field("wind_speed", &TreeComponent::wind_speed);
    t.field("cast_shadow", &TreeComponent::cast_shadow);
    t.field("shadow_distance", &TreeComponent::shadow_distance);
    t.field("seed", &TreeComponent::seed);
    t.field("height_variation", &TreeComponent::height_variation);
    t.field("random_rotation", &TreeComponent::random_rotation);
    t.field("billboard_distance", &TreeComponent::billboard_distance);
    t.field("mesh_path", &TreeComponent::mesh_path);
    t.field("lod1_mesh_path", &TreeComponent::lod1_mesh_path);
    t.field("billboard_texture_path", &TreeComponent::billboard_texture_path);
}

void RegisterTerrainTileManager() {
    using dse::TerrainTileManagerComponent;
    auto t = DSE_REFLECT_TYPE(TerrainTileManagerComponent);
    t.field("enabled", &TerrainTileManagerComponent::enabled);
    t.field("tile_world_size", &TerrainTileManagerComponent::tile_world_size).range(1.0, 1024.0);
    t.field("tile_resolution", &TerrainTileManagerComponent::tile_resolution).range(8.0, 512.0);
    t.field("max_height", &TerrainTileManagerComponent::max_height).range(0.0, 10000.0);
    t.field("load_radius", &TerrainTileManagerComponent::load_radius).range(1.0, 10000.0);
    t.field("unload_radius", &TerrainTileManagerComponent::unload_radius).range(1.0, 10000.0);
    t.field("use_procedural", &TerrainTileManagerComponent::use_procedural);
    t.field("procedural_base_height", &TerrainTileManagerComponent::procedural_base_height);
    t.field("max_lod_levels", &TerrainTileManagerComponent::max_lod_levels).range(1.0, 8.0);
    t.field("lod_distance_factor", &TerrainTileManagerComponent::lod_distance_factor).range(1.0, 1000.0);
}

void RegisterDynamicObstacle() {
    using dse::DynamicObstacleComponent;
    auto t = DSE_REFLECT_TYPE(DynamicObstacleComponent);
    t.field("enabled", &DynamicObstacleComponent::enabled);
    t.field("shape", &DynamicObstacleComponent::shape);
    t.field("box_extents", &DynamicObstacleComponent::box_extents);
    t.field("cylinder_radius", &DynamicObstacleComponent::cylinder_radius).range(0.0, 100.0);
    t.field("cylinder_height", &DynamicObstacleComponent::cylinder_height).range(0.0, 100.0);
}

void RegisterNavMeshAutoRebake() {
    using dse::NavMeshAutoRebakeComponent;
    auto t = DSE_REFLECT_TYPE(NavMeshAutoRebakeComponent);
    t.field("enabled", &NavMeshAutoRebakeComponent::enabled);
    t.field("tile_size", &NavMeshAutoRebakeComponent::tile_size).range(1.0, 256.0);
    t.field("rebake_cooldown", &NavMeshAutoRebakeComponent::rebake_cooldown).range(0.0, 60.0);
    t.field("collect_terrain", &NavMeshAutoRebakeComponent::collect_terrain);
    t.field("collect_mesh_renderers", &NavMeshAutoRebakeComponent::collect_mesh_renderers);
    t.field("agent_height", &NavMeshAutoRebakeComponent::agent_height).range(0.1, 10.0);
    t.field("agent_radius", &NavMeshAutoRebakeComponent::agent_radius).range(0.1, 10.0);
    t.field("agent_max_climb", &NavMeshAutoRebakeComponent::agent_max_climb).range(0.0, 10.0);
    t.field("agent_max_slope", &NavMeshAutoRebakeComponent::agent_max_slope).range(0.0, 90.0);
    t.field("cell_size", &NavMeshAutoRebakeComponent::cell_size).range(0.01, 10.0);
    t.field("cell_height", &NavMeshAutoRebakeComponent::cell_height).range(0.01, 10.0);
}

void RegisterPostProcess() {
    using dse::PostProcessComponent;
    auto t = DSE_REFLECT_TYPE(PostProcessComponent);
    t.field("enabled", &PostProcessComponent::enabled);
    t.field("bloom_enabled", &PostProcessComponent::bloom_enabled);
    t.field("bloom_threshold", &PostProcessComponent::bloom_threshold);
    t.field("bloom_intensity", &PostProcessComponent::bloom_intensity);
    t.field("bloom_knee", &PostProcessComponent::bloom_knee);
    t.field("bloom_mip_weight", &PostProcessComponent::bloom_mip_weight);
    t.field("color_grading_enabled", &PostProcessComponent::color_grading_enabled);
    t.field("exposure", &PostProcessComponent::exposure);
    t.field("gamma", &PostProcessComponent::gamma);
    t.field("ssao_enabled", &PostProcessComponent::ssao_enabled);
    t.field("ssao_radius", &PostProcessComponent::ssao_radius);
    t.field("ssao_bias", &PostProcessComponent::ssao_bias);
    t.field("ssao_sample_count", &PostProcessComponent::ssao_sample_count);
    t.field("ssao_power", &PostProcessComponent::ssao_power);
    t.field("ssao_intensity", &PostProcessComponent::ssao_intensity);
    t.field("auto_exposure_enabled", &PostProcessComponent::auto_exposure_enabled);
    t.field("exposure_min", &PostProcessComponent::exposure_min);
    t.field("exposure_max", &PostProcessComponent::exposure_max);
    t.field("adaptation_speed_up", &PostProcessComponent::adaptation_speed_up);
    t.field("adaptation_speed_down", &PostProcessComponent::adaptation_speed_down);
    t.field("exposure_compensation", &PostProcessComponent::exposure_compensation);
    t.field("color_lut_intensity", &PostProcessComponent::color_lut_intensity);
    t.field("vignette_enabled", &PostProcessComponent::vignette_enabled);
    t.field("vignette_intensity", &PostProcessComponent::vignette_intensity);
    t.field("vignette_radius", &PostProcessComponent::vignette_radius);
    t.field("vignette_softness", &PostProcessComponent::vignette_softness);
    t.field("film_grain_enabled", &PostProcessComponent::film_grain_enabled);
    t.field("film_grain_intensity", &PostProcessComponent::film_grain_intensity);
    t.field("film_grain_time_scale", &PostProcessComponent::film_grain_time_scale);
    t.field("fxaa_enabled", &PostProcessComponent::fxaa_enabled);
    t.field("taa_enabled", &PostProcessComponent::taa_enabled);
    t.field("taa_blend_factor", &PostProcessComponent::taa_blend_factor);
    t.field("contact_shadow_enabled", &PostProcessComponent::contact_shadow_enabled);
    t.field("contact_shadow_strength", &PostProcessComponent::contact_shadow_strength);
    t.field("contact_shadow_steps", &PostProcessComponent::contact_shadow_steps);
    t.field("contact_shadow_step_size", &PostProcessComponent::contact_shadow_step_size);
    t.field("dof_enabled", &PostProcessComponent::dof_enabled);
    t.field("dof_focus_distance", &PostProcessComponent::dof_focus_distance);
    t.field("dof_focus_range", &PostProcessComponent::dof_focus_range);
    t.field("dof_bokeh_radius", &PostProcessComponent::dof_bokeh_radius);
    t.field("motion_blur_enabled", &PostProcessComponent::motion_blur_enabled);
    t.field("motion_blur_intensity", &PostProcessComponent::motion_blur_intensity);
    t.field("motion_blur_samples", &PostProcessComponent::motion_blur_samples);
    t.field("ssr_enabled", &PostProcessComponent::ssr_enabled);
    t.field("ssr_max_distance", &PostProcessComponent::ssr_max_distance);
    t.field("ssr_thickness", &PostProcessComponent::ssr_thickness);
    t.field("ssr_step_size", &PostProcessComponent::ssr_step_size);
    t.field("ssr_max_steps", &PostProcessComponent::ssr_max_steps);
    t.field("ssr_fade_distance", &PostProcessComponent::ssr_fade_distance);
    t.field("ssr_max_roughness", &PostProcessComponent::ssr_max_roughness);
    t.field("outline_enabled", &PostProcessComponent::outline_enabled);
    t.field("outline_color", &PostProcessComponent::outline_color);
    t.field("outline_thickness", &PostProcessComponent::outline_thickness);
    t.field("outline_depth_threshold", &PostProcessComponent::outline_depth_threshold);
    t.field("outline_normal_threshold", &PostProcessComponent::outline_normal_threshold);
    t.field("light_shaft_enabled", &PostProcessComponent::light_shaft_enabled);
    t.field("light_shaft_color", &PostProcessComponent::light_shaft_color);
    t.field("light_shaft_density", &PostProcessComponent::light_shaft_density);
    t.field("light_shaft_weight", &PostProcessComponent::light_shaft_weight);
    t.field("light_shaft_decay", &PostProcessComponent::light_shaft_decay);
    t.field("light_shaft_exposure", &PostProcessComponent::light_shaft_exposure);
    t.field("light_shaft_intensity", &PostProcessComponent::light_shaft_intensity);
    t.field("light_shaft_samples", &PostProcessComponent::light_shaft_samples);
    t.field("fog_enabled", &PostProcessComponent::fog_enabled);
    t.field("fog_color", &PostProcessComponent::fog_color);
    t.field("fog_density", &PostProcessComponent::fog_density);
    t.field("fog_height_falloff", &PostProcessComponent::fog_height_falloff);
    t.field("fog_height_offset", &PostProcessComponent::fog_height_offset);
    t.field("fog_start", &PostProcessComponent::fog_start);
    t.field("fog_end", &PostProcessComponent::fog_end);
    t.field("fog_steps", &PostProcessComponent::fog_steps);
    t.field("fog_sun_scatter", &PostProcessComponent::fog_sun_scatter);
}

void RegisterAnimator3D() {
    using dse::Animator3DComponent;
    auto t = DSE_REFLECT_TYPE(Animator3DComponent);
    t.field("enabled", &Animator3DComponent::enabled);
    t.field("danim_path", &Animator3DComponent::danim_path);
    t.field("dskel_path", &Animator3DComponent::dskel_path);
    t.field("speed", &Animator3DComponent::speed);
    t.field("loop", &Animator3DComponent::loop);
    t.field("use_anim_tree", &Animator3DComponent::use_anim_tree);
    t.field("blend_parameter", &Animator3DComponent::blend_parameter);
    t.field("blend_parameter_value", &Animator3DComponent::blend_parameter_value);
}

void RegisterDecal() {
    using dse::DecalComponent;
    auto t = DSE_REFLECT_TYPE(DecalComponent);
    t.field("enabled", &DecalComponent::enabled);
    t.field("color", &DecalComponent::color).color();
    t.field("angle_fade", &DecalComponent::angle_fade).range(0.0, 1.0);
}

void RegisterSkybox() {
    using dse::SkyboxComponent;
    auto t = DSE_REFLECT_TYPE(SkyboxComponent);
    t.field("enabled", &SkyboxComponent::enabled);
    t.field("cubemap_path", &SkyboxComponent::cubemap_path);
}

void RegisterFreeCameraController() {
    using dse::FreeCameraControllerComponent;
    auto t = DSE_REFLECT_TYPE(FreeCameraControllerComponent);
    t.field("enabled", &FreeCameraControllerComponent::enabled);
    t.field("move_speed", &FreeCameraControllerComponent::move_speed).range(0.0, 100.0);
    t.field("mouse_sensitivity", &FreeCameraControllerComponent::mouse_sensitivity).range(0.0, 4.0);
    t.field("pitch", &FreeCameraControllerComponent::pitch);
    t.field("yaw", &FreeCameraControllerComponent::yaw);
}

void RegisterSubScene() {
    using dse::SubSceneComponent;
    auto t = DSE_REFLECT_TYPE(SubSceneComponent);
    t.field("enabled", &SubSceneComponent::enabled);
    t.field("scene_path", &SubSceneComponent::scene_path);
}

void RegisterBoundingBox() {
    using dse::BoundingBoxComponent;
    auto t = DSE_REFLECT_TYPE(BoundingBoxComponent);
    t.field("min_extents", &BoundingBoxComponent::min_extents);
    t.field("max_extents", &BoundingBoxComponent::max_extents);
}

void RegisterWater() {
    using dse::WaterComponent;
    auto t = DSE_REFLECT_TYPE(WaterComponent);
    t.field("enabled", &WaterComponent::enabled);
    t.field("water_level", &WaterComponent::water_level);
    t.field("deep_color", &WaterComponent::deep_color).color();
    t.field("shallow_color", &WaterComponent::shallow_color).color();
    t.field("max_depth", &WaterComponent::max_depth).range(0.0, 1000.0);
    t.field("transparency", &WaterComponent::transparency).range(0.0, 1.0);
    t.field("wave_amplitude", &WaterComponent::wave_amplitude).range(0.0, 10.0);
    t.field("wave_frequency", &WaterComponent::wave_frequency).range(0.0, 16.0);
    t.field("wave_speed", &WaterComponent::wave_speed).range(0.0, 16.0);
    t.field("wave_direction", &WaterComponent::wave_direction);
    t.field("refraction_strength", &WaterComponent::refraction_strength).range(0.0, 1.0);
    t.field("reflection_strength", &WaterComponent::reflection_strength).range(0.0, 1.0);
    t.field("specular_power", &WaterComponent::specular_power).range(1.0, 512.0);
    t.field("caustic_intensity", &WaterComponent::caustic_intensity).range(0.0, 4.0);
    t.field("caustic_scale", &WaterComponent::caustic_scale).range(0.0, 64.0);
    t.field("foam_intensity", &WaterComponent::foam_intensity).range(0.0, 4.0);
    t.field("foam_depth_threshold", &WaterComponent::foam_depth_threshold).range(0.0, 100.0);
    t.field("underwater_fog_density", &WaterComponent::underwater_fog_density).range(0.0, 1.0);
    t.field("underwater_fog_color", &WaterComponent::underwater_fog_color).color();
}

void RegisterLightProbe() {
    using dse::LightProbeComponent;
    auto t = DSE_REFLECT_TYPE(LightProbeComponent);
    t.field("enabled", &LightProbeComponent::enabled);
    t.field("influence_radius", &LightProbeComponent::influence_radius).range(0.0, 1000.0);
    t.field("show_debug", &LightProbeComponent::show_debug);
    t.field("sh_coefficients", &LightProbeComponent::sh_coefficients);
}

void RegisterReflectionProbe() {
    using dse::ReflectionProbeComponent;
    auto t = DSE_REFLECT_TYPE(ReflectionProbeComponent);
    t.field("enabled", &ReflectionProbeComponent::enabled);
    t.field("influence_radius", &ReflectionProbeComponent::influence_radius).range(0.0, 1000.0);
    t.field("box_size_x", &ReflectionProbeComponent::box_size_x).range(0.0, 1000.0);
    t.field("box_size_y", &ReflectionProbeComponent::box_size_y).range(0.0, 1000.0);
    t.field("box_size_z", &ReflectionProbeComponent::box_size_z).range(0.0, 1000.0);
    t.field("use_box_projection", &ReflectionProbeComponent::use_box_projection);
    t.field("resolution", &ReflectionProbeComponent::resolution).range(16.0, 2048.0);
    t.field("show_debug", &ReflectionProbeComponent::show_debug);
}

void RegisterGIProbeVolume() {
    using dse::GIProbeVolumeComponent;
    auto t = DSE_REFLECT_TYPE(GIProbeVolumeComponent);
    t.field("enabled", &GIProbeVolumeComponent::enabled);
    t.field("origin", &GIProbeVolumeComponent::origin);
    t.field("extent", &GIProbeVolumeComponent::extent);
    t.field("resolution_x", &GIProbeVolumeComponent::resolution_x).range(1.0, 256.0);
    t.field("resolution_y", &GIProbeVolumeComponent::resolution_y).range(1.0, 256.0);
    t.field("resolution_z", &GIProbeVolumeComponent::resolution_z).range(1.0, 256.0);
    t.field("irradiance_texels", &GIProbeVolumeComponent::irradiance_texels).range(1.0, 64.0);
    t.field("visibility_texels", &GIProbeVolumeComponent::visibility_texels).range(1.0, 64.0);
    t.field("rays_per_probe", &GIProbeVolumeComponent::rays_per_probe).range(1.0, 4096.0);
    t.field("hysteresis", &GIProbeVolumeComponent::hysteresis).range(0.0, 1.0);
    t.field("gi_intensity", &GIProbeVolumeComponent::gi_intensity).range(0.0, 16.0);
    t.field("normal_bias", &GIProbeVolumeComponent::normal_bias).range(0.0, 4.0);
    t.field("view_bias", &GIProbeVolumeComponent::view_bias).range(0.0, 4.0);
    t.field("show_debug_probes", &GIProbeVolumeComponent::show_debug_probes);
}

void RegisterFoliage() {
    using dse::FoliageComponent;
    auto t = DSE_REFLECT_TYPE(FoliageComponent);
    t.field("enabled", &FoliageComponent::enabled);
    t.field("wind_strength", &FoliageComponent::wind_strength).range(0.0, 10.0);
    t.field("stiffness", &FoliageComponent::stiffness).range(0.0, 1.0);
    t.field("phase_offset", &FoliageComponent::phase_offset);
    t.field("push_response", &FoliageComponent::push_response).range(0.0, 4.0);
}

void RegisterRigidBody3D() {
    using dse::RigidBody3DComponent;
    DSE_REFLECT_ENUM(dse::RigidBody3DType)
        .value("Static", dse::RigidBody3DType::Static)
        .value("Kinematic", dse::RigidBody3DType::Kinematic)
        .value("Dynamic", dse::RigidBody3DType::Dynamic)
        ;

    auto t = DSE_REFLECT_TYPE(RigidBody3DComponent);
    t.field("type", &RigidBody3DComponent::type);
    t.field("mass", &RigidBody3DComponent::mass).range(0.0, 10000.0);
    t.field("drag", &RigidBody3DComponent::drag).range(0.0, 100.0);
    t.field("angular_drag", &RigidBody3DComponent::angular_drag).range(0.0, 100.0);
    t.field("use_gravity", &RigidBody3DComponent::use_gravity);
    t.field("gravity_scale", &RigidBody3DComponent::gravity_scale).range(-10.0, 10.0);
    t.field("is_kinematic", &RigidBody3DComponent::is_kinematic);
    t.field("collision_layer", &RigidBody3DComponent::collision_layer);
    t.field("collision_mask", &RigidBody3DComponent::collision_mask);
}

void RegisterBoxCollider3D() {
    using dse::BoxCollider3DComponent;
    auto t = DSE_REFLECT_TYPE(BoxCollider3DComponent);
    t.field("size", &BoxCollider3DComponent::size);
    t.field("center", &BoxCollider3DComponent::center);
    t.field("is_trigger", &BoxCollider3DComponent::is_trigger);
    t.field("bounciness", &BoxCollider3DComponent::bounciness).range(0.0, 1.0);
    t.field("friction", &BoxCollider3DComponent::friction).range(0.0, 2.0);
}

void RegisterSphereCollider3D() {
    using dse::SphereCollider3DComponent;
    auto t = DSE_REFLECT_TYPE(SphereCollider3DComponent);
    t.field("radius", &SphereCollider3DComponent::radius).range(0.01, 1000.0);
    t.field("center", &SphereCollider3DComponent::center);
    t.field("is_trigger", &SphereCollider3DComponent::is_trigger);
    t.field("bounciness", &SphereCollider3DComponent::bounciness).range(0.0, 1.0);
    t.field("friction", &SphereCollider3DComponent::friction).range(0.0, 2.0);
}

void RegisterCapsuleCollider3D() {
    using dse::CapsuleCollider3DComponent;
    auto t = DSE_REFLECT_TYPE(CapsuleCollider3DComponent);
    t.field("radius", &CapsuleCollider3DComponent::radius).range(0.01, 100.0);
    t.field("height", &CapsuleCollider3DComponent::height).range(0.01, 100.0);
    t.field("center", &CapsuleCollider3DComponent::center);
    t.field("direction", &CapsuleCollider3DComponent::direction).range(0.0, 2.0).tooltip("0=X, 1=Y, 2=Z");
    t.field("is_trigger", &CapsuleCollider3DComponent::is_trigger);
    t.field("bounciness", &CapsuleCollider3DComponent::bounciness).range(0.0, 1.0);
    t.field("friction", &CapsuleCollider3DComponent::friction).range(0.0, 2.0);
}

void RegisterMeshCollider3D() {
    using dse::MeshCollider3DComponent;
    auto t = DSE_REFLECT_TYPE(MeshCollider3DComponent);
    t.field("convex", &MeshCollider3DComponent::convex);
    t.field("is_trigger", &MeshCollider3DComponent::is_trigger);
    t.field("bounciness", &MeshCollider3DComponent::bounciness).range(0.0, 1.0);
    t.field("friction", &MeshCollider3DComponent::friction).range(0.0, 2.0);
}

void RegisterCharacterController3D() {
    using dse::CharacterController3DComponent;
    auto t = DSE_REFLECT_TYPE(CharacterController3DComponent);
    t.field("radius", &CharacterController3DComponent::radius).range(0.01, 10.0);
    t.field("height", &CharacterController3DComponent::height).range(0.01, 10.0);
    t.field("slope_limit", &CharacterController3DComponent::slope_limit).range(0.0, 90.0);
    t.field("step_offset", &CharacterController3DComponent::step_offset).range(0.0, 5.0);
    t.field("skin_width", &CharacterController3DComponent::skin_width).range(0.0, 1.0);
    t.field("min_move_distance", &CharacterController3DComponent::min_move_distance).range(0.0, 1.0);
}

void RegisterJoint3D() {
    using dse::Joint3DComponent;
    DSE_REFLECT_ENUM(dse::Joint3DType)
        .value("Fixed", dse::Joint3DType::Fixed)
        .value("Hinge", dse::Joint3DType::Hinge)
        .value("Spring", dse::Joint3DType::Spring)
        .value("Distance", dse::Joint3DType::Distance)
        ;

    auto t = DSE_REFLECT_TYPE(Joint3DComponent);
    t.field("type", &Joint3DComponent::type);
    t.field("connected_entity_id", &Joint3DComponent::connected_entity_id);
    t.field("anchor", &Joint3DComponent::anchor);
    t.field("connected_anchor", &Joint3DComponent::connected_anchor);
    t.field("axis", &Joint3DComponent::axis);
    t.field("use_limits", &Joint3DComponent::use_limits);
    t.field("lower_limit", &Joint3DComponent::lower_limit).range(-180.0, 0.0);
    t.field("upper_limit", &Joint3DComponent::upper_limit).range(0.0, 180.0);
    t.field("min_distance", &Joint3DComponent::min_distance).range(0.0, 1000.0);
    t.field("max_distance", &Joint3DComponent::max_distance).range(0.0, 1000.0);
    t.field("spring_stiffness", &Joint3DComponent::spring_stiffness).range(0.0, 100000.0);
    t.field("spring_damping", &Joint3DComponent::spring_damping).range(0.0, 10000.0);
    t.field("break_force", &Joint3DComponent::break_force).range(0.0, 3.4e+38);
    t.field("break_torque", &Joint3DComponent::break_torque).range(0.0, 3.4e+38);
}

#if defined(DSE_ENABLE_PHYSX) || defined(DSE_ENABLE_JOLT)
void RegisterRagdoll() {
    using dse::RagdollComponent;
    auto t = DSE_REFLECT_TYPE(RagdollComponent);
    t.field("active", &RagdollComponent::active);
    t.field("auto_setup", &RagdollComponent::auto_setup);
    t.field("total_mass", &RagdollComponent::total_mass).range(0.1, 1000.0);
    t.field("joint_stiffness", &RagdollComponent::joint_stiffness).range(0.0, 10000.0);
    t.field("joint_damping", &RagdollComponent::joint_damping).range(0.0, 10000.0);
    t.field("collision_layer", &RagdollComponent::collision_layer);
    t.field("collision_mask", &RagdollComponent::collision_mask);
}
#endif

void RegisterSoftBody() {
    using dse::SoftBodyComponent;
    auto t = DSE_REFLECT_TYPE(SoftBodyComponent);
    t.field("enabled", &SoftBodyComponent::enabled);
    t.field("stiffness", &SoftBodyComponent::stiffness).range(0.0, 1.0);
    t.field("solver_iterations", &SoftBodyComponent::solver_iterations).range(1.0, 32.0);
    t.field("damping", &SoftBodyComponent::damping).range(0.0, 1.0);
    t.field("use_gravity", &SoftBodyComponent::use_gravity);
    t.field("gravity_scale", &SoftBodyComponent::gravity_scale).range(-10.0, 10.0);
    t.field("volume_stiffness", &SoftBodyComponent::volume_stiffness).range(0.0, 1.0);
}

#if defined(DSE_ENABLE_PHYSX) || defined(DSE_ENABLE_JOLT)
void RegisterVehicle() {
    using dse::VehicleComponent;
    auto t = DSE_REFLECT_TYPE(VehicleComponent);
    t.field("enabled", &VehicleComponent::enabled);
    t.field("max_engine_force", &VehicleComponent::max_engine_force).range(0.0, 100000.0);
    t.field("max_brake_force", &VehicleComponent::max_brake_force).range(0.0, 100000.0);
    t.field("max_steer_angle", &VehicleComponent::max_steer_angle).range(0.0, 90.0);
}
#endif

void RegisterRope() {
    using dse::RopeComponent;
    auto t = DSE_REFLECT_TYPE(RopeComponent);
    t.field("enabled", &RopeComponent::enabled);
    t.field("segment_count", &RopeComponent::segment_count).range(2.0, 200.0);
    t.field("segment_length", &RopeComponent::segment_length).range(0.01, 10.0);
    t.field("radius", &RopeComponent::radius).range(0.001, 1.0);
    t.field("damping", &RopeComponent::damping).range(0.0, 1.0);
    t.field("solver_iterations", &RopeComponent::solver_iterations).range(1.0, 32.0);
    t.field("use_gravity", &RopeComponent::use_gravity);
    t.field("gravity_scale", &RopeComponent::gravity_scale).range(-10.0, 10.0);
    t.field("anchor_entity_a", &RopeComponent::anchor_entity_a);
    t.field("anchor_entity_b", &RopeComponent::anchor_entity_b);
    t.field("anchor_offset_a", &RopeComponent::anchor_offset_a);
    t.field("anchor_offset_b", &RopeComponent::anchor_offset_b);
    t.field("start_position", &RopeComponent::start_position);
}

#if defined(DSE_ENABLE_PHYSX) || defined(DSE_ENABLE_JOLT)
void RegisterBuoyancy() {
    using dse::BuoyancyComponent;
    auto t = DSE_REFLECT_TYPE(BuoyancyComponent);
    t.field("enabled", &BuoyancyComponent::enabled);
    t.field("water_level", &BuoyancyComponent::water_level).range(-1000.0, 1000.0);
    t.field("use_fluid_system", &BuoyancyComponent::use_fluid_system);
    t.field("buoyancy_force", &BuoyancyComponent::buoyancy_force).range(0.0, 1000.0);
    t.field("water_drag", &BuoyancyComponent::water_drag).range(0.0, 100.0);
    t.field("water_angular_drag", &BuoyancyComponent::water_angular_drag).range(0.0, 100.0);
    t.field("submerge_depth", &BuoyancyComponent::submerge_depth).range(0.01, 100.0);
}
#endif

void RegisterAtmosphere() {
    using dse::AtmosphereComponent;
    auto t = DSE_REFLECT_TYPE(AtmosphereComponent);
    t.field("enabled", &AtmosphereComponent::enabled);
    t.field("planet_radius", &AtmosphereComponent::planet_radius).range(100000.0, 100000000.0);
    t.field("atmosphere_height", &AtmosphereComponent::atmosphere_height).range(1000.0, 1000000.0);
    t.field("rayleigh_coeff", &AtmosphereComponent::rayleigh_coeff);
    t.field("rayleigh_scale_height", &AtmosphereComponent::rayleigh_scale_height).range(100.0, 100000.0);
    t.field("mie_coeff", &AtmosphereComponent::mie_coeff).range(0.0, 0.001);
    t.field("mie_scale_height", &AtmosphereComponent::mie_scale_height).range(100.0, 10000.0);
    t.field("mie_g", &AtmosphereComponent::mie_g).range(-1.0, 1.0);
    t.field("mie_albedo", &AtmosphereComponent::mie_albedo);
    t.field("ozone_coeff", &AtmosphereComponent::ozone_coeff);
    t.field("ozone_center_h", &AtmosphereComponent::ozone_center_h).range(0.0, 100000.0);
    t.field("ozone_width", &AtmosphereComponent::ozone_width).range(0.0, 100000.0);
    t.field("sun_intensity", &AtmosphereComponent::sun_intensity);
    t.field("sun_disk_angle", &AtmosphereComponent::sun_disk_angle).range(0.0, 5.0);
    t.field("aerial_perspective_enabled", &AtmosphereComponent::aerial_perspective_enabled);
}

void RegisterVolumetricCloud() {
    using dse::VolumetricCloudComponent;
    auto t = DSE_REFLECT_TYPE(VolumetricCloudComponent);
    t.field("enabled", &VolumetricCloudComponent::enabled);
    t.field("cloud_bottom", &VolumetricCloudComponent::cloud_bottom).range(0.0, 20000.0);
    t.field("cloud_top", &VolumetricCloudComponent::cloud_top).range(0.0, 20000.0);
    t.field("coverage", &VolumetricCloudComponent::coverage).range(0.0, 1.0);
    t.field("density", &VolumetricCloudComponent::density).range(0.0, 1.0);
    t.field("shape_scale", &VolumetricCloudComponent::shape_scale).range(0.0, 0.01);
    t.field("detail_scale", &VolumetricCloudComponent::detail_scale).range(0.0, 0.01);
    t.field("detail_strength", &VolumetricCloudComponent::detail_strength).range(0.0, 1.0);
    t.field("erosion", &VolumetricCloudComponent::erosion).range(0.0, 1.0);
    t.field("wind_direction", &VolumetricCloudComponent::wind_direction);
    t.field("wind_speed", &VolumetricCloudComponent::wind_speed).range(0.0, 200.0);
    t.field("silver_intensity", &VolumetricCloudComponent::silver_intensity).range(0.0, 2.0);
    t.field("silver_spread", &VolumetricCloudComponent::silver_spread).range(0.0, 1.0);
    t.field("powder_strength", &VolumetricCloudComponent::powder_strength).range(0.0, 10.0);
    t.field("ambient_strength", &VolumetricCloudComponent::ambient_strength).range(0.0, 2.0);
    t.field("half_resolution", &VolumetricCloudComponent::half_resolution);
    t.field("temporal_reprojection", &VolumetricCloudComponent::temporal_reprojection);
    t.field("cloud_shadow_enabled", &VolumetricCloudComponent::cloud_shadow_enabled);
}

void RegisterDayNightCycle() {
    using dse::DayNightCycleComponent;
    auto t = DSE_REFLECT_TYPE(DayNightCycleComponent);
    t.field("enabled", &DayNightCycleComponent::enabled);
    t.field("time_of_day", &DayNightCycleComponent::time_of_day).range(0.0, 24.0);
    t.field("time_speed", &DayNightCycleComponent::time_speed).range(0.0, 100.0);
    t.field("auto_advance", &DayNightCycleComponent::auto_advance);
    t.field("latitude", &DayNightCycleComponent::latitude).range(-90.0, 90.0);
    t.field("longitude", &DayNightCycleComponent::longitude).range(-180.0, 180.0);
    t.field("day_of_year", &DayNightCycleComponent::day_of_year).range(1.0, 365.0);
}

void RegisterHair() {
    using dse::HairComponent;
    auto t = DSE_REFLECT_TYPE(HairComponent);
    t.field("enabled", &HairComponent::enabled);
    t.field("hair_asset_path", &HairComponent::hair_asset_path);
    t.field("damping", &HairComponent::damping).range(0.0, 1.0);
    t.field("stiffness_local", &HairComponent::stiffness_local).range(0.0, 1.0);
    t.field("stiffness_global", &HairComponent::stiffness_global).range(0.0, 1.0);
    t.field("gravity", &HairComponent::gravity).range(0.0, 100.0);
    t.field("wind", &HairComponent::wind);
    t.field("wind_turbulence", &HairComponent::wind_turbulence).range(0.0, 2.0);
    t.field("root_color", &HairComponent::root_color).color();
    t.field("tip_color", &HairComponent::tip_color).color();
    t.field("fiber_radius", &HairComponent::fiber_radius).range(0.001, 0.5);
    t.field("opacity", &HairComponent::opacity).range(0.0, 1.0);
    t.field("cast_shadow", &HairComponent::cast_shadow);
    t.field("receive_shadow", &HairComponent::receive_shadow);
}

void RegisterImpostor() {
    using dse::ImpostorComponent;
    auto t = DSE_REFLECT_TYPE(ImpostorComponent);
    t.field("enabled", &ImpostorComponent::enabled);
    t.field("atlas_path", &ImpostorComponent::atlas_path).tooltip("Baked .dimpostor atlas file");
    t.field("frames_x", &ImpostorComponent::frames_x).range(1, 32).tooltip("Atlas horizontal frames");
    t.field("frames_y", &ImpostorComponent::frames_y).range(1, 16).tooltip("Atlas vertical frames");
    t.field("transition_distance", &ImpostorComponent::transition_distance).range(1.0, 10000.0);
    t.field("fade_range", &ImpostorComponent::fade_range).range(0.1, 200.0);
    t.field("cull_distance", &ImpostorComponent::cull_distance).range(10.0, 50000.0);
    t.field("impostor_size", &ImpostorComponent::impostor_size).range(0.1, 10.0);
    t.field("pivot_offset", &ImpostorComponent::pivot_offset);
    t.field("cast_shadow", &ImpostorComponent::cast_shadow);
    t.field("use_frame_interpolation", &ImpostorComponent::use_frame_interpolation);
    t.field("normal_strength", &ImpostorComponent::normal_strength).range(0.0, 2.0);
    t.field("auto_from_lod_group", &ImpostorComponent::auto_from_lod_group);
}

void RegisterStreamingOrigin() {
    using dse::StreamingOriginComponent;
    auto t = DSE_REFLECT_TYPE(StreamingOriginComponent);
    t.field("enabled", &StreamingOriginComponent::enabled);
    t.field("load_radius", &StreamingOriginComponent::load_radius).range(32.0, 2048.0).tooltip("Load radius");
    t.field("unload_radius", &StreamingOriginComponent::unload_radius).range(64.0, 4096.0).tooltip("Unload radius (should > load)");
}

void RegisterWorldPartitionConfig() {
    using dse::WorldPartitionConfigComponent;
    auto t = DSE_REFLECT_TYPE(WorldPartitionConfigComponent);
    t.field("enabled", &WorldPartitionConfigComponent::enabled);
    t.field("cell_size", &WorldPartitionConfigComponent::cell_size).range(32.0, 1024.0).tooltip("Cell edge length");
    t.field("cells_directory", &WorldPartitionConfigComponent::cells_directory);
    t.field("grid_min_x", &WorldPartitionConfigComponent::grid_min_x);
    t.field("grid_max_x", &WorldPartitionConfigComponent::grid_max_x);
    t.field("grid_min_y", &WorldPartitionConfigComponent::grid_min_y);
    t.field("grid_max_y", &WorldPartitionConfigComponent::grid_max_y);
    t.field("max_loads_per_frame", &WorldPartitionConfigComponent::max_loads_per_frame).range(1, 16);
}

void RegisterHLODConfig() {
    using dse::render::HLODConfigComponent;
    auto t = DSE_REFLECT_TYPE(HLODConfigComponent);
    t.field("enabled", &HLODConfigComponent::enabled);
    t.field("hlod_data_path", &HLODConfigComponent::hlod_data_path).tooltip(".dhlod data file");
    t.field("distance_scale", &HLODConfigComponent::distance_scale).range(0.1, 10.0);
    t.field("hysteresis", &HLODConfigComponent::hysteresis).range(0.0, 0.5);
}

void RegisterVirtualTexture() {
    using dse::vt::VirtualTextureComponent;
    auto t = DSE_REFLECT_TYPE(VirtualTextureComponent);
    t.field("enabled", &VirtualTextureComponent::enabled);
    t.field("vt_id", &VirtualTextureComponent::vt_id);
    t.field("tile_data_path", &VirtualTextureComponent::tile_data_path).tooltip("VT tile data directory");
    t.field("virtual_width", &VirtualTextureComponent::virtual_width);
    t.field("virtual_height", &VirtualTextureComponent::virtual_height);
    t.field("mip_bias", &VirtualTextureComponent::mip_bias).range(-4.0, 4.0);
}

void RegisterLightmap() {
    using dse::render::LightmapComponent;
    auto t = DSE_REFLECT_TYPE(LightmapComponent);
    t.field("lightmap_path", &LightmapComponent::lightmap_path).tooltip(".dlightmap file path");
    t.field("intensity", &LightmapComponent::intensity).range(0.0, 5.0);
    t.field("st_offset", &LightmapComponent::st_offset).tooltip("UV scale(xy) + offset(zw)");
    t.field("use_ao", &LightmapComponent::use_ao).tooltip("Apply AO channel");
}

void RegisterCharacterMovementConfig() {
    using dse::CharacterMovementConfig;
    auto t = DSE_REFLECT_TYPE(CharacterMovementConfig);
    t.field("enabled", &CharacterMovementConfig::enabled);
    t.field("max_walk_speed", &CharacterMovementConfig::max_walk_speed).range(0.0, 100.0);
    t.field("max_sprint_speed", &CharacterMovementConfig::max_sprint_speed).range(0.0, 100.0);
    t.field("max_crouch_speed", &CharacterMovementConfig::max_crouch_speed).range(0.0, 50.0);
    t.field("ground_acceleration", &CharacterMovementConfig::ground_acceleration).range(0.0, 200.0);
    t.field("ground_deceleration", &CharacterMovementConfig::ground_deceleration).range(0.0, 200.0);
    t.field("ground_friction", &CharacterMovementConfig::ground_friction).range(0.0, 50.0);
    t.field("gravity", &CharacterMovementConfig::gravity).range(-100.0, 0.0);
    t.field("jump_velocity", &CharacterMovementConfig::jump_velocity).range(0.0, 50.0);
    t.field("max_jump_count", &CharacterMovementConfig::max_jump_count);
    t.field("coyote_time", &CharacterMovementConfig::coyote_time).range(0.0, 1.0);
    t.field("jump_buffer_time", &CharacterMovementConfig::jump_buffer_time).range(0.0, 1.0);
    t.field("air_control", &CharacterMovementConfig::air_control).range(0.0, 1.0);
    t.field("rotation_rate", &CharacterMovementConfig::rotation_rate).range(0.0, 3600.0);
    t.field("publish_events", &CharacterMovementConfig::publish_events);
    t.field("crouch_height", &CharacterMovementConfig::crouch_height).range(0.1, 2.0);
    t.field("stand_height", &CharacterMovementConfig::stand_height).range(0.1, 3.0);
    t.field("max_fall_speed", &CharacterMovementConfig::max_fall_speed).range(-100.0, 0.0);
    t.field("swim_speed", &CharacterMovementConfig::swim_speed).range(0.0, 50.0);
    t.field("fly_speed", &CharacterMovementConfig::fly_speed).range(0.0, 50.0);
}

void RegisterCharacterMovementState() {
    using dse::CharacterMovementState;
    auto t = DSE_REFLECT_TYPE(CharacterMovementState);
    t.field("input_direction", &CharacterMovementState::input_direction);
    t.field("input_jump", &CharacterMovementState::input_jump);
    t.field("input_sprint", &CharacterMovementState::input_sprint);
    t.field("input_crouch", &CharacterMovementState::input_crouch);
    t.field("velocity", &CharacterMovementState::velocity);
    t.field("is_grounded", &CharacterMovementState::is_grounded);
    t.field("is_jumping", &CharacterMovementState::is_jumping);
    t.field("jump_count", &CharacterMovementState::jump_count);
}

void RegisterSpringArm3D() {
    using dse::SpringArm3DComponent;
    auto t = DSE_REFLECT_TYPE(SpringArm3DComponent);
    t.field("enabled", &SpringArm3DComponent::enabled);
    t.field("target_offset", &SpringArm3DComponent::target_offset);
    t.field("arm_length", &SpringArm3DComponent::arm_length).range(0.0, 50.0);
    t.field("collision_test", &SpringArm3DComponent::collision_test);
    t.field("pitch", &SpringArm3DComponent::pitch).range(-90.0, 90.0);
    t.field("yaw", &SpringArm3DComponent::yaw);
    t.field("position_lag_speed", &SpringArm3DComponent::position_lag_speed).range(0.0, 100.0);
    t.field("shake_trauma", &SpringArm3DComponent::shake_trauma).range(0.0, 1.0);
    t.field("min_arm_length", &SpringArm3DComponent::min_arm_length).range(0.0, 10.0);
    t.field("max_arm_length", &SpringArm3DComponent::max_arm_length).range(0.0, 100.0);
    t.field("probe_radius", &SpringArm3DComponent::probe_radius).range(0.0, 2.0);
    t.field("min_pitch", &SpringArm3DComponent::min_pitch).range(-90.0, 0.0);
    t.field("max_pitch", &SpringArm3DComponent::max_pitch).range(0.0, 90.0);
    t.field("rotation_lag_speed", &SpringArm3DComponent::rotation_lag_speed).range(0.0, 100.0);
    t.field("first_person_fov", &SpringArm3DComponent::first_person_fov).range(30.0, 120.0);
    t.field("third_person_fov", &SpringArm3DComponent::third_person_fov).range(30.0, 120.0);
    t.field("shake_decay_rate", &SpringArm3DComponent::shake_decay_rate).range(0.0, 10.0);
    t.field("shake_max_offset", &SpringArm3DComponent::shake_max_offset).range(0.0, 2.0);
    t.field("shake_frequency", &SpringArm3DComponent::shake_frequency).range(0.0, 50.0);
}

void RegisterPlayerController() {
    using dse::PlayerControllerComponent;
    auto t = DSE_REFLECT_TYPE(PlayerControllerComponent);
    t.field("enabled", &PlayerControllerComponent::enabled);
    t.field("mouse_sensitivity", &PlayerControllerComponent::mouse_sensitivity).range(0.01, 5.0);
    t.field("gamepad_sensitivity", &PlayerControllerComponent::gamepad_sensitivity).range(0.1, 10.0);
    t.field("invert_y", &PlayerControllerComponent::invert_y);
    t.field("stick_dead_zone", &PlayerControllerComponent::stick_dead_zone).range(0.0, 0.5);
    t.field("move_response_curve", &PlayerControllerComponent::move_response_curve).range(0.5, 5.0);
    t.field("look_response_curve", &PlayerControllerComponent::look_response_curve).range(0.5, 5.0);
    t.field("stick_outer_dead_zone", &PlayerControllerComponent::stick_outer_dead_zone).range(0.5, 1.0);
}

void RegisterJiggleBone() {
    using dse::JiggleBoneComponent;
    {
        using dse::JiggleBoneConfig;
        auto c = DSE_REFLECT_TYPE(JiggleBoneConfig);
        c.field("bone_name", &JiggleBoneConfig::bone_name);
        c.field("stiffness", &JiggleBoneConfig::stiffness).range(0.0, 1.0);
        c.field("damping", &JiggleBoneConfig::damping).range(0.0, 1.0);
        c.field("gravity", &JiggleBoneConfig::gravity).range(0.0, 100.0);
        c.field("gravity_dir", &JiggleBoneConfig::gravity_dir);
        c.field("bone_length", &JiggleBoneConfig::bone_length).range(0.0, 10.0);
        c.field("rest_dir", &JiggleBoneConfig::rest_dir);
    }
    {
        using dse::JiggleSphereCollider;
        auto c = DSE_REFLECT_TYPE(JiggleSphereCollider);
        c.field("bone_name", &JiggleSphereCollider::bone_name);
        c.field("center", &JiggleSphereCollider::center);
        c.field("radius", &JiggleSphereCollider::radius).range(0.0, 10.0);
    }
    auto t = DSE_REFLECT_TYPE(JiggleBoneComponent);
    t.field("enabled", &JiggleBoneComponent::enabled);
    t.field("stiffness_scale", &JiggleBoneComponent::stiffness_scale).range(0.0, 4.0);
    t.field("damping_scale", &JiggleBoneComponent::damping_scale).range(0.0, 4.0);
    t.field("gravity_scale", &JiggleBoneComponent::gravity_scale).range(0.0, 4.0);
    t.field("bones", &JiggleBoneComponent::bones);
    t.field("colliders", &JiggleBoneComponent::colliders);
}

void RegisterGrass() {
    using dse::GrassComponent;
    auto t = DSE_REFLECT_TYPE(GrassComponent);
    t.field("enabled", &GrassComponent::enabled);
    t.field("density", &GrassComponent::density).range(0.0, 16.0).tooltip("Grass blades per unit area");
    t.field("spawn_radius", &GrassComponent::spawn_radius).range(1.0, 500.0);
    t.field("seed", &GrassComponent::seed);
    t.field("chunk_size", &GrassComponent::chunk_size).range(1.0, 64.0);
    t.field("blade_width", &GrassComponent::blade_width).range(0.0, 2.0);
    t.field("blade_height", &GrassComponent::blade_height).range(0.0, 8.0);
    t.field("blade_height_variation", &GrassComponent::blade_height_variation).range(0.0, 1.0);
    t.field("base_color", &GrassComponent::base_color).color();
    t.field("tip_color", &GrassComponent::tip_color).color();
    t.field("wind_direction", &GrassComponent::wind_direction);
    t.field("wind_speed", &GrassComponent::wind_speed).range(0.0, 10.0);
    t.field("wind_strength", &GrassComponent::wind_strength).range(0.0, 4.0);
    t.field("wind_turbulence", &GrassComponent::wind_turbulence).range(0.0, 4.0);
    t.field("lod_near", &GrassComponent::lod_near).range(0.0, 500.0);
    t.field("lod_far", &GrassComponent::lod_far).range(0.0, 500.0);
    t.field("fade_range", &GrassComponent::fade_range).range(0.0, 50.0);
    t.field("cast_shadow", &GrassComponent::cast_shadow);
    t.field("shadow_distance", &GrassComponent::shadow_distance).range(0.0, 200.0);
}

void RegisterLODGroup() {
    using dse::LODGroupComponent;
    {
        using dse::LODLevelConfig;
        auto c = DSE_REFLECT_TYPE(LODLevelConfig);
        c.field("mesh_path", &LODLevelConfig::mesh_path);
        c.field("screen_size_threshold", &LODLevelConfig::screen_size_threshold).range(0.0, 1.0);
    }
    auto t = DSE_REFLECT_TYPE(LODGroupComponent);
    t.field("enabled", &LODGroupComponent::enabled);
    t.field("levels", &LODGroupComponent::levels);
    t.field("global_scale", &LODGroupComponent::global_scale).range(0.0, 100.0);
    t.field("hysteresis", &LODGroupComponent::hysteresis).range(0.0, 1.0);
    t.field("min_screen_size", &LODGroupComponent::min_screen_size).range(0.0, 1.0);
    t.field("original_mesh_path", &LODGroupComponent::original_mesh_path);
}

void RegisterMorphTarget() {
    using dse::MorphTargetComponent;
    auto t = DSE_REFLECT_TYPE(MorphTargetComponent);
    t.field("enabled", &MorphTargetComponent::enabled);
}

void RegisterGpuParticle() {
    using dse::render::GpuParticleComponent;
    DSE_REFLECT_ENUM(dse::render::EmitterShape)
        .value("Point", dse::render::EmitterShape::Point)
        .value("Sphere", dse::render::EmitterShape::Sphere)
        .value("Cone", dse::render::EmitterShape::Cone)
        .value("Ring", dse::render::EmitterShape::Ring)
        .value("Box", dse::render::EmitterShape::Box)
        ;

    {
        using dse::render::GpuParticleEmitterConfig;
        auto c = DSE_REFLECT_TYPE(GpuParticleEmitterConfig);
        c.field("enabled", &GpuParticleEmitterConfig::enabled);
        c.field("max_particles", &GpuParticleEmitterConfig::max_particles).range(1, 1000000);
        c.field("emission_rate", &GpuParticleEmitterConfig::emission_rate).range(0.0, 100000.0);
        c.field("shape", &GpuParticleEmitterConfig::shape);
        c.field("shape_radius", &GpuParticleEmitterConfig::shape_radius).range(0.0, 1000.0);
        c.field("cone_angle", &GpuParticleEmitterConfig::cone_angle).range(0.0, 180.0);
        c.field("life_min", &GpuParticleEmitterConfig::life_min).range(0.0, 3600.0);
        c.field("life_max", &GpuParticleEmitterConfig::life_max).range(0.0, 3600.0);
        c.field("speed_min", &GpuParticleEmitterConfig::speed_min).range(0.0, 10000.0);
        c.field("speed_max", &GpuParticleEmitterConfig::speed_max).range(0.0, 10000.0);
        c.field("size_start", &GpuParticleEmitterConfig::size_start).range(0.0, 100.0);
        c.field("size_end", &GpuParticleEmitterConfig::size_end).range(0.0, 100.0);
        c.field("color_start", &GpuParticleEmitterConfig::color_start).color();
        c.field("color_end", &GpuParticleEmitterConfig::color_end).color();
        c.field("gravity", &GpuParticleEmitterConfig::gravity);
        c.field("wind", &GpuParticleEmitterConfig::wind);
        c.field("turbulence", &GpuParticleEmitterConfig::turbulence).range(0.0, 100.0);
        c.field("vortex_strength", &GpuParticleEmitterConfig::vortex_strength).range(0.0, 100.0);
        c.field("collision_enabled", &GpuParticleEmitterConfig::collision_enabled);
        c.field("collision_plane_y", &GpuParticleEmitterConfig::collision_plane_y);
        c.field("collision_bounce", &GpuParticleEmitterConfig::collision_bounce).range(0.0, 1.0);
        c.field("collision_friction", &GpuParticleEmitterConfig::collision_friction).range(0.0, 1.0);
        c.field("texture_path", &GpuParticleEmitterConfig::texture_path);
        c.field("additive_blend", &GpuParticleEmitterConfig::additive_blend);
        c.field("sort_particles", &GpuParticleEmitterConfig::sort_particles);
    }
    auto t = DSE_REFLECT_TYPE(GpuParticleComponent);
    t.field("config", &GpuParticleComponent::config);
    t.field("ping", &GpuParticleComponent::ping);
    t.field("emit_accumulator", &GpuParticleComponent::emit_accumulator);
    t.field("initialized", &GpuParticleComponent::initialized);
}

void RegisterHLODMember() {
    using dse::render::HLODMemberComponent;
    auto t = DSE_REFLECT_TYPE(HLODMemberComponent);
    t.field("cluster_index", &HLODMemberComponent::cluster_index);
    t.field("hidden_by_hlod", &HLODMemberComponent::hidden_by_hlod);
}

void RegisterUIRenderer() {
    using ::UIRendererComponent;
    auto t = DSE_REFLECT_TYPE(UIRendererComponent);
    t.field("color", &UIRendererComponent::color).color();
    t.field("uv", &UIRendererComponent::uv);
    t.field("order", &UIRendererComponent::order);
    t.field("visible", &UIRendererComponent::visible);
    t.field("scale", &UIRendererComponent::scale).range(0.0, 100.0);
    t.field("hover_scale", &UIRendererComponent::hover_scale).range(0.0, 10.0);
    t.field("pressed_scale", &UIRendererComponent::pressed_scale).range(0.0, 10.0);
    t.field("scale_lerp_speed", &UIRendererComponent::scale_lerp_speed).range(0.0, 100.0);
    t.field("position", &UIRendererComponent::position);
    t.field("size", &UIRendererComponent::size);
    t.field("anchor_min", &UIRendererComponent::anchor_min);
    t.field("anchor_max", &UIRendererComponent::anchor_max);
    t.field("pivot", &UIRendererComponent::pivot);
    t.field("interactable", &UIRendererComponent::interactable);
    t.field("nine_slice_enabled", &UIRendererComponent::nine_slice_enabled);
    t.field("nine_slice_border", &UIRendererComponent::nine_slice_border);
    t.field("nine_slice_src_size", &UIRendererComponent::nine_slice_src_size);
    t.field("use_sdf_shader", &UIRendererComponent::use_sdf_shader);
    t.field("sdf_threshold", &UIRendererComponent::sdf_threshold).range(0.0, 1.0);
    t.field("sdf_smoothing", &UIRendererComponent::sdf_smoothing).range(0.0, 1.0);
    t.field("sdf_outline_width", &UIRendererComponent::sdf_outline_width).range(0.0, 10.0);
    t.field("sdf_shadow_softness", &UIRendererComponent::sdf_shadow_softness).range(0.0, 10.0);
}

void RegisterUIButton() {
    using ::UIButtonComponent;
    auto t = DSE_REFLECT_TYPE(UIButtonComponent);
    t.field("normal_color", &UIButtonComponent::normal_color).color();
    t.field("hover_color", &UIButtonComponent::hover_color).color();
    t.field("pressed_color", &UIButtonComponent::pressed_color).color();
}

void RegisterUILabel() {
    using ::UILabelComponent;
    auto t = DSE_REFLECT_TYPE(UILabelComponent);
    t.field("text", &UILabelComponent::text);
    t.field("use_localization", &UILabelComponent::use_localization);
    t.field("localization_key", &UILabelComponent::localization_key);
    t.field("fallback_text", &UILabelComponent::fallback_text);
    t.field("numeric_mode", &UILabelComponent::numeric_mode);
    t.field("glyph_size", &UILabelComponent::glyph_size);
    t.field("offset", &UILabelComponent::offset);
    t.field("spacing", &UILabelComponent::spacing);
    t.field("atlas_cols", &UILabelComponent::atlas_cols);
    t.field("atlas_rows", &UILabelComponent::atlas_rows);
    t.field("ascii_start", &UILabelComponent::ascii_start);
    t.field("color", &UILabelComponent::color).color();
    t.field("font_id", &UILabelComponent::font_id);
    t.field("font_size", &UILabelComponent::font_size).range(4.0, 512.0);
    t.field("use_sdf", &UILabelComponent::use_sdf);
    t.field("max_width", &UILabelComponent::max_width).range(0.0, 10000.0);
    t.field("text_align", &UILabelComponent::text_align);
    t.field("overflow_mode", &UILabelComponent::overflow_mode);
    t.field("max_lines", &UILabelComponent::max_lines);
    t.field("line_spacing_extra", &UILabelComponent::line_spacing_extra);
}

void RegisterUIPanel() {
    using ::UIPanelComponent;
    auto t = DSE_REFLECT_TYPE(UIPanelComponent);
    t.field("blocks_input", &UIPanelComponent::blocks_input);
}

void RegisterUIMask() {
    using ::UIMaskComponent;
    auto t = DSE_REFLECT_TYPE(UIMaskComponent);
    t.field("enabled", &UIMaskComponent::enabled);
    t.field("size", &UIMaskComponent::size);
    t.field("offset", &UIMaskComponent::offset);
    t.field("block_outside_input", &UIMaskComponent::block_outside_input);
}

void RegisterUIAnchor() {
    using ::UIAnchorComponent;
    auto t = DSE_REFLECT_TYPE(UIAnchorComponent);
    t.field("anchor", &UIAnchorComponent::anchor);
    t.field("offset", &UIAnchorComponent::offset);
}

void RegisterUIGridLayout() {
    using ::UIGridLayoutComponent;
    auto t = DSE_REFLECT_TYPE(UIGridLayoutComponent);
    t.field("columns", &UIGridLayoutComponent::columns);
    t.field("rows", &UIGridLayoutComponent::rows);
    t.field("cell_size", &UIGridLayoutComponent::cell_size);
    t.field("spacing", &UIGridLayoutComponent::spacing);
    t.field("alignment", &UIGridLayoutComponent::alignment);
}

void RegisterUIBoxLayout() {
    using ::UIBoxLayoutComponent;
    auto t = DSE_REFLECT_TYPE(UIBoxLayoutComponent);
    t.field("vertical", &UIBoxLayoutComponent::vertical);
    t.field("spacing", &UIBoxLayoutComponent::spacing);
    t.field("padding", &UIBoxLayoutComponent::padding);
    t.field("align_main", &UIBoxLayoutComponent::align_main);
    t.field("align_cross", &UIBoxLayoutComponent::align_cross);
    t.field("reverse", &UIBoxLayoutComponent::reverse);
}

void RegisterUICanvasScaler() {
    using ::UICanvasScalerComponent;
    auto t = DSE_REFLECT_TYPE(UICanvasScalerComponent);
    t.field("reference_resolution", &UICanvasScalerComponent::reference_resolution);
    t.field("scale_factor", &UICanvasScalerComponent::scale_factor);
    t.field("match_width_or_height", &UICanvasScalerComponent::match_width_or_height);
    t.field("match", &UICanvasScalerComponent::match).range(0.0, 1.0);
    t.field("pixel_snap", &UICanvasScalerComponent::pixel_snap);
}

void RegisterUIScrollView() {
    using ::UIScrollViewComponent;
    auto t = DSE_REFLECT_TYPE(UIScrollViewComponent);
    t.field("content_size", &UIScrollViewComponent::content_size);
    t.field("viewport_size", &UIScrollViewComponent::viewport_size);
    t.field("scroll_offset", &UIScrollViewComponent::scroll_offset);
    t.field("horizontal", &UIScrollViewComponent::horizontal);
    t.field("vertical", &UIScrollViewComponent::vertical);
    t.field("elastic", &UIScrollViewComponent::elastic);
    t.field("elasticity", &UIScrollViewComponent::elasticity).range(0.0, 1.0);
    t.field("inertia", &UIScrollViewComponent::inertia);
    t.field("deceleration_rate", &UIScrollViewComponent::deceleration_rate).range(0.0, 1.0);
    t.field("show_scrollbar", &UIScrollViewComponent::show_scrollbar);
    t.field("scrollbar_width", &UIScrollViewComponent::scrollbar_width);
    t.field("scrollbar_color", &UIScrollViewComponent::scrollbar_color).color();
}

void RegisterUISlider() {
    using ::UISliderComponent;
    auto t = DSE_REFLECT_TYPE(UISliderComponent);
    t.field("value", &UISliderComponent::value);
    t.field("min_value", &UISliderComponent::min_value);
    t.field("max_value", &UISliderComponent::max_value);
    t.field("whole_numbers", &UISliderComponent::whole_numbers);
    t.field("vertical", &UISliderComponent::vertical);
    t.field("track_color", &UISliderComponent::track_color).color();
    t.field("fill_color", &UISliderComponent::fill_color).color();
    t.field("handle_color", &UISliderComponent::handle_color).color();
    t.field("handle_size", &UISliderComponent::handle_size);
}

void RegisterUIToggle() {
    using ::UIToggleComponent;
    auto t = DSE_REFLECT_TYPE(UIToggleComponent);
    t.field("is_on", &UIToggleComponent::is_on);
    t.field("group", &UIToggleComponent::group);
    t.field("on_color", &UIToggleComponent::on_color).color();
    t.field("off_color", &UIToggleComponent::off_color).color();
    t.field("transition_duration", &UIToggleComponent::transition_duration);
}

void RegisterUIProgressBar() {
    using ::UIProgressBarComponent;
    auto t = DSE_REFLECT_TYPE(UIProgressBarComponent);
    t.field("value", &UIProgressBarComponent::value);
    t.field("max_value", &UIProgressBarComponent::max_value);
    t.field("right_to_left", &UIProgressBarComponent::right_to_left);
    t.field("vertical", &UIProgressBarComponent::vertical);
    t.field("background_color", &UIProgressBarComponent::background_color).color();
    t.field("fill_color", &UIProgressBarComponent::fill_color).color();
}

void RegisterUITextInput() {
    using ::UITextInputComponent;
    auto t = DSE_REFLECT_TYPE(UITextInputComponent);
    t.field("text", &UITextInputComponent::text);
    t.field("placeholder", &UITextInputComponent::placeholder);
    t.field("cursor_position", &UITextInputComponent::cursor_position);
    t.field("selection_start", &UITextInputComponent::selection_start);
    t.field("selection_end", &UITextInputComponent::selection_end);
    t.field("max_length", &UITextInputComponent::max_length);
    t.field("is_focused", &UITextInputComponent::is_focused);
    t.field("is_password", &UITextInputComponent::is_password);
    t.field("multiline", &UITextInputComponent::multiline);
    t.field("read_only", &UITextInputComponent::read_only);
    t.field("submit_on_enter", &UITextInputComponent::submit_on_enter);
    t.field("text_color", &UITextInputComponent::text_color).color();
    t.field("placeholder_color", &UITextInputComponent::placeholder_color).color();
    t.field("cursor_color", &UITextInputComponent::cursor_color).color();
    t.field("selection_color", &UITextInputComponent::selection_color).color();
    t.field("cursor_blink_rate", &UITextInputComponent::cursor_blink_rate);
}

void RegisterUIDropdown() {
    using ::UIDropdownComponent;
    auto t = DSE_REFLECT_TYPE(UIDropdownComponent);
    t.field("selected_index", &UIDropdownComponent::selected_index);
    t.field("item_height", &UIDropdownComponent::item_height);
    t.field("max_visible_items", &UIDropdownComponent::max_visible_items);
    t.field("normal_color", &UIDropdownComponent::normal_color).color();
    t.field("hover_color", &UIDropdownComponent::hover_color).color();
    t.field("selected_color", &UIDropdownComponent::selected_color).color();
    t.field("text_color", &UIDropdownComponent::text_color).color();
}

void RegisterUIFilledImage() {
    using ::UIFilledImageComponent;
    DSE_REFLECT_ENUM(UIFillMethod)
        .value("Horizontal", UIFillMethod::Horizontal)
        .value("Vertical", UIFillMethod::Vertical)
        .value("Radial360", UIFillMethod::Radial360)
        .value("Radial180", UIFillMethod::Radial180)
        .value("Radial90", UIFillMethod::Radial90)
        ;
    DSE_REFLECT_ENUM(UIFillOrigin)
        .value("Left", UIFillOrigin::Left)
        .value("Right", UIFillOrigin::Right)
        .value("Bottom", UIFillOrigin::Bottom)
        .value("Top", UIFillOrigin::Top)
        .value("Center", UIFillOrigin::Center)
        ;

    auto t = DSE_REFLECT_TYPE(UIFilledImageComponent);
    t.field("fill_amount", &UIFilledImageComponent::fill_amount).range(0.0, 1.0);
    t.field("fill_method", &UIFilledImageComponent::fill_method);
    t.field("fill_origin", &UIFilledImageComponent::fill_origin);
    t.field("clockwise", &UIFilledImageComponent::clockwise);
}

void RegisterUIFocusNavigable() {
    using ::UIFocusNavigableComponent;
    auto t = DSE_REFLECT_TYPE(UIFocusNavigableComponent);
    t.field("tab_index", &UIFocusNavigableComponent::tab_index);
    t.field("is_focused", &UIFocusNavigableComponent::is_focused);
    t.field("focus_tint", &UIFocusNavigableComponent::focus_tint).color();
}

void RegisterUIEventPropagation() {
    using ::UIEventPropagationComponent;
    auto t = DSE_REFLECT_TYPE(UIEventPropagationComponent);
    t.field("bubbles_click", &UIEventPropagationComponent::bubbles_click);
    t.field("bubbles_hover", &UIEventPropagationComponent::bubbles_hover);
}

void RegisterUIVisualEffect() {
    using ::UIVisualEffectComponent;
    DSE_REFLECT_ENUM(UIGradientDirection)
        .value("Horizontal", UIGradientDirection::Horizontal)
        .value("Vertical", UIGradientDirection::Vertical)
        .value("Diagonal", UIGradientDirection::Diagonal)
        ;

    auto t = DSE_REFLECT_TYPE(UIVisualEffectComponent);
    t.field("corner_radius", &UIVisualEffectComponent::corner_radius);
    t.field("gradient_color_start", &UIVisualEffectComponent::gradient_color_start).color();
    t.field("gradient_color_end", &UIVisualEffectComponent::gradient_color_end).color();
    t.field("gradient_direction", &UIVisualEffectComponent::gradient_direction);
    t.field("blur_radius", &UIVisualEffectComponent::blur_radius);
    t.field("blur_intensity", &UIVisualEffectComponent::blur_intensity).range(0.0, 1.0);
}

void RegisterUIAnimation() {
    using ::UIAnimationComponent;
    auto t = DSE_REFLECT_TYPE(UIAnimationComponent);
    t.field("target_position", &UIAnimationComponent::target_position);
    t.field("target_scale", &UIAnimationComponent::target_scale);
    t.field("target_alpha", &UIAnimationComponent::target_alpha).range(0.0, 1.0);
    t.field("target_color", &UIAnimationComponent::target_color).color();
    t.field("animate_position", &UIAnimationComponent::animate_position);
    t.field("animate_scale", &UIAnimationComponent::animate_scale);
    t.field("animate_alpha", &UIAnimationComponent::animate_alpha);
    t.field("animate_color", &UIAnimationComponent::animate_color);
    t.field("duration", &UIAnimationComponent::duration);
    t.field("delay", &UIAnimationComponent::delay);
    t.field("loop", &UIAnimationComponent::loop);
    t.field("ping_pong", &UIAnimationComponent::ping_pong);
    t.field("playing", &UIAnimationComponent::playing);
    t.field("easing", &UIAnimationComponent::easing);
}

void RegisterUIRichText() {
    using ::UIRichTextComponent;
    auto t = DSE_REFLECT_TYPE(UIRichTextComponent);
    t.field("text", &UIRichTextComponent::text);
    t.field("default_color", &UIRichTextComponent::default_color).color();
    t.field("enable_shadow", &UIRichTextComponent::enable_shadow);
    t.field("shadow_offset", &UIRichTextComponent::shadow_offset);
    t.field("shadow_color", &UIRichTextComponent::shadow_color).color();
    t.field("enable_outline", &UIRichTextComponent::enable_outline);
    t.field("outline_color", &UIRichTextComponent::outline_color).color();
    t.field("outline_width", &UIRichTextComponent::outline_width);
}

void RegisterUIJoystick() {
    using ::UIJoystickComponent;
    auto t = DSE_REFLECT_TYPE(UIJoystickComponent);
    t.field("direction", &UIJoystickComponent::direction);
    t.field("max_radius", &UIJoystickComponent::max_radius);
    t.field("follow_pointer", &UIJoystickComponent::follow_pointer);
    t.field("reset_on_release", &UIJoystickComponent::reset_on_release);
    t.field("is_dragging", &UIJoystickComponent::is_dragging);
    t.field("drag_anchor", &UIJoystickComponent::drag_anchor);
}

void RegisterUIContentSizeFitter() {
    using ::UIContentSizeFitterComponent;
    auto t = DSE_REFLECT_TYPE(UIContentSizeFitterComponent);
    t.field("fit_width", &UIContentSizeFitterComponent::fit_width);
    t.field("fit_height", &UIContentSizeFitterComponent::fit_height);
    t.field("min_size", &UIContentSizeFitterComponent::min_size);
    t.field("max_size", &UIContentSizeFitterComponent::max_size);
}

void RegisterSpriteRenderer() {
    using ::SpriteRendererComponent;
    DSE_REFLECT_ENUM(SpriteBlendMode)
        .value("Alpha", SpriteBlendMode::Alpha)
        .value("Additive", SpriteBlendMode::Additive)
        .value("Multiply", SpriteBlendMode::Multiply)
        ;

    auto t = DSE_REFLECT_TYPE(SpriteRendererComponent);
    t.field("material_instance_id", &SpriteRendererComponent::material_instance_id);
    t.field("shader_variant", &SpriteRendererComponent::shader_variant);
    t.field("blend_mode", &SpriteRendererComponent::blend_mode);
    t.field("color", &SpriteRendererComponent::color).color();
    t.field("uv", &SpriteRendererComponent::uv);
    t.field("uv_offset", &SpriteRendererComponent::uv_offset);
    t.field("uv_scroll_speed", &SpriteRendererComponent::uv_scroll_speed);
    t.field("sorting_layer", &SpriteRendererComponent::sorting_layer);
    t.field("order_in_layer", &SpriteRendererComponent::order_in_layer);
    t.field("visible", &SpriteRendererComponent::visible);
}

void RegisterMaterialInstance() {
    using ::MaterialInstanceComponent;
    auto t = DSE_REFLECT_TYPE(MaterialInstanceComponent);
    t.field("material_id", &MaterialInstanceComponent::material_id);
    t.field("name", &MaterialInstanceComponent::name);
    t.field("shader_variant", &MaterialInstanceComponent::shader_variant);
    t.field("blend_mode", &MaterialInstanceComponent::blend_mode);
    t.field("tint", &MaterialInstanceComponent::tint).color();
    t.field("uv_rect", &MaterialInstanceComponent::uv_rect);
}

void RegisterLight2D() {
    using ::Light2DComponent;
    DSE_REFLECT_ENUM(Light2DType)
        .value("Point", Light2DType::Point)
        .value("Spot", Light2DType::Spot)
        .value("Directional", Light2DType::Directional)
        ;
    DSE_REFLECT_ENUM(Shadow2DMode)
        .value("None", Shadow2DMode::None)
        .value("Hard", Shadow2DMode::Hard)
        .value("Soft", Shadow2DMode::Soft)
        ;

    auto t = DSE_REFLECT_TYPE(Light2DComponent);
    t.field("type", &Light2DComponent::type);
    t.field("color", &Light2DComponent::color).color();
    t.field("intensity", &Light2DComponent::intensity).range(0.0, 100.0);
    t.field("range", &Light2DComponent::range).range(0.0, 1000.0);
    t.field("falloff", &Light2DComponent::falloff).range(0.0, 10.0);
    t.field("spot_angle", &Light2DComponent::spot_angle).range(0.0, 180.0);
    t.field("spot_outer_angle", &Light2DComponent::spot_outer_angle).range(0.0, 180.0);
    t.field("direction_angle", &Light2DComponent::direction_angle);
    t.field("shadow_mode", &Light2DComponent::shadow_mode);
    t.field("shadow_strength", &Light2DComponent::shadow_strength).range(0.0, 1.0);
    t.field("shadow_ray_count", &Light2DComponent::shadow_ray_count);
    t.field("enabled", &Light2DComponent::enabled);
    t.field("layer_mask", &Light2DComponent::layer_mask);
}

void RegisterAmbient2D() {
    using ::Ambient2DComponent;
    auto t = DSE_REFLECT_TYPE(Ambient2DComponent);
    t.field("color", &Ambient2DComponent::color).color();
    t.field("intensity", &Ambient2DComponent::intensity).range(0.0, 10.0);
}

void RegisterNormalMap2D() {
    using ::NormalMap2DComponent;
    auto t = DSE_REFLECT_TYPE(NormalMap2DComponent);
    t.field("normal_strength", &NormalMap2DComponent::normal_strength).range(0.0, 4.0);
}

void RegisterAudioSource() {
    using ::AudioSourceComponent;
    DSE_REFLECT_ENUM(AudioAttenuationModel)
        .value("Inverse", AudioAttenuationModel::Inverse)
        .value("Linear", AudioAttenuationModel::Linear)
        .value("Exponential", AudioAttenuationModel::Exponential)
        ;

    auto t = DSE_REFLECT_TYPE(AudioSourceComponent);
    t.field("play_on_awake", &AudioSourceComponent::play_on_awake);
    t.field("loop", &AudioSourceComponent::loop);
    t.field("volume", &AudioSourceComponent::volume).range(0.0, 4.0);
    t.field("pitch", &AudioSourceComponent::pitch).range(0.0, 4.0);
    t.field("spatial_enabled", &AudioSourceComponent::spatial_enabled);
    t.field("min_distance", &AudioSourceComponent::min_distance);
    t.field("max_distance", &AudioSourceComponent::max_distance);
    t.field("rolloff", &AudioSourceComponent::rolloff).range(0.0, 10.0);
    t.field("attenuation_model", &AudioSourceComponent::attenuation_model);
    t.field("occlusion_enabled", &AudioSourceComponent::occlusion_enabled);
    t.field("occlusion_factor", &AudioSourceComponent::occlusion_factor).range(0.0, 1.0);
    t.field("bus_name", &AudioSourceComponent::bus_name);
}

void RegisterAudioListener() {
    using ::AudioListenerComponent;
    auto t = DSE_REFLECT_TYPE(AudioListenerComponent);
    t.field("enabled", &AudioListenerComponent::enabled);
    t.field("listener_index", &AudioListenerComponent::listener_index);
}

void RegisterScript() {
    using ::ScriptComponent;
    auto t = DSE_REFLECT_TYPE(ScriptComponent);
    t.field("script_path", &ScriptComponent::script_path);
    t.field("enabled", &ScriptComponent::enabled);
}

void RegisterLuaScript() {
    using ::LuaScriptComponent;
    auto t = DSE_REFLECT_TYPE(LuaScriptComponent);
    t.field("script_path", &LuaScriptComponent::script_path);
    t.field("is_initialized", &LuaScriptComponent::is_initialized);
}

void RegisterCSharpScript() {
    using ::CSharpScriptComponent;
    auto t = DSE_REFLECT_TYPE(CSharpScriptComponent);
    t.field("class_name", &CSharpScriptComponent::class_name);
    t.field("enabled", &CSharpScriptComponent::enabled);
    t.field("is_bound", &CSharpScriptComponent::is_bound);
}

}  // namespace

void EnsureCoreReflectionRegistered() {
    static bool registered = false;
    if (registered) return;
    registered = true;
    RegisterTransform();
    RegisterCamera3D();
    RegisterMeshRenderer();
    RegisterDirectionalLight3D();
    RegisterPointLight();
    RegisterSpotLight();
    RegisterSkyLight();
    RegisterTree();
    RegisterTerrainTileManager();
    RegisterDynamicObstacle();
    RegisterNavMeshAutoRebake();
    RegisterPostProcess();
    RegisterAnimator3D();
    RegisterDecal();
    RegisterSkybox();
    RegisterFreeCameraController();
    RegisterSubScene();
    RegisterBoundingBox();
    RegisterWater();
    RegisterLightProbe();
    RegisterReflectionProbe();
    RegisterGIProbeVolume();
    RegisterFoliage();
    RegisterRigidBody3D();
    RegisterBoxCollider3D();
    RegisterSphereCollider3D();
    RegisterCapsuleCollider3D();
    RegisterMeshCollider3D();
    RegisterCharacterController3D();
    RegisterJoint3D();
#if defined(DSE_ENABLE_PHYSX) || defined(DSE_ENABLE_JOLT)
    RegisterRagdoll();
#endif
    RegisterSoftBody();
#if defined(DSE_ENABLE_PHYSX) || defined(DSE_ENABLE_JOLT)
    RegisterVehicle();
#endif
    RegisterRope();
#if defined(DSE_ENABLE_PHYSX) || defined(DSE_ENABLE_JOLT)
    RegisterBuoyancy();
#endif
    RegisterAtmosphere();
    RegisterVolumetricCloud();
    RegisterDayNightCycle();
    RegisterHair();
    RegisterImpostor();
    RegisterStreamingOrigin();
    RegisterWorldPartitionConfig();
    RegisterHLODConfig();
    RegisterVirtualTexture();
    RegisterLightmap();
    RegisterCharacterMovementConfig();
    RegisterCharacterMovementState();
    RegisterSpringArm3D();
    RegisterPlayerController();
    RegisterJiggleBone();
    RegisterGrass();
    RegisterLODGroup();
    RegisterMorphTarget();
    RegisterGpuParticle();
    RegisterHLODMember();
    RegisterUIRenderer();
    RegisterUIButton();
    RegisterUILabel();
    RegisterUIPanel();
    RegisterUIMask();
    RegisterUIAnchor();
    RegisterUIGridLayout();
    RegisterUIBoxLayout();
    RegisterUICanvasScaler();
    RegisterUIScrollView();
    RegisterUISlider();
    RegisterUIToggle();
    RegisterUIProgressBar();
    RegisterUITextInput();
    RegisterUIDropdown();
    RegisterUIFilledImage();
    RegisterUIFocusNavigable();
    RegisterUIEventPropagation();
    RegisterUIVisualEffect();
    RegisterUIAnimation();
    RegisterUIRichText();
    RegisterUIJoystick();
    RegisterUIContentSizeFitter();
    RegisterSpriteRenderer();
    RegisterMaterialInstance();
    RegisterLight2D();
    RegisterAmbient2D();
    RegisterNormalMap2D();
    RegisterAudioSource();
    RegisterAudioListener();
    RegisterScript();
    RegisterLuaScript();
    RegisterCSharpScript();
}

}  // namespace dse::reflect
