/**
 * @file shader_graph_codegen.cpp
 * @brief ShaderGraphAsset → GLSL/HLSL 源码生成实现
 */

#include "engine/render/shader_graph/shader_graph_codegen.h"

#include <queue>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>

namespace dse {
namespace shadergraph {
namespace {

bool IsHLSL(ShaderTarget t) { return t == ShaderTarget::HLSL; }
bool IsVulkan(ShaderTarget t) { return t == ShaderTarget::GLSL_VULKAN; }
bool IsES(ShaderTarget t) { return t == ShaderTarget::GLSL_ES; }

// GLSL 方言的 #version 行（不含 HLSL）。
const char* GlslVersionLine(ShaderTarget t) {
    if (t == ShaderTarget::GLSL_VULKAN) return "#version 450\n";
    if (t == ShaderTarget::GLSL_ES) return "#version 300 es\n";
    return "#version 430\n";
}

// 向量类型名：n=1 float, 2 vec2/float2, 3 vec3/float3, 4 vec4/float4。
std::string VecT(ShaderTarget t, int n) {
    if (n <= 1) return "float";
    if (IsHLSL(t)) return "float" + std::to_string(n);
    return "vec" + std::to_string(n);
}

std::string Mat3T(ShaderTarget t) { return IsHLSL(t) ? "float3x3" : "mat3"; }
std::string Mat2T(ShaderTarget t) { return IsHLSL(t) ? "float2x2" : "mat2"; }

// 内建函数名映射：绝大多数同名，少数不同。
std::string Fn(ShaderTarget t, const std::string& glsl_name) {
    if (IsHLSL(t)) {
        if (glsl_name == "mix") return "lerp";
        if (glsl_name == "fract") return "frac";
        if (glsl_name == "mod") return "fmod";
    }
    return glsl_name;
}

// 矩阵×向量：GLSL 用 *，HLSL 用 mul()。
std::string MulMV(ShaderTarget t, const std::string& m, const std::string& v) {
    if (IsHLSL(t)) return "mul(" + m + ", " + v + ")";
    return "(" + m + " * " + v + ")";
}

// atan(y, x)：GLSL atan / HLSL atan2。
std::string Atan2(ShaderTarget t, const std::string& y, const std::string& x) {
    return (IsHLSL(t) ? "atan2(" : "atan(") + y + ", " + x + ")";
}

// 纹理采样：GLSL texture(sampler, uv) / HLSL tex.Sample(tex##_s, uv)。
std::string TexSample(ShaderTarget t, const std::string& tex, const std::string& uv) {
    if (IsHLSL(t)) return tex + ".Sample(" + tex + "_s, " + uv + ")";
    return "texture(" + tex + ", " + uv + ")";
}

std::string F(float v) {
    std::ostringstream o;
    o << v;
    std::string s = o.str();
    if (s.find('.') == std::string::npos && s.find('e') == std::string::npos &&
        s.find("inf") == std::string::npos && s.find("nan") == std::string::npos) {
        s += ".0";
    }
    return s;
}

// ── 顶点着色器（后端各一份，语义与引擎网格顶点契约一致）─────────────────────
// GLSL 家族共用一份，按方言微调：Vulkan 给 varying 显式 location，WebGL2 加 precision
// 并去掉 UBO 的 binding 限定符（ES 3.00 不支持 UBO binding layout）。
std::string VertexGLSLFamily(ShaderTarget t) {
    const bool vulkan = IsVulkan(t);
    const bool es = IsES(t);
    std::ostringstream o;
    o << "// Auto-generated by DSEngine Shader Graph (vertex, " << ShaderTargetName(t) << ")\n";
    o << GlslVersionLine(t);
    if (es) o << "precision highp float;\n";
    o << "\n";
    o << "layout(location = 0) in vec3 a_pos;\n";
    o << "layout(location = 1) in vec4 a_color;\n";
    o << "layout(location = 2) in vec2 a_uv;\n";
    o << "layout(location = 3) in vec3 a_normal;\n";
    o << "layout(location = 4) in vec3 a_tangent;\n\n";
    o << (es ? "layout(std140) uniform PerFrame {\n" : "layout(std140, binding = 0) uniform PerFrame {\n");
    o << "    mat4 vp;\n    mat4 view;\n    vec4 camera_pos;\n";
    o << "    vec4 foliage_wind;\n    vec4 foliage_push;\n};\n\n";
    const char* varyings[] = {"vec2 v_uv", "vec3 v_normal", "vec3 v_world_pos",
                              "vec3 v_tangent", "vec3 v_bitangent", "vec4 v_color"};
    for (int i = 0; i < 6; ++i) {
        if (vulkan) o << "layout(location = " << i << ") ";
        o << "out " << varyings[i] << ";\n";
    }
    o << "\nvoid main() {\n";
    o << "    v_world_pos = a_pos;\n    v_normal = a_normal;\n";
    o << "    v_tangent = a_tangent;\n";
    o << "    v_bitangent = cross(a_normal, a_tangent);\n";
    o << "    v_uv = a_uv;\n    v_color = a_color;\n";
    o << "    gl_Position = vp * vec4(a_pos, 1.0);\n";
    o << "}\n";
    return o.str();
}

std::string VertexHLSL() {
    std::ostringstream o;
    o << "// Auto-generated by DSEngine Shader Graph (vertex, HLSL)\n";
    o << "cbuffer PerFrame : register(b0) {\n";
    o << "    float4x4 vp;\n    float4x4 view;\n    float4 camera_pos;\n";
    o << "    float4 foliage_wind;\n    float4 foliage_push;\n};\n\n";
    o << "struct VSIn {\n";
    o << "    float3 a_pos : POSITION;\n    float4 a_color : COLOR;\n";
    o << "    float2 a_uv : TEXCOORD0;\n    float3 a_normal : NORMAL;\n";
    o << "    float3 a_tangent : TANGENT;\n};\n\n";
    o << "struct VSOut {\n";
    o << "    float4 pos : SV_Position;\n    float2 v_uv : TEXCOORD0;\n";
    o << "    float3 v_normal : NORMAL;\n    float3 v_world_pos : TEXCOORD1;\n";
    o << "    float3 v_tangent : TANGENT;\n    float3 v_bitangent : BINORMAL;\n";
    o << "    float4 v_color : COLOR;\n};\n\n";
    o << "VSOut VSMain(VSIn i) {\n    VSOut o;\n";
    o << "    o.v_world_pos = i.a_pos;\n    o.v_normal = i.a_normal;\n";
    o << "    o.v_tangent = i.a_tangent;\n";
    o << "    o.v_bitangent = cross(i.a_normal, i.a_tangent);\n";
    o << "    o.v_uv = i.a_uv;\n    o.v_color = i.a_color;\n";
    o << "    o.pos = mul(vp, float4(i.a_pos, 1.0));\n";
    o << "    return o;\n}\n";
    return o.str();
}

}  // namespace

const char* ShaderTargetName(ShaderTarget target) {
    switch (target) {
        case ShaderTarget::HLSL: return "HLSL";
        case ShaderTarget::GLSL_VULKAN: return "GLSL-Vulkan";
        case ShaderTarget::GLSL_ES: return "GLSL-ES";
        case ShaderTarget::GLSL: default: return "GLSL";
    }
}

ShaderCodegenResult GenerateShader(const ShaderGraphAsset& graph, ShaderTarget target) {
    ShaderCodegenResult res;

    std::string verr;
    if (!ValidateShaderGraph(graph, verr)) {
        res.errors.push_back(verr);
        return res;
    }

    const bool hlsl = IsHLSL(target);
    std::ostringstream o;

    // ── 片元/像素着色器头 ────────────────────────────────────────────────
    // 收集 Texture Sample 节点用到的贴图 uniform（先扫描，头部声明）。
    std::unordered_map<int, std::string> tex_uniforms;  // node_id -> uniform 名
    std::vector<std::string> tex_order;                 // 声明顺序（决定 HLSL register / Vulkan binding）
    int tex_unit = 0;
    for (const auto& n : graph.nodes) {
        if (n.name == "Texture Sample" || n.name == "Normal Map") {
            std::string uname = "u_tex" + std::to_string(tex_unit++);
            tex_uniforms[n.id] = uname;
            tex_order.push_back(uname);
        }
    }

    if (hlsl) {
        o << "// Auto-generated by DSEngine Shader Graph (fragment, HLSL)\n";
        o << "cbuffer PerDraw : register(b0) {\n    float u_time;\n};\n\n";
        int slot = 0;
        for (const auto& uname : tex_order) {
            o << "Texture2D " << uname << " : register(t" << slot << ");\n";
            o << "SamplerState " << uname << "_s : register(s" << slot << ");\n";
            ++slot;
        }
        if (!tex_order.empty()) o << "\n";
        o << "struct PSIn {\n";
        o << "    float4 pos : SV_Position;\n    float2 v_uv : TEXCOORD0;\n";
        o << "    float3 v_normal : NORMAL;\n    float3 v_world_pos : TEXCOORD1;\n";
        o << "    float3 v_tangent : TANGENT;\n    float3 v_bitangent : BINORMAL;\n";
        o << "    float4 v_color : COLOR;\n};\n\n";
        o << "float4 PSMain(PSIn i) : SV_Target {\n";
        // 局部别名：让节点发射逻辑对两个后端统一使用 v_* 名字。
        o << "    float2 v_uv = i.v_uv;\n    float3 v_normal = i.v_normal;\n";
        o << "    float3 v_world_pos = i.v_world_pos;\n    float3 v_tangent = i.v_tangent;\n";
        o << "    float3 v_bitangent = i.v_bitangent;\n    float4 v_color = i.v_color;\n";
        o << "    float4 FragColor = float4(0.0, 0.0, 0.0, 1.0);\n";
    } else {
        const bool vulkan = IsVulkan(target);
        const bool es = IsES(target);
        o << "// Auto-generated by DSEngine Shader Graph (fragment, " << ShaderTargetName(target) << ")\n";
        o << GlslVersionLine(target);
        if (es) o << "precision highp float;\n";
        o << "\n";
        const char* varyings[] = {"vec2 v_uv", "vec3 v_normal", "vec3 v_world_pos",
                                  "vec3 v_tangent", "vec3 v_bitangent", "vec4 v_color"};
        for (int i = 0; i < 6; ++i) {
            if (vulkan) o << "layout(location = " << i << ") ";
            o << "in " << varyings[i] << ";\n";
        }
        o << "\n";
        // Vulkan 片元输出必须显式 location；u_time 必须包进 UBO（不能是自由 uniform）。
        o << (vulkan ? "layout(location = 0) out vec4 FragColor;\n\n" : "out vec4 FragColor;\n\n");
        if (vulkan) o << "layout(std140, binding = 0) uniform PerDraw { float u_time; };\n";
        else        o << "uniform float u_time;\n";
        int binding = 1;  // binding 0 归 PerDraw UBO
        for (const auto& uname : tex_order) {
            if (vulkan) o << "layout(binding = " << binding++ << ") ";
            o << "uniform sampler2D " << uname << ";\n";
        }
        o << "\nvoid main() {\n";
    }

    // ── 拓扑排序（Kahn）────────────────────────────────────────────────
    std::unordered_map<int, int> pin_to_node;
    for (size_t i = 0; i < graph.nodes.size(); ++i) {
        for (const auto& p : graph.nodes[i].inputs) pin_to_node[p.id] = static_cast<int>(i);
        for (const auto& p : graph.nodes[i].outputs) pin_to_node[p.id] = static_cast<int>(i);
    }
    std::unordered_map<int, std::unordered_set<int>> deps;
    std::unordered_map<int, int> input_source;  // to_pin -> from_pin
    for (const auto& l : graph.links) {
        input_source[l.to_pin] = l.from_pin;
        auto it_to = pin_to_node.find(l.to_pin);
        auto it_from = pin_to_node.find(l.from_pin);
        if (it_to != pin_to_node.end() && it_from != pin_to_node.end()) {
            deps[it_to->second].insert(it_from->second);
        }
    }
    std::unordered_map<int, int> in_degree;
    for (size_t i = 0; i < graph.nodes.size(); ++i) in_degree[static_cast<int>(i)] = 0;
    for (auto& [idx, dep_set] : deps) in_degree[idx] = static_cast<int>(dep_set.size());
    std::queue<int> q;
    for (auto& [idx, deg] : in_degree)
        if (deg == 0) q.push(idx);
    std::vector<int> topo;
    while (!q.empty()) {
        int cur = q.front();
        q.pop();
        topo.push_back(cur);
        for (size_t i = 0; i < graph.nodes.size(); ++i) {
            auto it = deps.find(static_cast<int>(i));
            if (it != deps.end() && it->second.count(cur)) {
                it->second.erase(cur);
                if (--in_degree[static_cast<int>(i)] == 0) q.push(static_cast<int>(i));
            }
        }
    }
    if (topo.size() != graph.nodes.size()) {
        res.errors.push_back("shader graph contains a cycle");
        return res;
    }

    std::unordered_map<int, std::string> pin_vars;  // pin_id -> 变量表达式

    // 取输入表达式：优先取上游连线，否则用引脚默认值（标量）。
    auto in_expr = [&](const NodeDesc& n, int idx, const std::string& fallback) -> std::string {
        if (idx < 0 || idx >= static_cast<int>(n.inputs.size())) return fallback;
        auto s = input_source.find(n.inputs[idx].id);
        if (s != input_source.end()) {
            auto v = pin_vars.find(s->second);
            if (v != pin_vars.end()) return v->second;
        }
        return fallback;
    };
    auto in_default = [&](const NodeDesc& n, int idx) -> std::string {
        if (idx < 0 || idx >= static_cast<int>(n.inputs.size())) return "0.0";
        return F(n.inputs[idx].default_value[0]);
    };

    for (int ni : topo) {
        const NodeDesc& n = graph.nodes[ni];
        const std::string p = "n" + std::to_string(n.id) + "_";
        auto set_out = [&](int idx, const std::string& expr) {
            if (idx < static_cast<int>(n.outputs.size())) pin_vars[n.outputs[idx].id] = expr;
        };
        const std::string& name = n.name;

        if (name == "Float") {
            std::string v = p + "val";
            o << "    float " << v << " = " << F(n.outputs.empty() ? 0.f : n.outputs[0].default_value[0]) << ";\n";
            set_out(0, v);
        } else if (name == "Vec2") {
            std::string v = p + "val";
            o << "    " << VecT(target, 2) << " " << v << " = " << VecT(target, 2) << "("
              << F(n.outputs[0].default_value[0]) << ", " << F(n.outputs[0].default_value[1]) << ");\n";
            set_out(0, v);
        } else if (name == "Vec3") {
            std::string v = p + "val";
            o << "    " << VecT(target, 3) << " " << v << " = " << VecT(target, 3) << "("
              << F(n.outputs[0].default_value[0]) << ", " << F(n.outputs[0].default_value[1]) << ", "
              << F(n.outputs[0].default_value[2]) << ");\n";
            set_out(0, v);
        } else if (name == "Color") {
            std::string v = p + "col";
            o << "    " << VecT(target, 4) << " " << v << " = " << VecT(target, 4) << "("
              << F(n.outputs[0].default_value[0]) << ", " << F(n.outputs[0].default_value[1]) << ", "
              << F(n.outputs[0].default_value[2]) << ", " << F(n.outputs[0].default_value[3]) << ");\n";
            set_out(0, v);
        } else if (name == "UV") {
            set_out(0, "v_uv");
        } else if (name == "Time") {
            set_out(0, "u_time");
            if (n.outputs.size() > 1) {
                o << "    float " << p << "sin = " << Fn(target, "sin") << "(u_time);\n";
                set_out(1, p + "sin");
            }
            if (n.outputs.size() > 2) {
                o << "    float " << p << "cos = " << Fn(target, "cos") << "(u_time);\n";
                set_out(2, p + "cos");
            }
        } else if (name == "Texture Sample") {
            std::string uname = tex_uniforms.count(n.id) ? tex_uniforms[n.id] : "u_tex0";
            std::string uv = in_expr(n, 0, "v_uv");
            std::string v = p + "rgba";
            o << "    " << VecT(target, 4) << " " << v << " = " << TexSample(target, uname, uv) << ";\n";
            set_out(0, v);
            set_out(1, v + ".r");
            set_out(2, v + ".g");
            set_out(3, v + ".b");
            set_out(4, v + ".a");
        } else if (name == "Add" || name == "Multiply" || name == "Subtract" || name == "Divide") {
            std::string a = in_expr(n, 0, in_default(n, 0));
            std::string b = in_expr(n, 1, in_default(n, 1));
            const char* op = name == "Multiply" ? " * " : name == "Subtract" ? " - " : name == "Divide" ? " / " : " + ";
            std::string v = p + "out";
            o << "    float " << v << " = " << a << op << b << ";\n";
            set_out(0, v);
        } else if (name == "Lerp") {
            std::string a = in_expr(n, 0, "0.0"), b = in_expr(n, 1, "1.0"), t = in_expr(n, 2, "0.5");
            std::string v = p + "out";
            o << "    float " << v << " = " << Fn(target, "mix") << "(" << a << ", " << b << ", " << t << ");\n";
            set_out(0, v);
        } else if (name == "Power") {
            std::string a = in_expr(n, 0, in_default(n, 0)), b = in_expr(n, 1, in_default(n, 1));
            std::string v = p + "out";
            o << "    float " << v << " = pow(" << a << ", " << b << ");\n";
            set_out(0, v);
        } else if (name == "Abs" || name == "Saturate" || name == "Sin" || name == "Cos" ||
                   name == "Floor" || name == "Fract" || name == "Negate" || name == "One Minus" ||
                   name == "Normalize" || name == "Length") {
            std::string in_e = in_expr(n, 0, in_default(n, 0));
            std::string fn;
            if (name == "Abs") fn = "abs(" + in_e + ")";
            else if (name == "Saturate") fn = "clamp(" + in_e + ", 0.0, 1.0)";
            else if (name == "Sin") fn = Fn(target, "sin") + "(" + in_e + ")";
            else if (name == "Cos") fn = Fn(target, "cos") + "(" + in_e + ")";
            else if (name == "Floor") fn = "floor(" + in_e + ")";
            else if (name == "Fract") fn = Fn(target, "fract") + "(" + in_e + ")";
            else if (name == "Negate") fn = "-(" + in_e + ")";
            else if (name == "One Minus") fn = "(1.0 - " + in_e + ")";
            else if (name == "Normalize") fn = "normalize(" + in_e + ")";
            else fn = "length(" + in_e + ")";
            bool is_vec = (name == "Normalize");
            std::string v = p + "out";
            o << "    " << (is_vec ? VecT(target, 3) : std::string("float")) << " " << v << " = " << fn << ";\n";
            set_out(0, v);
        } else if (name == "Clamp") {
            std::string in_e = in_expr(n, 0, "0.0");
            std::string mn = in_expr(n, 1, in_default(n, 1)), mx = in_expr(n, 2, in_default(n, 2));
            std::string v = p + "out";
            o << "    float " << v << " = clamp(" << in_e << ", " << mn << ", " << mx << ");\n";
            set_out(0, v);
        } else if (name == "Step") {
            std::string edge = in_expr(n, 0, in_default(n, 0)), in_e = in_expr(n, 1, "0.0");
            std::string v = p + "out";
            o << "    float " << v << " = step(" << edge << ", " << in_e << ");\n";
            set_out(0, v);
        } else if (name == "Smoothstep") {
            std::string e0 = in_expr(n, 0, in_default(n, 0)), e1 = in_expr(n, 1, in_default(n, 1)), in_e = in_expr(n, 2, "0.5");
            std::string v = p + "out";
            o << "    float " << v << " = smoothstep(" << e0 << ", " << e1 << ", " << in_e << ");\n";
            set_out(0, v);
        } else if (name == "Min" || name == "Max" || name == "Dot") {
            std::string a = in_expr(n, 0, "0.0"), b = in_expr(n, 1, "0.0");
            std::string fn = name == "Min" ? "min" : name == "Max" ? "max" : "dot";
            std::string v = p + "out";
            o << "    float " << v << " = " << fn << "(" << a << ", " << b << ");\n";
            set_out(0, v);
        } else if (name == "Cross") {
            std::string a = in_expr(n, 0, VecT(target, 3) + "(0.0)"), b = in_expr(n, 1, VecT(target, 3) + "(0.0)");
            std::string v = p + "out";
            o << "    " << VecT(target, 3) << " " << v << " = cross(" << a << ", " << b << ");\n";
            set_out(0, v);
        } else if (name == "Make Vec3") {
            std::string v = p + "out";
            o << "    " << VecT(target, 3) << " " << v << " = " << VecT(target, 3) << "("
              << in_expr(n, 0, "0.0") << ", " << in_expr(n, 1, "0.0") << ", " << in_expr(n, 2, "0.0") << ");\n";
            set_out(0, v);
        } else if (name == "Split") {
            std::string in_e = in_expr(n, 0, VecT(target, 4) + "(0.0)");
            std::string v = p + "v";
            o << "    " << VecT(target, 4) << " " << v << " = " << in_e << ";\n";
            set_out(0, v + ".r");
            set_out(1, v + ".g");
            set_out(2, v + ".b");
            set_out(3, v + ".a");
        } else if (name == "Combine") {
            std::string r = in_expr(n, 0, "0.0"), g = in_expr(n, 1, "0.0"), b = in_expr(n, 2, "0.0"), a = in_expr(n, 3, "1.0");
            std::string v = p + "rgba";
            o << "    " << VecT(target, 4) << " " << v << " = " << VecT(target, 4) << "(" << r << ", " << g << ", " << b << ", " << a << ");\n";
            set_out(0, v);
            set_out(1, v + ".rgb");
        } else if (name == "Tiling Offset") {
            std::string uv = in_expr(n, 0, "v_uv");
            std::string v = p + "out";
            o << "    " << VecT(target, 2) << " " << v << " = " << uv << " * " << VecT(target, 2) << "("
              << F(n.inputs[1].default_value[0]) << ", " << F(n.inputs[1].default_value[1]) << ") + " << VecT(target, 2) << "("
              << F(n.inputs[2].default_value[0]) << ", " << F(n.inputs[2].default_value[1]) << ");\n";
            set_out(0, v);
        } else if (name == "Fresnel") {
            std::string power = in_expr(n, 0, in_default(n, 0));
            std::string v = p + "out";
            o << "    float " << v << " = pow(1.0 - max(dot(normalize(v_normal), normalize(-v_world_pos)), 0.0), " << power << ");\n";
            set_out(0, v);
        } else if (name == "Normal Map") {
            std::string tex = tex_uniforms.count(n.id) ? tex_uniforms[n.id] : "u_tex0";
            std::string uv = in_expr(n, 1, "v_uv");
            std::string strength = in_expr(n, 2, in_default(n, 2));
            std::string v = p + "out";
            o << "    " << VecT(target, 3) << " " << p << "raw = " << TexSample(target, tex, uv) << ".rgb * 2.0 - 1.0;\n";
            o << "    " << p << "raw.xy *= " << strength << ";\n";
            o << "    " << Mat3T(target) << " " << p << "TBN = " << Mat3T(target)
              << "(normalize(v_tangent), normalize(v_bitangent), normalize(v_normal));\n";
            o << "    " << VecT(target, 3) << " " << v << " = normalize(" << MulMV(target, p + "TBN", p + "raw") << ");\n";
            set_out(0, v);
        } else if (name == "World Position") {
            set_out(0, "v_world_pos");
        } else if (name == "World Normal") {
            std::string v = p + "wn";
            o << "    " << VecT(target, 3) << " " << v << " = normalize(v_normal);\n";
            set_out(0, v);
        } else if (name == "View Direction") {
            std::string v = p + "vd";
            o << "    " << VecT(target, 3) << " " << v << " = normalize(-v_world_pos);\n";
            set_out(0, v);
        } else if (name == "Vertex Color") {
            set_out(0, "v_color");
        } else if (name == "Camera Distance") {
            std::string v = p + "cd";
            o << "    float " << v << " = length(v_world_pos);\n";
            set_out(0, v);
        } else if (name == "Swizzle XY") {
            std::string in_e = in_expr(n, 0, VecT(target, 3) + "(0.0)");
            std::string v = p + "xy";
            o << "    " << VecT(target, 2) << " " << v << " = " << in_e << ".xy;\n";
            set_out(0, v);
        } else if (name == "Rotate UV") {
            std::string uv = in_expr(n, 0, "v_uv");
            std::string angle = in_expr(n, 2, "0.0");
            o << "    " << VecT(target, 2) << " " << p << "c = " << VecT(target, 2) << "("
              << F(n.inputs[1].default_value[0]) << ", " << F(n.inputs[1].default_value[1]) << ");\n";
            o << "    float " << p << "ca = cos(" << angle << "), " << p << "sa = sin(" << angle << ");\n";
            std::string rot = Mat2T(target) + "(" + p + "ca, -" + p + "sa, " + p + "sa, " + p + "ca)";
            std::string v = p + "out";
            o << "    " << VecT(target, 2) << " " << v << " = " << p << "c + "
              << MulMV(target, rot, "(" + uv + " - " + p + "c)") << ";\n";
            set_out(0, v);
        } else if (name == "Polar UV") {
            std::string uv = in_expr(n, 0, "v_uv");
            std::string v = p + "out";
            o << "    " << VecT(target, 2) << " " << p << "d = " << uv << " - " << VecT(target, 2) << "("
              << F(n.inputs[1].default_value[0]) << ", " << F(n.inputs[1].default_value[1]) << ");\n";
            o << "    " << VecT(target, 2) << " " << v << " = " << VecT(target, 2) << "("
              << Atan2(target, p + "d.y", p + "d.x") << " / 6.2832 + 0.5, length(" << p << "d));\n";
            set_out(0, v);
        } else if (name == "Checkerboard") {
            std::string uv = in_expr(n, 0, "v_uv"), scale = in_expr(n, 1, in_default(n, 1));
            std::string v = p + "out";
            o << "    float " << v << " = " << Fn(target, "mod") << "(floor(" << uv << ".x * " << scale
              << ") + floor(" << uv << ".y * " << scale << "), 2.0);\n";
            set_out(0, v);
        } else if (name == "Noise Perlin" || name == "Gradient Noise") {
            std::string uv = in_expr(n, 0, "v_uv"), scale = in_expr(n, 1, in_default(n, 1));
            std::string v = p + "out";
            o << "    " << VecT(target, 2) << " " << p << "np = " << uv << " * " << scale << ";\n";
            o << "    float " << v << " = " << Fn(target, "fract") << "(sin(dot(" << p << "np, "
              << VecT(target, 2) << "(12.9898, 78.233))) * 43758.5453);\n";
            set_out(0, v);
        } else if (name == "Noise Voronoi") {
            std::string uv = in_expr(n, 0, "v_uv"), scale = in_expr(n, 1, in_default(n, 1));
            std::string v = p + "dist";
            o << "    " << VecT(target, 2) << " " << p << "vp = " << uv << " * " << scale << ";\n";
            o << "    " << VecT(target, 2) << " " << p << "vi = floor(" << p << "vp);\n";
            o << "    " << VecT(target, 2) << " " << p << "vf = " << Fn(target, "fract") << "(" << p << "vp);\n";
            o << "    float " << v << " = 1.0;\n";
            o << "    for (int " << p << "y = -1; " << p << "y <= 1; ++" << p << "y)\n";
            o << "    for (int " << p << "x = -1; " << p << "x <= 1; ++" << p << "x) {\n";
            o << "        " << VecT(target, 2) << " " << p << "nb = " << VecT(target, 2) << "(float(" << p << "x), float(" << p << "y));\n";
            o << "        " << VecT(target, 2) << " " << p << "pt = " << p << "nb + " << Fn(target, "fract")
              << "(sin(dot(" << p << "vi + " << p << "nb, " << VecT(target, 2) << "(127.1, 311.7))) * 43758.5453) - " << p << "vf;\n";
            o << "        " << v << " = min(" << v << ", dot(" << p << "pt, " << p << "pt));\n";
            o << "    }\n";
            o << "    " << v << " = sqrt(" << v << ");\n";
            set_out(0, v);
        } else if (name == "Remap") {
            std::string in_e = in_expr(n, 0, "0.0");
            std::string imn = in_expr(n, 1, in_default(n, 1)), imx = in_expr(n, 2, in_default(n, 2));
            std::string omn = in_expr(n, 3, in_default(n, 3)), omx = in_expr(n, 4, in_default(n, 4));
            std::string v = p + "out";
            o << "    float " << v << " = " << omn << " + (" << in_e << " - " << imn << ") / ("
              << imx << " - " << imn << ") * (" << omx << " - " << omn << ");\n";
            set_out(0, v);
        } else if (name == "Rim Light") {
            std::string power = in_expr(n, 0, in_default(n, 0));
            std::string v = p + "out";
            o << "    float " << p << "ndv = 1.0 - max(dot(normalize(v_normal), normalize(-v_world_pos)), 0.0);\n";
            o << "    " << VecT(target, 3) << " " << v << " = " << VecT(target, 3) << "(pow(" << p << "ndv, " << power << "));\n";
            set_out(0, v);
        } else if (name == "Dissolve") {
            std::string noise = in_expr(n, 0, "0.5");
            std::string thresh = in_expr(n, 1, in_default(n, 1));
            std::string edge_w = in_expr(n, 2, in_default(n, 2));
            std::string alpha = p + "alpha", edge = p + "edge";
            o << "    float " << alpha << " = step(" << thresh << ", " << noise << ");\n";
            o << "    float " << edge << " = smoothstep(" << thresh << " - " << edge_w << ", " << thresh << ", " << noise << ") - " << alpha << ";\n";
            set_out(0, alpha);
            set_out(1, edge);
        } else if (name == "Triplanar") {
            std::string v = p + "out";
            o << "    " << VecT(target, 3) << " " << p << "bl = pow(abs(normalize(v_normal)), " << VecT(target, 3) << "(1.0));\n";
            o << "    " << p << "bl /= (" << p << "bl.x + " << p << "bl.y + " << p << "bl.z);\n";
            o << "    " << VecT(target, 4) << " " << v << " = " << VecT(target, 4) << "(" << p << "bl.x + " << p << "bl.y + " << p << "bl.z);\n";
            set_out(0, v);
        } else if (name == "Parallax Mapping") {
            std::string uv = in_expr(n, 0, "v_uv");
            std::string h = in_expr(n, 1, "0.0");
            std::string scale = in_expr(n, 2, in_default(n, 2));
            std::string v = p + "out";
            std::string tbn = Mat3T(target) + "(v_tangent, v_bitangent, v_normal)";
            o << "    " << VecT(target, 3) << " " << p << "vts = normalize(" << MulMV(target, tbn, "normalize(-v_world_pos)") << ");\n";
            o << "    " << VecT(target, 2) << " " << v << " = " << uv << " + " << p << "vts.xy * (" << h << " * " << scale << ");\n";
            set_out(0, v);
        } else if (name == "Screen Position") {
            std::string v = p + "sp";
            if (hlsl) {
                res.warnings.push_back("node 'Screen Position' on HLSL lacks a screen-size uniform; "
                                       "approximating with v_uv");
                o << "    " << VecT(target, 2) << " " << v << " = v_uv;\n";
            } else {
                o << "    vec2 " << v << " = gl_FragCoord.xy / vec2(textureSize(u_tex0, 0));\n";
            }
            set_out(0, v);
        } else if (name == "PBR Output") {
            std::string base = in_expr(n, 0, VecT(target, 4) + "(0.8, 0.8, 0.8, 1.0)");
            std::string alpha = in_expr(n, 6, "1.0");
            o << "    " << VecT(target, 4) << " " << p << "base = " << base << ";\n";
            o << "    FragColor = " << VecT(target, 4) << "(" << p << "base.rgb, " << alpha << ");\n";
        } else {
            res.warnings.push_back("node '" + name + "' has no codegen for target " +
                                   std::string(ShaderTargetName(target)) + "; emitting safe default");
            if (!n.outputs.empty()) {
                std::string v = p + "unsupported";
                o << "    float " << v << " = 0.0;\n";
                set_out(0, v);
            }
        }
    }

    o << (hlsl ? "    return FragColor;\n}\n" : "}\n");

    res.fragment = o.str();
    res.vertex = hlsl ? VertexHLSL() : VertexGLSLFamily(target);
    res.ok = true;
    return res;
}

}  // namespace shadergraph
}  // namespace dse
