// <auto-generated>
//   来源：tools/codegen/binding_defs.json — 勿手动修改
//   统一复制层序列化编解码 — 消除双序列化路径漂移（A1 架构优化）
// </auto-generated>
#ifndef DSE_NET_REPLICATION_REPL_CODEC_GEN_H
#define DSE_NET_REPLICATION_REPL_CODEC_GEN_H

#include "engine/net/serialize/byte_stream.h"
#include "engine/ecs/transform.h"
#include "engine/ecs/components_3d.h"
#include "engine/ecs/components_3d.h"
#include "engine/ecs/components_3d.h"
#include "engine/ecs/components_3d.h"
#include "engine/ecs/components_3d.h"
#include "engine/ecs/components_3d.h"
#include "engine/ecs/components_3d_tree.h"
#include "engine/ecs/components_3d_terrain_tile.h"
#include "engine/ecs/components_3d_navmesh.h"
#include "engine/ecs/components_3d_navmesh.h"
#include "engine/ecs/components_3d_render.h"
#include "engine/ecs/components_3d.h"
#include <cstdint>

namespace dse::net::repl {

// ═══════════════════════════════════════════════════════════════════════════════
// TransformComponent (prefix: transform)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class transform_DeltaFlags : uint32_t {
    None = 0,
    f_position = (1u << 0),
    f_rotation = (1u << 1),
    f_scale = (1u << 2),
    All = 0x7u
};

inline transform_DeltaFlags operator|(transform_DeltaFlags a, transform_DeltaFlags b) {
    return static_cast<transform_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(transform_DeltaFlags flags, transform_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_transform(ByteWriter& w, const TransformComponent& c) {
    w.WriteF32(c.position.x); w.WriteF32(c.position.y); w.WriteF32(c.position.z);
    w.WriteF32(c.rotation.x); w.WriteF32(c.rotation.y); w.WriteF32(c.rotation.z); w.WriteF32(c.rotation.w);
    w.WriteF32(c.scale.x); w.WriteF32(c.scale.y); w.WriteF32(c.scale.z);
}

/// Full snapshot read.
inline void ReadSnapshot_transform(ByteReader& r, TransformComponent& c) {
    c.position.x = r.ReadF32(); c.position.y = r.ReadF32(); c.position.z = r.ReadF32();
    c.rotation.x = r.ReadF32(); c.rotation.y = r.ReadF32(); c.rotation.z = r.ReadF32(); c.rotation.w = r.ReadF32();
    c.scale.x = r.ReadF32(); c.scale.y = r.ReadF32(); c.scale.z = r.ReadF32();
    c.dirty = true;
}

/// Compute delta between current and baseline.
inline transform_DeltaFlags ComputeDelta_transform(
        const TransformComponent& cur,
        const TransformComponent& base) {
    transform_DeltaFlags flags = transform_DeltaFlags::None;
    if (cur.position.x != base.position.x || cur.position.y != base.position.y || cur.position.z != base.position.z) flags = flags | transform_DeltaFlags::f_position;
    if (cur.rotation.x != base.rotation.x || cur.rotation.y != base.rotation.y || cur.rotation.z != base.rotation.z || cur.rotation.w != base.rotation.w) flags = flags | transform_DeltaFlags::f_rotation;
    if (cur.scale.x != base.scale.x || cur.scale.y != base.scale.y || cur.scale.z != base.scale.z) flags = flags | transform_DeltaFlags::f_scale;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_transform(ByteWriter& w, const TransformComponent& c, transform_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, transform_DeltaFlags::f_position)) { w.WriteF32(c.position.x); w.WriteF32(c.position.y); w.WriteF32(c.position.z); }
    if (HasFlag(flags, transform_DeltaFlags::f_rotation)) { w.WriteF32(c.rotation.x); w.WriteF32(c.rotation.y); w.WriteF32(c.rotation.z); w.WriteF32(c.rotation.w); }
    if (HasFlag(flags, transform_DeltaFlags::f_scale)) { w.WriteF32(c.scale.x); w.WriteF32(c.scale.y); w.WriteF32(c.scale.z); }
}

/// Read delta and apply to component.
inline void ReadDelta_transform(ByteReader& r, TransformComponent& c) {
    auto flags = static_cast<transform_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, transform_DeltaFlags::f_position)) { c.position.x = r.ReadF32(); c.position.y = r.ReadF32(); c.position.z = r.ReadF32(); }
    if (HasFlag(flags, transform_DeltaFlags::f_rotation)) { c.rotation.x = r.ReadF32(); c.rotation.y = r.ReadF32(); c.rotation.z = r.ReadF32(); c.rotation.w = r.ReadF32(); }
    if (HasFlag(flags, transform_DeltaFlags::f_scale)) { c.scale.x = r.ReadF32(); c.scale.y = r.ReadF32(); c.scale.z = r.ReadF32(); }
    if (static_cast<uint32_t>(flags) != 0) c.dirty = true;
}
// ═══════════════════════════════════════════════════════════════════════════════
// Camera3DComponent (prefix: camera3d)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class camera3d_DeltaFlags : uint32_t {
    None = 0,
    f_fov = (1u << 0),
    f_near_clip = (1u << 1),
    f_far_clip = (1u << 2),
    f_enabled = (1u << 3),
    f_priority = (1u << 4),
    All = 0x1fu
};

inline camera3d_DeltaFlags operator|(camera3d_DeltaFlags a, camera3d_DeltaFlags b) {
    return static_cast<camera3d_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(camera3d_DeltaFlags flags, camera3d_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_camera3d(ByteWriter& w, const dse::Camera3DComponent& c) {
    w.WriteF32(c.fov);
    w.WriteF32(c.near_clip);
    w.WriteF32(c.far_clip);
    w.WriteU8(c.enabled ? 1 : 0);
    w.WriteU32(static_cast<uint32_t>(c.priority));
}

/// Full snapshot read.
inline void ReadSnapshot_camera3d(ByteReader& r, dse::Camera3DComponent& c) {
    c.fov = r.ReadF32();
    c.near_clip = r.ReadF32();
    c.far_clip = r.ReadF32();
    c.enabled = r.ReadU8() != 0;
    c.priority = static_cast<int>(r.ReadU32());
}

/// Compute delta between current and baseline.
inline camera3d_DeltaFlags ComputeDelta_camera3d(
        const dse::Camera3DComponent& cur,
        const dse::Camera3DComponent& base) {
    camera3d_DeltaFlags flags = camera3d_DeltaFlags::None;
    if (cur.fov != base.fov) flags = flags | camera3d_DeltaFlags::f_fov;
    if (cur.near_clip != base.near_clip) flags = flags | camera3d_DeltaFlags::f_near_clip;
    if (cur.far_clip != base.far_clip) flags = flags | camera3d_DeltaFlags::f_far_clip;
    if (cur.enabled != base.enabled) flags = flags | camera3d_DeltaFlags::f_enabled;
    if (cur.priority != base.priority) flags = flags | camera3d_DeltaFlags::f_priority;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_camera3d(ByteWriter& w, const dse::Camera3DComponent& c, camera3d_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, camera3d_DeltaFlags::f_fov)) { w.WriteF32(c.fov); }
    if (HasFlag(flags, camera3d_DeltaFlags::f_near_clip)) { w.WriteF32(c.near_clip); }
    if (HasFlag(flags, camera3d_DeltaFlags::f_far_clip)) { w.WriteF32(c.far_clip); }
    if (HasFlag(flags, camera3d_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
    if (HasFlag(flags, camera3d_DeltaFlags::f_priority)) { w.WriteU32(static_cast<uint32_t>(c.priority)); }
}

/// Read delta and apply to component.
inline void ReadDelta_camera3d(ByteReader& r, dse::Camera3DComponent& c) {
    auto flags = static_cast<camera3d_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, camera3d_DeltaFlags::f_fov)) { c.fov = r.ReadF32(); }
    if (HasFlag(flags, camera3d_DeltaFlags::f_near_clip)) { c.near_clip = r.ReadF32(); }
    if (HasFlag(flags, camera3d_DeltaFlags::f_far_clip)) { c.far_clip = r.ReadF32(); }
    if (HasFlag(flags, camera3d_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, camera3d_DeltaFlags::f_priority)) { c.priority = static_cast<int>(r.ReadU32()); }
}
// ═══════════════════════════════════════════════════════════════════════════════
// MeshRendererComponent (prefix: mesh_renderer)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class mesh_renderer_DeltaFlags : uint32_t {
    None = 0,
    f_color = (1u << 0),
    f_visible = (1u << 1),
    f_metallic = (1u << 2),
    f_roughness = (1u << 3),
    f_emissive = (1u << 4),
    f_receive_shadow = (1u << 5),
    All = 0x3fu
};

inline mesh_renderer_DeltaFlags operator|(mesh_renderer_DeltaFlags a, mesh_renderer_DeltaFlags b) {
    return static_cast<mesh_renderer_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(mesh_renderer_DeltaFlags flags, mesh_renderer_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_mesh_renderer(ByteWriter& w, const dse::MeshRendererComponent& c) {
    w.WriteF32(c.color.x); w.WriteF32(c.color.y); w.WriteF32(c.color.z); w.WriteF32(c.color.w);
    w.WriteU8(c.visible ? 1 : 0);
    w.WriteF32(c.metallic);
    w.WriteF32(c.roughness);
    w.WriteF32(c.emissive.x); w.WriteF32(c.emissive.y); w.WriteF32(c.emissive.z);
    w.WriteU8(c.receive_shadow ? 1 : 0);
}

/// Full snapshot read.
inline void ReadSnapshot_mesh_renderer(ByteReader& r, dse::MeshRendererComponent& c) {
    c.color.x = r.ReadF32(); c.color.y = r.ReadF32(); c.color.z = r.ReadF32(); c.color.w = r.ReadF32();
    c.visible = r.ReadU8() != 0;
    c.metallic = r.ReadF32();
    c.roughness = r.ReadF32();
    c.emissive.x = r.ReadF32(); c.emissive.y = r.ReadF32(); c.emissive.z = r.ReadF32();
    c.receive_shadow = r.ReadU8() != 0;
}

/// Compute delta between current and baseline.
inline mesh_renderer_DeltaFlags ComputeDelta_mesh_renderer(
        const dse::MeshRendererComponent& cur,
        const dse::MeshRendererComponent& base) {
    mesh_renderer_DeltaFlags flags = mesh_renderer_DeltaFlags::None;
    if (cur.color.x != base.color.x || cur.color.y != base.color.y || cur.color.z != base.color.z || cur.color.w != base.color.w) flags = flags | mesh_renderer_DeltaFlags::f_color;
    if (cur.visible != base.visible) flags = flags | mesh_renderer_DeltaFlags::f_visible;
    if (cur.metallic != base.metallic) flags = flags | mesh_renderer_DeltaFlags::f_metallic;
    if (cur.roughness != base.roughness) flags = flags | mesh_renderer_DeltaFlags::f_roughness;
    if (cur.emissive.x != base.emissive.x || cur.emissive.y != base.emissive.y || cur.emissive.z != base.emissive.z) flags = flags | mesh_renderer_DeltaFlags::f_emissive;
    if (cur.receive_shadow != base.receive_shadow) flags = flags | mesh_renderer_DeltaFlags::f_receive_shadow;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_mesh_renderer(ByteWriter& w, const dse::MeshRendererComponent& c, mesh_renderer_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_color)) { w.WriteF32(c.color.x); w.WriteF32(c.color.y); w.WriteF32(c.color.z); w.WriteF32(c.color.w); }
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_visible)) { w.WriteU8(c.visible ? 1 : 0); }
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_metallic)) { w.WriteF32(c.metallic); }
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_roughness)) { w.WriteF32(c.roughness); }
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_emissive)) { w.WriteF32(c.emissive.x); w.WriteF32(c.emissive.y); w.WriteF32(c.emissive.z); }
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_receive_shadow)) { w.WriteU8(c.receive_shadow ? 1 : 0); }
}

/// Read delta and apply to component.
inline void ReadDelta_mesh_renderer(ByteReader& r, dse::MeshRendererComponent& c) {
    auto flags = static_cast<mesh_renderer_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_color)) { c.color.x = r.ReadF32(); c.color.y = r.ReadF32(); c.color.z = r.ReadF32(); c.color.w = r.ReadF32(); }
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_visible)) { c.visible = r.ReadU8() != 0; }
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_metallic)) { c.metallic = r.ReadF32(); }
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_roughness)) { c.roughness = r.ReadF32(); }
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_emissive)) { c.emissive.x = r.ReadF32(); c.emissive.y = r.ReadF32(); c.emissive.z = r.ReadF32(); }
    if (HasFlag(flags, mesh_renderer_DeltaFlags::f_receive_shadow)) { c.receive_shadow = r.ReadU8() != 0; }
}
// ═══════════════════════════════════════════════════════════════════════════════
// DirectionalLight3DComponent (prefix: dir_light)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class dir_light_DeltaFlags : uint32_t {
    None = 0,
    f_direction = (1u << 0),
    f_color = (1u << 1),
    f_intensity = (1u << 2),
    f_ambient_intensity = (1u << 3),
    f_cast_shadow = (1u << 4),
    f_shadow_strength = (1u << 5),
    f_enabled = (1u << 6),
    All = 0x7fu
};

inline dir_light_DeltaFlags operator|(dir_light_DeltaFlags a, dir_light_DeltaFlags b) {
    return static_cast<dir_light_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(dir_light_DeltaFlags flags, dir_light_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_dir_light(ByteWriter& w, const dse::DirectionalLight3DComponent& c) {
    w.WriteF32(c.direction.x); w.WriteF32(c.direction.y); w.WriteF32(c.direction.z);
    w.WriteF32(c.color.x); w.WriteF32(c.color.y); w.WriteF32(c.color.z);
    w.WriteF32(c.intensity);
    w.WriteF32(c.ambient_intensity);
    w.WriteU8(c.cast_shadow ? 1 : 0);
    w.WriteF32(c.shadow_strength);
    w.WriteU8(c.enabled ? 1 : 0);
}

/// Full snapshot read.
inline void ReadSnapshot_dir_light(ByteReader& r, dse::DirectionalLight3DComponent& c) {
    c.direction.x = r.ReadF32(); c.direction.y = r.ReadF32(); c.direction.z = r.ReadF32();
    c.color.x = r.ReadF32(); c.color.y = r.ReadF32(); c.color.z = r.ReadF32();
    c.intensity = r.ReadF32();
    c.ambient_intensity = r.ReadF32();
    c.cast_shadow = r.ReadU8() != 0;
    c.shadow_strength = r.ReadF32();
    c.enabled = r.ReadU8() != 0;
}

/// Compute delta between current and baseline.
inline dir_light_DeltaFlags ComputeDelta_dir_light(
        const dse::DirectionalLight3DComponent& cur,
        const dse::DirectionalLight3DComponent& base) {
    dir_light_DeltaFlags flags = dir_light_DeltaFlags::None;
    if (cur.direction.x != base.direction.x || cur.direction.y != base.direction.y || cur.direction.z != base.direction.z) flags = flags | dir_light_DeltaFlags::f_direction;
    if (cur.color.x != base.color.x || cur.color.y != base.color.y || cur.color.z != base.color.z) flags = flags | dir_light_DeltaFlags::f_color;
    if (cur.intensity != base.intensity) flags = flags | dir_light_DeltaFlags::f_intensity;
    if (cur.ambient_intensity != base.ambient_intensity) flags = flags | dir_light_DeltaFlags::f_ambient_intensity;
    if (cur.cast_shadow != base.cast_shadow) flags = flags | dir_light_DeltaFlags::f_cast_shadow;
    if (cur.shadow_strength != base.shadow_strength) flags = flags | dir_light_DeltaFlags::f_shadow_strength;
    if (cur.enabled != base.enabled) flags = flags | dir_light_DeltaFlags::f_enabled;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_dir_light(ByteWriter& w, const dse::DirectionalLight3DComponent& c, dir_light_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, dir_light_DeltaFlags::f_direction)) { w.WriteF32(c.direction.x); w.WriteF32(c.direction.y); w.WriteF32(c.direction.z); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_color)) { w.WriteF32(c.color.x); w.WriteF32(c.color.y); w.WriteF32(c.color.z); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_intensity)) { w.WriteF32(c.intensity); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_ambient_intensity)) { w.WriteF32(c.ambient_intensity); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_cast_shadow)) { w.WriteU8(c.cast_shadow ? 1 : 0); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_shadow_strength)) { w.WriteF32(c.shadow_strength); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
}

/// Read delta and apply to component.
inline void ReadDelta_dir_light(ByteReader& r, dse::DirectionalLight3DComponent& c) {
    auto flags = static_cast<dir_light_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, dir_light_DeltaFlags::f_direction)) { c.direction.x = r.ReadF32(); c.direction.y = r.ReadF32(); c.direction.z = r.ReadF32(); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_color)) { c.color.x = r.ReadF32(); c.color.y = r.ReadF32(); c.color.z = r.ReadF32(); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_intensity)) { c.intensity = r.ReadF32(); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_ambient_intensity)) { c.ambient_intensity = r.ReadF32(); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_cast_shadow)) { c.cast_shadow = r.ReadU8() != 0; }
    if (HasFlag(flags, dir_light_DeltaFlags::f_shadow_strength)) { c.shadow_strength = r.ReadF32(); }
    if (HasFlag(flags, dir_light_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
}
// ═══════════════════════════════════════════════════════════════════════════════
// PointLightComponent (prefix: point_light)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class point_light_DeltaFlags : uint32_t {
    None = 0,
    f_color = (1u << 0),
    f_intensity = (1u << 1),
    f_radius = (1u << 2),
    f_enabled = (1u << 3),
    f_cast_shadow = (1u << 4),
    All = 0x1fu
};

inline point_light_DeltaFlags operator|(point_light_DeltaFlags a, point_light_DeltaFlags b) {
    return static_cast<point_light_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(point_light_DeltaFlags flags, point_light_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_point_light(ByteWriter& w, const dse::PointLightComponent& c) {
    w.WriteF32(c.color.x); w.WriteF32(c.color.y); w.WriteF32(c.color.z);
    w.WriteF32(c.intensity);
    w.WriteF32(c.radius);
    w.WriteU8(c.enabled ? 1 : 0);
    w.WriteU8(c.cast_shadow ? 1 : 0);
}

/// Full snapshot read.
inline void ReadSnapshot_point_light(ByteReader& r, dse::PointLightComponent& c) {
    c.color.x = r.ReadF32(); c.color.y = r.ReadF32(); c.color.z = r.ReadF32();
    c.intensity = r.ReadF32();
    c.radius = r.ReadF32();
    c.enabled = r.ReadU8() != 0;
    c.cast_shadow = r.ReadU8() != 0;
}

/// Compute delta between current and baseline.
inline point_light_DeltaFlags ComputeDelta_point_light(
        const dse::PointLightComponent& cur,
        const dse::PointLightComponent& base) {
    point_light_DeltaFlags flags = point_light_DeltaFlags::None;
    if (cur.color.x != base.color.x || cur.color.y != base.color.y || cur.color.z != base.color.z) flags = flags | point_light_DeltaFlags::f_color;
    if (cur.intensity != base.intensity) flags = flags | point_light_DeltaFlags::f_intensity;
    if (cur.radius != base.radius) flags = flags | point_light_DeltaFlags::f_radius;
    if (cur.enabled != base.enabled) flags = flags | point_light_DeltaFlags::f_enabled;
    if (cur.cast_shadow != base.cast_shadow) flags = flags | point_light_DeltaFlags::f_cast_shadow;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_point_light(ByteWriter& w, const dse::PointLightComponent& c, point_light_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, point_light_DeltaFlags::f_color)) { w.WriteF32(c.color.x); w.WriteF32(c.color.y); w.WriteF32(c.color.z); }
    if (HasFlag(flags, point_light_DeltaFlags::f_intensity)) { w.WriteF32(c.intensity); }
    if (HasFlag(flags, point_light_DeltaFlags::f_radius)) { w.WriteF32(c.radius); }
    if (HasFlag(flags, point_light_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
    if (HasFlag(flags, point_light_DeltaFlags::f_cast_shadow)) { w.WriteU8(c.cast_shadow ? 1 : 0); }
}

/// Read delta and apply to component.
inline void ReadDelta_point_light(ByteReader& r, dse::PointLightComponent& c) {
    auto flags = static_cast<point_light_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, point_light_DeltaFlags::f_color)) { c.color.x = r.ReadF32(); c.color.y = r.ReadF32(); c.color.z = r.ReadF32(); }
    if (HasFlag(flags, point_light_DeltaFlags::f_intensity)) { c.intensity = r.ReadF32(); }
    if (HasFlag(flags, point_light_DeltaFlags::f_radius)) { c.radius = r.ReadF32(); }
    if (HasFlag(flags, point_light_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, point_light_DeltaFlags::f_cast_shadow)) { c.cast_shadow = r.ReadU8() != 0; }
}
// ═══════════════════════════════════════════════════════════════════════════════
// SpotLightComponent (prefix: spot_light)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class spot_light_DeltaFlags : uint32_t {
    None = 0,
    f_color = (1u << 0),
    f_intensity = (1u << 1),
    f_radius = (1u << 2),
    f_inner_cone_angle = (1u << 3),
    f_outer_cone_angle = (1u << 4),
    f_direction = (1u << 5),
    f_enabled = (1u << 6),
    f_cast_shadow = (1u << 7),
    All = 0xffu
};

inline spot_light_DeltaFlags operator|(spot_light_DeltaFlags a, spot_light_DeltaFlags b) {
    return static_cast<spot_light_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(spot_light_DeltaFlags flags, spot_light_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_spot_light(ByteWriter& w, const dse::SpotLightComponent& c) {
    w.WriteF32(c.color.x); w.WriteF32(c.color.y); w.WriteF32(c.color.z);
    w.WriteF32(c.intensity);
    w.WriteF32(c.radius);
    w.WriteF32(c.inner_cone_angle);
    w.WriteF32(c.outer_cone_angle);
    w.WriteF32(c.direction.x); w.WriteF32(c.direction.y); w.WriteF32(c.direction.z);
    w.WriteU8(c.enabled ? 1 : 0);
    w.WriteU8(c.cast_shadow ? 1 : 0);
}

/// Full snapshot read.
inline void ReadSnapshot_spot_light(ByteReader& r, dse::SpotLightComponent& c) {
    c.color.x = r.ReadF32(); c.color.y = r.ReadF32(); c.color.z = r.ReadF32();
    c.intensity = r.ReadF32();
    c.radius = r.ReadF32();
    c.inner_cone_angle = r.ReadF32();
    c.outer_cone_angle = r.ReadF32();
    c.direction.x = r.ReadF32(); c.direction.y = r.ReadF32(); c.direction.z = r.ReadF32();
    c.enabled = r.ReadU8() != 0;
    c.cast_shadow = r.ReadU8() != 0;
}

/// Compute delta between current and baseline.
inline spot_light_DeltaFlags ComputeDelta_spot_light(
        const dse::SpotLightComponent& cur,
        const dse::SpotLightComponent& base) {
    spot_light_DeltaFlags flags = spot_light_DeltaFlags::None;
    if (cur.color.x != base.color.x || cur.color.y != base.color.y || cur.color.z != base.color.z) flags = flags | spot_light_DeltaFlags::f_color;
    if (cur.intensity != base.intensity) flags = flags | spot_light_DeltaFlags::f_intensity;
    if (cur.radius != base.radius) flags = flags | spot_light_DeltaFlags::f_radius;
    if (cur.inner_cone_angle != base.inner_cone_angle) flags = flags | spot_light_DeltaFlags::f_inner_cone_angle;
    if (cur.outer_cone_angle != base.outer_cone_angle) flags = flags | spot_light_DeltaFlags::f_outer_cone_angle;
    if (cur.direction.x != base.direction.x || cur.direction.y != base.direction.y || cur.direction.z != base.direction.z) flags = flags | spot_light_DeltaFlags::f_direction;
    if (cur.enabled != base.enabled) flags = flags | spot_light_DeltaFlags::f_enabled;
    if (cur.cast_shadow != base.cast_shadow) flags = flags | spot_light_DeltaFlags::f_cast_shadow;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_spot_light(ByteWriter& w, const dse::SpotLightComponent& c, spot_light_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, spot_light_DeltaFlags::f_color)) { w.WriteF32(c.color.x); w.WriteF32(c.color.y); w.WriteF32(c.color.z); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_intensity)) { w.WriteF32(c.intensity); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_radius)) { w.WriteF32(c.radius); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_inner_cone_angle)) { w.WriteF32(c.inner_cone_angle); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_outer_cone_angle)) { w.WriteF32(c.outer_cone_angle); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_direction)) { w.WriteF32(c.direction.x); w.WriteF32(c.direction.y); w.WriteF32(c.direction.z); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_cast_shadow)) { w.WriteU8(c.cast_shadow ? 1 : 0); }
}

/// Read delta and apply to component.
inline void ReadDelta_spot_light(ByteReader& r, dse::SpotLightComponent& c) {
    auto flags = static_cast<spot_light_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, spot_light_DeltaFlags::f_color)) { c.color.x = r.ReadF32(); c.color.y = r.ReadF32(); c.color.z = r.ReadF32(); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_intensity)) { c.intensity = r.ReadF32(); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_radius)) { c.radius = r.ReadF32(); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_inner_cone_angle)) { c.inner_cone_angle = r.ReadF32(); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_outer_cone_angle)) { c.outer_cone_angle = r.ReadF32(); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_direction)) { c.direction.x = r.ReadF32(); c.direction.y = r.ReadF32(); c.direction.z = r.ReadF32(); }
    if (HasFlag(flags, spot_light_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, spot_light_DeltaFlags::f_cast_shadow)) { c.cast_shadow = r.ReadU8() != 0; }
}
// ═══════════════════════════════════════════════════════════════════════════════
// SkyLightComponent (prefix: sky_light)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class sky_light_DeltaFlags : uint32_t {
    None = 0,
    f_up_color = (1u << 0),
    f_down_color = (1u << 1),
    f_intensity = (1u << 2),
    f_enabled = (1u << 3),
    All = 0xfu
};

inline sky_light_DeltaFlags operator|(sky_light_DeltaFlags a, sky_light_DeltaFlags b) {
    return static_cast<sky_light_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(sky_light_DeltaFlags flags, sky_light_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_sky_light(ByteWriter& w, const dse::SkyLightComponent& c) {
    w.WriteF32(c.up_color.x); w.WriteF32(c.up_color.y); w.WriteF32(c.up_color.z);
    w.WriteF32(c.down_color.x); w.WriteF32(c.down_color.y); w.WriteF32(c.down_color.z);
    w.WriteF32(c.intensity);
    w.WriteU8(c.enabled ? 1 : 0);
}

/// Full snapshot read.
inline void ReadSnapshot_sky_light(ByteReader& r, dse::SkyLightComponent& c) {
    c.up_color.x = r.ReadF32(); c.up_color.y = r.ReadF32(); c.up_color.z = r.ReadF32();
    c.down_color.x = r.ReadF32(); c.down_color.y = r.ReadF32(); c.down_color.z = r.ReadF32();
    c.intensity = r.ReadF32();
    c.enabled = r.ReadU8() != 0;
}

/// Compute delta between current and baseline.
inline sky_light_DeltaFlags ComputeDelta_sky_light(
        const dse::SkyLightComponent& cur,
        const dse::SkyLightComponent& base) {
    sky_light_DeltaFlags flags = sky_light_DeltaFlags::None;
    if (cur.up_color.x != base.up_color.x || cur.up_color.y != base.up_color.y || cur.up_color.z != base.up_color.z) flags = flags | sky_light_DeltaFlags::f_up_color;
    if (cur.down_color.x != base.down_color.x || cur.down_color.y != base.down_color.y || cur.down_color.z != base.down_color.z) flags = flags | sky_light_DeltaFlags::f_down_color;
    if (cur.intensity != base.intensity) flags = flags | sky_light_DeltaFlags::f_intensity;
    if (cur.enabled != base.enabled) flags = flags | sky_light_DeltaFlags::f_enabled;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_sky_light(ByteWriter& w, const dse::SkyLightComponent& c, sky_light_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, sky_light_DeltaFlags::f_up_color)) { w.WriteF32(c.up_color.x); w.WriteF32(c.up_color.y); w.WriteF32(c.up_color.z); }
    if (HasFlag(flags, sky_light_DeltaFlags::f_down_color)) { w.WriteF32(c.down_color.x); w.WriteF32(c.down_color.y); w.WriteF32(c.down_color.z); }
    if (HasFlag(flags, sky_light_DeltaFlags::f_intensity)) { w.WriteF32(c.intensity); }
    if (HasFlag(flags, sky_light_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
}

/// Read delta and apply to component.
inline void ReadDelta_sky_light(ByteReader& r, dse::SkyLightComponent& c) {
    auto flags = static_cast<sky_light_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, sky_light_DeltaFlags::f_up_color)) { c.up_color.x = r.ReadF32(); c.up_color.y = r.ReadF32(); c.up_color.z = r.ReadF32(); }
    if (HasFlag(flags, sky_light_DeltaFlags::f_down_color)) { c.down_color.x = r.ReadF32(); c.down_color.y = r.ReadF32(); c.down_color.z = r.ReadF32(); }
    if (HasFlag(flags, sky_light_DeltaFlags::f_intensity)) { c.intensity = r.ReadF32(); }
    if (HasFlag(flags, sky_light_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
}
// ═══════════════════════════════════════════════════════════════════════════════
// TreeComponent (prefix: tree)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class tree_DeltaFlags : uint32_t {
    None = 0,
    f_enabled = (1u << 0),
    f_density = (1u << 1),
    f_spawn_radius = (1u << 2),
    f_chunk_size = (1u << 3),
    f_min_scale = (1u << 4),
    f_max_scale = (1u << 5),
    f_lod1_distance = (1u << 6),
    f_cull_distance = (1u << 7),
    f_wind_strength = (1u << 8),
    f_wind_speed = (1u << 9),
    f_cast_shadow = (1u << 10),
    f_shadow_distance = (1u << 11),
    f_seed = (1u << 12),
    f_height_variation = (1u << 13),
    f_random_rotation = (1u << 14),
    f_billboard_distance = (1u << 15),
    All = 0xffffu
};

inline tree_DeltaFlags operator|(tree_DeltaFlags a, tree_DeltaFlags b) {
    return static_cast<tree_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(tree_DeltaFlags flags, tree_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_tree(ByteWriter& w, const dse::TreeComponent& c) {
    w.WriteU8(c.enabled ? 1 : 0);
    w.WriteF32(c.density);
    w.WriteF32(c.spawn_radius);
    w.WriteF32(c.chunk_size);
    w.WriteF32(c.min_scale);
    w.WriteF32(c.max_scale);
    w.WriteF32(c.lod1_distance);
    w.WriteF32(c.cull_distance);
    w.WriteF32(c.wind_strength);
    w.WriteF32(c.wind_speed);
    w.WriteU8(c.cast_shadow ? 1 : 0);
    w.WriteF32(c.shadow_distance);
    w.WriteU32(static_cast<uint32_t>(c.seed));
    w.WriteF32(c.height_variation);
    w.WriteU8(c.random_rotation ? 1 : 0);
    w.WriteF32(c.billboard_distance);
}

/// Full snapshot read.
inline void ReadSnapshot_tree(ByteReader& r, dse::TreeComponent& c) {
    c.enabled = r.ReadU8() != 0;
    c.density = r.ReadF32();
    c.spawn_radius = r.ReadF32();
    c.chunk_size = r.ReadF32();
    c.min_scale = r.ReadF32();
    c.max_scale = r.ReadF32();
    c.lod1_distance = r.ReadF32();
    c.cull_distance = r.ReadF32();
    c.wind_strength = r.ReadF32();
    c.wind_speed = r.ReadF32();
    c.cast_shadow = r.ReadU8() != 0;
    c.shadow_distance = r.ReadF32();
    c.seed = static_cast<int>(r.ReadU32());
    c.height_variation = r.ReadF32();
    c.random_rotation = r.ReadU8() != 0;
    c.billboard_distance = r.ReadF32();
}

/// Compute delta between current and baseline.
inline tree_DeltaFlags ComputeDelta_tree(
        const dse::TreeComponent& cur,
        const dse::TreeComponent& base) {
    tree_DeltaFlags flags = tree_DeltaFlags::None;
    if (cur.enabled != base.enabled) flags = flags | tree_DeltaFlags::f_enabled;
    if (cur.density != base.density) flags = flags | tree_DeltaFlags::f_density;
    if (cur.spawn_radius != base.spawn_radius) flags = flags | tree_DeltaFlags::f_spawn_radius;
    if (cur.chunk_size != base.chunk_size) flags = flags | tree_DeltaFlags::f_chunk_size;
    if (cur.min_scale != base.min_scale) flags = flags | tree_DeltaFlags::f_min_scale;
    if (cur.max_scale != base.max_scale) flags = flags | tree_DeltaFlags::f_max_scale;
    if (cur.lod1_distance != base.lod1_distance) flags = flags | tree_DeltaFlags::f_lod1_distance;
    if (cur.cull_distance != base.cull_distance) flags = flags | tree_DeltaFlags::f_cull_distance;
    if (cur.wind_strength != base.wind_strength) flags = flags | tree_DeltaFlags::f_wind_strength;
    if (cur.wind_speed != base.wind_speed) flags = flags | tree_DeltaFlags::f_wind_speed;
    if (cur.cast_shadow != base.cast_shadow) flags = flags | tree_DeltaFlags::f_cast_shadow;
    if (cur.shadow_distance != base.shadow_distance) flags = flags | tree_DeltaFlags::f_shadow_distance;
    if (cur.seed != base.seed) flags = flags | tree_DeltaFlags::f_seed;
    if (cur.height_variation != base.height_variation) flags = flags | tree_DeltaFlags::f_height_variation;
    if (cur.random_rotation != base.random_rotation) flags = flags | tree_DeltaFlags::f_random_rotation;
    if (cur.billboard_distance != base.billboard_distance) flags = flags | tree_DeltaFlags::f_billboard_distance;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_tree(ByteWriter& w, const dse::TreeComponent& c, tree_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, tree_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
    if (HasFlag(flags, tree_DeltaFlags::f_density)) { w.WriteF32(c.density); }
    if (HasFlag(flags, tree_DeltaFlags::f_spawn_radius)) { w.WriteF32(c.spawn_radius); }
    if (HasFlag(flags, tree_DeltaFlags::f_chunk_size)) { w.WriteF32(c.chunk_size); }
    if (HasFlag(flags, tree_DeltaFlags::f_min_scale)) { w.WriteF32(c.min_scale); }
    if (HasFlag(flags, tree_DeltaFlags::f_max_scale)) { w.WriteF32(c.max_scale); }
    if (HasFlag(flags, tree_DeltaFlags::f_lod1_distance)) { w.WriteF32(c.lod1_distance); }
    if (HasFlag(flags, tree_DeltaFlags::f_cull_distance)) { w.WriteF32(c.cull_distance); }
    if (HasFlag(flags, tree_DeltaFlags::f_wind_strength)) { w.WriteF32(c.wind_strength); }
    if (HasFlag(flags, tree_DeltaFlags::f_wind_speed)) { w.WriteF32(c.wind_speed); }
    if (HasFlag(flags, tree_DeltaFlags::f_cast_shadow)) { w.WriteU8(c.cast_shadow ? 1 : 0); }
    if (HasFlag(flags, tree_DeltaFlags::f_shadow_distance)) { w.WriteF32(c.shadow_distance); }
    if (HasFlag(flags, tree_DeltaFlags::f_seed)) { w.WriteU32(static_cast<uint32_t>(c.seed)); }
    if (HasFlag(flags, tree_DeltaFlags::f_height_variation)) { w.WriteF32(c.height_variation); }
    if (HasFlag(flags, tree_DeltaFlags::f_random_rotation)) { w.WriteU8(c.random_rotation ? 1 : 0); }
    if (HasFlag(flags, tree_DeltaFlags::f_billboard_distance)) { w.WriteF32(c.billboard_distance); }
}

/// Read delta and apply to component.
inline void ReadDelta_tree(ByteReader& r, dse::TreeComponent& c) {
    auto flags = static_cast<tree_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, tree_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, tree_DeltaFlags::f_density)) { c.density = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_spawn_radius)) { c.spawn_radius = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_chunk_size)) { c.chunk_size = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_min_scale)) { c.min_scale = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_max_scale)) { c.max_scale = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_lod1_distance)) { c.lod1_distance = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_cull_distance)) { c.cull_distance = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_wind_strength)) { c.wind_strength = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_wind_speed)) { c.wind_speed = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_cast_shadow)) { c.cast_shadow = r.ReadU8() != 0; }
    if (HasFlag(flags, tree_DeltaFlags::f_shadow_distance)) { c.shadow_distance = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_seed)) { c.seed = static_cast<int>(r.ReadU32()); }
    if (HasFlag(flags, tree_DeltaFlags::f_height_variation)) { c.height_variation = r.ReadF32(); }
    if (HasFlag(flags, tree_DeltaFlags::f_random_rotation)) { c.random_rotation = r.ReadU8() != 0; }
    if (HasFlag(flags, tree_DeltaFlags::f_billboard_distance)) { c.billboard_distance = r.ReadF32(); }
}
// ═══════════════════════════════════════════════════════════════════════════════
// TerrainTileManagerComponent (prefix: terrain_tile)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class terrain_tile_DeltaFlags : uint32_t {
    None = 0,
    f_enabled = (1u << 0),
    f_tile_world_size = (1u << 1),
    f_tile_resolution = (1u << 2),
    f_max_height = (1u << 3),
    f_load_radius = (1u << 4),
    f_unload_radius = (1u << 5),
    f_use_procedural = (1u << 6),
    f_procedural_base_height = (1u << 7),
    f_max_lod_levels = (1u << 8),
    f_lod_distance_factor = (1u << 9),
    All = 0x3ffu
};

inline terrain_tile_DeltaFlags operator|(terrain_tile_DeltaFlags a, terrain_tile_DeltaFlags b) {
    return static_cast<terrain_tile_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(terrain_tile_DeltaFlags flags, terrain_tile_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_terrain_tile(ByteWriter& w, const dse::TerrainTileManagerComponent& c) {
    w.WriteU8(c.enabled ? 1 : 0);
    w.WriteF32(c.tile_world_size);
    w.WriteU32(static_cast<uint32_t>(c.tile_resolution));
    w.WriteF32(c.max_height);
    w.WriteF32(c.load_radius);
    w.WriteF32(c.unload_radius);
    w.WriteU8(c.use_procedural ? 1 : 0);
    w.WriteF32(c.procedural_base_height);
    w.WriteU32(static_cast<uint32_t>(c.max_lod_levels));
    w.WriteF32(c.lod_distance_factor);
}

/// Full snapshot read.
inline void ReadSnapshot_terrain_tile(ByteReader& r, dse::TerrainTileManagerComponent& c) {
    c.enabled = r.ReadU8() != 0;
    c.tile_world_size = r.ReadF32();
    c.tile_resolution = static_cast<int>(r.ReadU32());
    c.max_height = r.ReadF32();
    c.load_radius = r.ReadF32();
    c.unload_radius = r.ReadF32();
    c.use_procedural = r.ReadU8() != 0;
    c.procedural_base_height = r.ReadF32();
    c.max_lod_levels = static_cast<int>(r.ReadU32());
    c.lod_distance_factor = r.ReadF32();
}

/// Compute delta between current and baseline.
inline terrain_tile_DeltaFlags ComputeDelta_terrain_tile(
        const dse::TerrainTileManagerComponent& cur,
        const dse::TerrainTileManagerComponent& base) {
    terrain_tile_DeltaFlags flags = terrain_tile_DeltaFlags::None;
    if (cur.enabled != base.enabled) flags = flags | terrain_tile_DeltaFlags::f_enabled;
    if (cur.tile_world_size != base.tile_world_size) flags = flags | terrain_tile_DeltaFlags::f_tile_world_size;
    if (cur.tile_resolution != base.tile_resolution) flags = flags | terrain_tile_DeltaFlags::f_tile_resolution;
    if (cur.max_height != base.max_height) flags = flags | terrain_tile_DeltaFlags::f_max_height;
    if (cur.load_radius != base.load_radius) flags = flags | terrain_tile_DeltaFlags::f_load_radius;
    if (cur.unload_radius != base.unload_radius) flags = flags | terrain_tile_DeltaFlags::f_unload_radius;
    if (cur.use_procedural != base.use_procedural) flags = flags | terrain_tile_DeltaFlags::f_use_procedural;
    if (cur.procedural_base_height != base.procedural_base_height) flags = flags | terrain_tile_DeltaFlags::f_procedural_base_height;
    if (cur.max_lod_levels != base.max_lod_levels) flags = flags | terrain_tile_DeltaFlags::f_max_lod_levels;
    if (cur.lod_distance_factor != base.lod_distance_factor) flags = flags | terrain_tile_DeltaFlags::f_lod_distance_factor;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_terrain_tile(ByteWriter& w, const dse::TerrainTileManagerComponent& c, terrain_tile_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_tile_world_size)) { w.WriteF32(c.tile_world_size); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_tile_resolution)) { w.WriteU32(static_cast<uint32_t>(c.tile_resolution)); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_max_height)) { w.WriteF32(c.max_height); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_load_radius)) { w.WriteF32(c.load_radius); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_unload_radius)) { w.WriteF32(c.unload_radius); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_use_procedural)) { w.WriteU8(c.use_procedural ? 1 : 0); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_procedural_base_height)) { w.WriteF32(c.procedural_base_height); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_max_lod_levels)) { w.WriteU32(static_cast<uint32_t>(c.max_lod_levels)); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_lod_distance_factor)) { w.WriteF32(c.lod_distance_factor); }
}

/// Read delta and apply to component.
inline void ReadDelta_terrain_tile(ByteReader& r, dse::TerrainTileManagerComponent& c) {
    auto flags = static_cast<terrain_tile_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_tile_world_size)) { c.tile_world_size = r.ReadF32(); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_tile_resolution)) { c.tile_resolution = static_cast<int>(r.ReadU32()); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_max_height)) { c.max_height = r.ReadF32(); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_load_radius)) { c.load_radius = r.ReadF32(); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_unload_radius)) { c.unload_radius = r.ReadF32(); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_use_procedural)) { c.use_procedural = r.ReadU8() != 0; }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_procedural_base_height)) { c.procedural_base_height = r.ReadF32(); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_max_lod_levels)) { c.max_lod_levels = static_cast<int>(r.ReadU32()); }
    if (HasFlag(flags, terrain_tile_DeltaFlags::f_lod_distance_factor)) { c.lod_distance_factor = r.ReadF32(); }
}
// ═══════════════════════════════════════════════════════════════════════════════
// DynamicObstacleComponent (prefix: dyn_obstacle)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class dyn_obstacle_DeltaFlags : uint32_t {
    None = 0,
    f_enabled = (1u << 0),
    f_box_extents = (1u << 1),
    f_cylinder_radius = (1u << 2),
    f_cylinder_height = (1u << 3),
    All = 0xfu
};

inline dyn_obstacle_DeltaFlags operator|(dyn_obstacle_DeltaFlags a, dyn_obstacle_DeltaFlags b) {
    return static_cast<dyn_obstacle_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(dyn_obstacle_DeltaFlags flags, dyn_obstacle_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_dyn_obstacle(ByteWriter& w, const dse::DynamicObstacleComponent& c) {
    w.WriteU8(c.enabled ? 1 : 0);
    w.WriteF32(c.box_extents.x); w.WriteF32(c.box_extents.y); w.WriteF32(c.box_extents.z);
    w.WriteF32(c.cylinder_radius);
    w.WriteF32(c.cylinder_height);
}

/// Full snapshot read.
inline void ReadSnapshot_dyn_obstacle(ByteReader& r, dse::DynamicObstacleComponent& c) {
    c.enabled = r.ReadU8() != 0;
    c.box_extents.x = r.ReadF32(); c.box_extents.y = r.ReadF32(); c.box_extents.z = r.ReadF32();
    c.cylinder_radius = r.ReadF32();
    c.cylinder_height = r.ReadF32();
    c.dirty_ = true;
}

/// Compute delta between current and baseline.
inline dyn_obstacle_DeltaFlags ComputeDelta_dyn_obstacle(
        const dse::DynamicObstacleComponent& cur,
        const dse::DynamicObstacleComponent& base) {
    dyn_obstacle_DeltaFlags flags = dyn_obstacle_DeltaFlags::None;
    if (cur.enabled != base.enabled) flags = flags | dyn_obstacle_DeltaFlags::f_enabled;
    if (cur.box_extents.x != base.box_extents.x || cur.box_extents.y != base.box_extents.y || cur.box_extents.z != base.box_extents.z) flags = flags | dyn_obstacle_DeltaFlags::f_box_extents;
    if (cur.cylinder_radius != base.cylinder_radius) flags = flags | dyn_obstacle_DeltaFlags::f_cylinder_radius;
    if (cur.cylinder_height != base.cylinder_height) flags = flags | dyn_obstacle_DeltaFlags::f_cylinder_height;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_dyn_obstacle(ByteWriter& w, const dse::DynamicObstacleComponent& c, dyn_obstacle_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, dyn_obstacle_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
    if (HasFlag(flags, dyn_obstacle_DeltaFlags::f_box_extents)) { w.WriteF32(c.box_extents.x); w.WriteF32(c.box_extents.y); w.WriteF32(c.box_extents.z); }
    if (HasFlag(flags, dyn_obstacle_DeltaFlags::f_cylinder_radius)) { w.WriteF32(c.cylinder_radius); }
    if (HasFlag(flags, dyn_obstacle_DeltaFlags::f_cylinder_height)) { w.WriteF32(c.cylinder_height); }
}

/// Read delta and apply to component.
inline void ReadDelta_dyn_obstacle(ByteReader& r, dse::DynamicObstacleComponent& c) {
    auto flags = static_cast<dyn_obstacle_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, dyn_obstacle_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, dyn_obstacle_DeltaFlags::f_box_extents)) { c.box_extents.x = r.ReadF32(); c.box_extents.y = r.ReadF32(); c.box_extents.z = r.ReadF32(); }
    if (HasFlag(flags, dyn_obstacle_DeltaFlags::f_cylinder_radius)) { c.cylinder_radius = r.ReadF32(); }
    if (HasFlag(flags, dyn_obstacle_DeltaFlags::f_cylinder_height)) { c.cylinder_height = r.ReadF32(); }
    if (static_cast<uint32_t>(flags) != 0) c.dirty_ = true;
}
// ═══════════════════════════════════════════════════════════════════════════════
// NavMeshAutoRebakeComponent (prefix: navmesh_rebake)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class navmesh_rebake_DeltaFlags : uint32_t {
    None = 0,
    f_enabled = (1u << 0),
    f_tile_size = (1u << 1),
    f_rebake_cooldown = (1u << 2),
    f_collect_terrain = (1u << 3),
    f_collect_mesh_renderers = (1u << 4),
    f_agent_height = (1u << 5),
    f_agent_radius = (1u << 6),
    f_agent_max_climb = (1u << 7),
    f_agent_max_slope = (1u << 8),
    f_cell_size = (1u << 9),
    f_cell_height = (1u << 10),
    All = 0x7ffu
};

inline navmesh_rebake_DeltaFlags operator|(navmesh_rebake_DeltaFlags a, navmesh_rebake_DeltaFlags b) {
    return static_cast<navmesh_rebake_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(navmesh_rebake_DeltaFlags flags, navmesh_rebake_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_navmesh_rebake(ByteWriter& w, const dse::NavMeshAutoRebakeComponent& c) {
    w.WriteU8(c.enabled ? 1 : 0);
    w.WriteF32(c.tile_size);
    w.WriteF32(c.rebake_cooldown);
    w.WriteU8(c.collect_terrain ? 1 : 0);
    w.WriteU8(c.collect_mesh_renderers ? 1 : 0);
    w.WriteF32(c.agent_height);
    w.WriteF32(c.agent_radius);
    w.WriteF32(c.agent_max_climb);
    w.WriteF32(c.agent_max_slope);
    w.WriteF32(c.cell_size);
    w.WriteF32(c.cell_height);
}

/// Full snapshot read.
inline void ReadSnapshot_navmesh_rebake(ByteReader& r, dse::NavMeshAutoRebakeComponent& c) {
    c.enabled = r.ReadU8() != 0;
    c.tile_size = r.ReadF32();
    c.rebake_cooldown = r.ReadF32();
    c.collect_terrain = r.ReadU8() != 0;
    c.collect_mesh_renderers = r.ReadU8() != 0;
    c.agent_height = r.ReadF32();
    c.agent_radius = r.ReadF32();
    c.agent_max_climb = r.ReadF32();
    c.agent_max_slope = r.ReadF32();
    c.cell_size = r.ReadF32();
    c.cell_height = r.ReadF32();
}

/// Compute delta between current and baseline.
inline navmesh_rebake_DeltaFlags ComputeDelta_navmesh_rebake(
        const dse::NavMeshAutoRebakeComponent& cur,
        const dse::NavMeshAutoRebakeComponent& base) {
    navmesh_rebake_DeltaFlags flags = navmesh_rebake_DeltaFlags::None;
    if (cur.enabled != base.enabled) flags = flags | navmesh_rebake_DeltaFlags::f_enabled;
    if (cur.tile_size != base.tile_size) flags = flags | navmesh_rebake_DeltaFlags::f_tile_size;
    if (cur.rebake_cooldown != base.rebake_cooldown) flags = flags | navmesh_rebake_DeltaFlags::f_rebake_cooldown;
    if (cur.collect_terrain != base.collect_terrain) flags = flags | navmesh_rebake_DeltaFlags::f_collect_terrain;
    if (cur.collect_mesh_renderers != base.collect_mesh_renderers) flags = flags | navmesh_rebake_DeltaFlags::f_collect_mesh_renderers;
    if (cur.agent_height != base.agent_height) flags = flags | navmesh_rebake_DeltaFlags::f_agent_height;
    if (cur.agent_radius != base.agent_radius) flags = flags | navmesh_rebake_DeltaFlags::f_agent_radius;
    if (cur.agent_max_climb != base.agent_max_climb) flags = flags | navmesh_rebake_DeltaFlags::f_agent_max_climb;
    if (cur.agent_max_slope != base.agent_max_slope) flags = flags | navmesh_rebake_DeltaFlags::f_agent_max_slope;
    if (cur.cell_size != base.cell_size) flags = flags | navmesh_rebake_DeltaFlags::f_cell_size;
    if (cur.cell_height != base.cell_height) flags = flags | navmesh_rebake_DeltaFlags::f_cell_height;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_navmesh_rebake(ByteWriter& w, const dse::NavMeshAutoRebakeComponent& c, navmesh_rebake_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_tile_size)) { w.WriteF32(c.tile_size); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_rebake_cooldown)) { w.WriteF32(c.rebake_cooldown); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_collect_terrain)) { w.WriteU8(c.collect_terrain ? 1 : 0); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_collect_mesh_renderers)) { w.WriteU8(c.collect_mesh_renderers ? 1 : 0); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_agent_height)) { w.WriteF32(c.agent_height); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_agent_radius)) { w.WriteF32(c.agent_radius); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_agent_max_climb)) { w.WriteF32(c.agent_max_climb); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_agent_max_slope)) { w.WriteF32(c.agent_max_slope); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_cell_size)) { w.WriteF32(c.cell_size); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_cell_height)) { w.WriteF32(c.cell_height); }
}

/// Read delta and apply to component.
inline void ReadDelta_navmesh_rebake(ByteReader& r, dse::NavMeshAutoRebakeComponent& c) {
    auto flags = static_cast<navmesh_rebake_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_tile_size)) { c.tile_size = r.ReadF32(); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_rebake_cooldown)) { c.rebake_cooldown = r.ReadF32(); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_collect_terrain)) { c.collect_terrain = r.ReadU8() != 0; }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_collect_mesh_renderers)) { c.collect_mesh_renderers = r.ReadU8() != 0; }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_agent_height)) { c.agent_height = r.ReadF32(); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_agent_radius)) { c.agent_radius = r.ReadF32(); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_agent_max_climb)) { c.agent_max_climb = r.ReadF32(); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_agent_max_slope)) { c.agent_max_slope = r.ReadF32(); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_cell_size)) { c.cell_size = r.ReadF32(); }
    if (HasFlag(flags, navmesh_rebake_DeltaFlags::f_cell_height)) { c.cell_height = r.ReadF32(); }
}
// ═══════════════════════════════════════════════════════════════════════════════
// PostProcessComponent (prefix: post_process)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class post_process_DeltaFlags : uint32_t {
    None = 0,
    f_enabled = (1u << 0),
    f_bloom_enabled = (1u << 1),
    f_bloom_threshold = (1u << 2),
    f_bloom_intensity = (1u << 3),
    f_bloom_knee = (1u << 4),
    f_bloom_mip_weight = (1u << 5),
    f_color_grading_enabled = (1u << 6),
    f_exposure = (1u << 7),
    f_gamma = (1u << 8),
    f_ssao_enabled = (1u << 9),
    f_ssao_radius = (1u << 10),
    f_ssao_bias = (1u << 11),
    f_ssao_sample_count = (1u << 12),
    f_ssao_power = (1u << 13),
    f_ssao_intensity = (1u << 14),
    f_auto_exposure_enabled = (1u << 15),
    f_exposure_min = (1u << 16),
    f_exposure_max = (1u << 17),
    f_adaptation_speed_up = (1u << 18),
    f_adaptation_speed_down = (1u << 19),
    f_exposure_compensation = (1u << 20),
    f_color_lut_intensity = (1u << 21),
    f_vignette_enabled = (1u << 22),
    f_vignette_intensity = (1u << 23),
    f_vignette_radius = (1u << 24),
    f_vignette_softness = (1u << 25),
    f_film_grain_enabled = (1u << 26),
    f_film_grain_intensity = (1u << 27),
    f_film_grain_time_scale = (1u << 28),
    f_fxaa_enabled = (1u << 29),
    f_taa_enabled = (1u << 30),
    f_taa_blend_factor = (1u << 31),
    f_contact_shadow_enabled = (1u << 32),
    f_contact_shadow_strength = (1u << 33),
    f_contact_shadow_steps = (1u << 34),
    f_contact_shadow_step_size = (1u << 35),
    f_dof_enabled = (1u << 36),
    f_dof_focus_distance = (1u << 37),
    f_dof_focus_range = (1u << 38),
    f_dof_bokeh_radius = (1u << 39),
    f_motion_blur_enabled = (1u << 40),
    f_motion_blur_intensity = (1u << 41),
    f_motion_blur_samples = (1u << 42),
    f_ssr_enabled = (1u << 43),
    f_ssr_max_distance = (1u << 44),
    f_ssr_thickness = (1u << 45),
    f_ssr_step_size = (1u << 46),
    f_ssr_max_steps = (1u << 47),
    f_ssr_fade_distance = (1u << 48),
    f_ssr_max_roughness = (1u << 49),
    f_outline_enabled = (1u << 50),
    f_outline_color = (1u << 51),
    f_outline_thickness = (1u << 52),
    f_outline_depth_threshold = (1u << 53),
    f_outline_normal_threshold = (1u << 54),
    f_light_shaft_enabled = (1u << 55),
    f_light_shaft_color = (1u << 56),
    f_light_shaft_density = (1u << 57),
    f_light_shaft_weight = (1u << 58),
    f_light_shaft_decay = (1u << 59),
    f_light_shaft_exposure = (1u << 60),
    f_light_shaft_intensity = (1u << 61),
    f_light_shaft_samples = (1u << 62),
    f_fog_enabled = (1u << 63),
    f_fog_color = (1u << 64),
    f_fog_density = (1u << 65),
    f_fog_height_falloff = (1u << 66),
    f_fog_height_offset = (1u << 67),
    f_fog_start = (1u << 68),
    f_fog_end = (1u << 69),
    f_fog_steps = (1u << 70),
    f_fog_sun_scatter = (1u << 71),
    All = 0xffffffffffffffffffu
};

inline post_process_DeltaFlags operator|(post_process_DeltaFlags a, post_process_DeltaFlags b) {
    return static_cast<post_process_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(post_process_DeltaFlags flags, post_process_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_post_process(ByteWriter& w, const dse::PostProcessComponent& c) {
    w.WriteU8(c.enabled ? 1 : 0);
    w.WriteU8(c.bloom_enabled ? 1 : 0);
    w.WriteF32(c.bloom_threshold);
    w.WriteF32(c.bloom_intensity);
    w.WriteF32(c.bloom_knee);
    w.WriteF32(c.bloom_mip_weight);
    w.WriteU8(c.color_grading_enabled ? 1 : 0);
    w.WriteF32(c.exposure);
    w.WriteF32(c.gamma);
    w.WriteU8(c.ssao_enabled ? 1 : 0);
    w.WriteF32(c.ssao_radius);
    w.WriteF32(c.ssao_bias);
    w.WriteU32(static_cast<uint32_t>(c.ssao_sample_count));
    w.WriteF32(c.ssao_power);
    w.WriteF32(c.ssao_intensity);
    w.WriteU8(c.auto_exposure_enabled ? 1 : 0);
    w.WriteF32(c.exposure_min);
    w.WriteF32(c.exposure_max);
    w.WriteF32(c.adaptation_speed_up);
    w.WriteF32(c.adaptation_speed_down);
    w.WriteF32(c.exposure_compensation);
    w.WriteF32(c.color_lut_intensity);
    w.WriteU8(c.vignette_enabled ? 1 : 0);
    w.WriteF32(c.vignette_intensity);
    w.WriteF32(c.vignette_radius);
    w.WriteF32(c.vignette_softness);
    w.WriteU8(c.film_grain_enabled ? 1 : 0);
    w.WriteF32(c.film_grain_intensity);
    w.WriteF32(c.film_grain_time_scale);
    w.WriteU8(c.fxaa_enabled ? 1 : 0);
    w.WriteU8(c.taa_enabled ? 1 : 0);
    w.WriteF32(c.taa_blend_factor);
    w.WriteU8(c.contact_shadow_enabled ? 1 : 0);
    w.WriteF32(c.contact_shadow_strength);
    w.WriteU32(static_cast<uint32_t>(c.contact_shadow_steps));
    w.WriteF32(c.contact_shadow_step_size);
    w.WriteU8(c.dof_enabled ? 1 : 0);
    w.WriteF32(c.dof_focus_distance);
    w.WriteF32(c.dof_focus_range);
    w.WriteF32(c.dof_bokeh_radius);
    w.WriteU8(c.motion_blur_enabled ? 1 : 0);
    w.WriteF32(c.motion_blur_intensity);
    w.WriteU32(static_cast<uint32_t>(c.motion_blur_samples));
    w.WriteU8(c.ssr_enabled ? 1 : 0);
    w.WriteF32(c.ssr_max_distance);
    w.WriteF32(c.ssr_thickness);
    w.WriteF32(c.ssr_step_size);
    w.WriteU32(static_cast<uint32_t>(c.ssr_max_steps));
    w.WriteF32(c.ssr_fade_distance);
    w.WriteF32(c.ssr_max_roughness);
    w.WriteU8(c.outline_enabled ? 1 : 0);
    w.WriteF32(c.outline_color.x); w.WriteF32(c.outline_color.y); w.WriteF32(c.outline_color.z);
    w.WriteF32(c.outline_thickness);
    w.WriteF32(c.outline_depth_threshold);
    w.WriteF32(c.outline_normal_threshold);
    w.WriteU8(c.light_shaft_enabled ? 1 : 0);
    w.WriteF32(c.light_shaft_color.x); w.WriteF32(c.light_shaft_color.y); w.WriteF32(c.light_shaft_color.z);
    w.WriteF32(c.light_shaft_density);
    w.WriteF32(c.light_shaft_weight);
    w.WriteF32(c.light_shaft_decay);
    w.WriteF32(c.light_shaft_exposure);
    w.WriteF32(c.light_shaft_intensity);
    w.WriteU32(static_cast<uint32_t>(c.light_shaft_samples));
    w.WriteU8(c.fog_enabled ? 1 : 0);
    w.WriteF32(c.fog_color.x); w.WriteF32(c.fog_color.y); w.WriteF32(c.fog_color.z);
    w.WriteF32(c.fog_density);
    w.WriteF32(c.fog_height_falloff);
    w.WriteF32(c.fog_height_offset);
    w.WriteF32(c.fog_start);
    w.WriteF32(c.fog_end);
    w.WriteU32(static_cast<uint32_t>(c.fog_steps));
    w.WriteF32(c.fog_sun_scatter);
}

/// Full snapshot read.
inline void ReadSnapshot_post_process(ByteReader& r, dse::PostProcessComponent& c) {
    c.enabled = r.ReadU8() != 0;
    c.bloom_enabled = r.ReadU8() != 0;
    c.bloom_threshold = r.ReadF32();
    c.bloom_intensity = r.ReadF32();
    c.bloom_knee = r.ReadF32();
    c.bloom_mip_weight = r.ReadF32();
    c.color_grading_enabled = r.ReadU8() != 0;
    c.exposure = r.ReadF32();
    c.gamma = r.ReadF32();
    c.ssao_enabled = r.ReadU8() != 0;
    c.ssao_radius = r.ReadF32();
    c.ssao_bias = r.ReadF32();
    c.ssao_sample_count = static_cast<int>(r.ReadU32());
    c.ssao_power = r.ReadF32();
    c.ssao_intensity = r.ReadF32();
    c.auto_exposure_enabled = r.ReadU8() != 0;
    c.exposure_min = r.ReadF32();
    c.exposure_max = r.ReadF32();
    c.adaptation_speed_up = r.ReadF32();
    c.adaptation_speed_down = r.ReadF32();
    c.exposure_compensation = r.ReadF32();
    c.color_lut_intensity = r.ReadF32();
    c.vignette_enabled = r.ReadU8() != 0;
    c.vignette_intensity = r.ReadF32();
    c.vignette_radius = r.ReadF32();
    c.vignette_softness = r.ReadF32();
    c.film_grain_enabled = r.ReadU8() != 0;
    c.film_grain_intensity = r.ReadF32();
    c.film_grain_time_scale = r.ReadF32();
    c.fxaa_enabled = r.ReadU8() != 0;
    c.taa_enabled = r.ReadU8() != 0;
    c.taa_blend_factor = r.ReadF32();
    c.contact_shadow_enabled = r.ReadU8() != 0;
    c.contact_shadow_strength = r.ReadF32();
    c.contact_shadow_steps = static_cast<int>(r.ReadU32());
    c.contact_shadow_step_size = r.ReadF32();
    c.dof_enabled = r.ReadU8() != 0;
    c.dof_focus_distance = r.ReadF32();
    c.dof_focus_range = r.ReadF32();
    c.dof_bokeh_radius = r.ReadF32();
    c.motion_blur_enabled = r.ReadU8() != 0;
    c.motion_blur_intensity = r.ReadF32();
    c.motion_blur_samples = static_cast<int>(r.ReadU32());
    c.ssr_enabled = r.ReadU8() != 0;
    c.ssr_max_distance = r.ReadF32();
    c.ssr_thickness = r.ReadF32();
    c.ssr_step_size = r.ReadF32();
    c.ssr_max_steps = static_cast<int>(r.ReadU32());
    c.ssr_fade_distance = r.ReadF32();
    c.ssr_max_roughness = r.ReadF32();
    c.outline_enabled = r.ReadU8() != 0;
    c.outline_color.x = r.ReadF32(); c.outline_color.y = r.ReadF32(); c.outline_color.z = r.ReadF32();
    c.outline_thickness = r.ReadF32();
    c.outline_depth_threshold = r.ReadF32();
    c.outline_normal_threshold = r.ReadF32();
    c.light_shaft_enabled = r.ReadU8() != 0;
    c.light_shaft_color.x = r.ReadF32(); c.light_shaft_color.y = r.ReadF32(); c.light_shaft_color.z = r.ReadF32();
    c.light_shaft_density = r.ReadF32();
    c.light_shaft_weight = r.ReadF32();
    c.light_shaft_decay = r.ReadF32();
    c.light_shaft_exposure = r.ReadF32();
    c.light_shaft_intensity = r.ReadF32();
    c.light_shaft_samples = static_cast<int>(r.ReadU32());
    c.fog_enabled = r.ReadU8() != 0;
    c.fog_color.x = r.ReadF32(); c.fog_color.y = r.ReadF32(); c.fog_color.z = r.ReadF32();
    c.fog_density = r.ReadF32();
    c.fog_height_falloff = r.ReadF32();
    c.fog_height_offset = r.ReadF32();
    c.fog_start = r.ReadF32();
    c.fog_end = r.ReadF32();
    c.fog_steps = static_cast<int>(r.ReadU32());
    c.fog_sun_scatter = r.ReadF32();
}

/// Compute delta between current and baseline.
inline post_process_DeltaFlags ComputeDelta_post_process(
        const dse::PostProcessComponent& cur,
        const dse::PostProcessComponent& base) {
    post_process_DeltaFlags flags = post_process_DeltaFlags::None;
    if (cur.enabled != base.enabled) flags = flags | post_process_DeltaFlags::f_enabled;
    if (cur.bloom_enabled != base.bloom_enabled) flags = flags | post_process_DeltaFlags::f_bloom_enabled;
    if (cur.bloom_threshold != base.bloom_threshold) flags = flags | post_process_DeltaFlags::f_bloom_threshold;
    if (cur.bloom_intensity != base.bloom_intensity) flags = flags | post_process_DeltaFlags::f_bloom_intensity;
    if (cur.bloom_knee != base.bloom_knee) flags = flags | post_process_DeltaFlags::f_bloom_knee;
    if (cur.bloom_mip_weight != base.bloom_mip_weight) flags = flags | post_process_DeltaFlags::f_bloom_mip_weight;
    if (cur.color_grading_enabled != base.color_grading_enabled) flags = flags | post_process_DeltaFlags::f_color_grading_enabled;
    if (cur.exposure != base.exposure) flags = flags | post_process_DeltaFlags::f_exposure;
    if (cur.gamma != base.gamma) flags = flags | post_process_DeltaFlags::f_gamma;
    if (cur.ssao_enabled != base.ssao_enabled) flags = flags | post_process_DeltaFlags::f_ssao_enabled;
    if (cur.ssao_radius != base.ssao_radius) flags = flags | post_process_DeltaFlags::f_ssao_radius;
    if (cur.ssao_bias != base.ssao_bias) flags = flags | post_process_DeltaFlags::f_ssao_bias;
    if (cur.ssao_sample_count != base.ssao_sample_count) flags = flags | post_process_DeltaFlags::f_ssao_sample_count;
    if (cur.ssao_power != base.ssao_power) flags = flags | post_process_DeltaFlags::f_ssao_power;
    if (cur.ssao_intensity != base.ssao_intensity) flags = flags | post_process_DeltaFlags::f_ssao_intensity;
    if (cur.auto_exposure_enabled != base.auto_exposure_enabled) flags = flags | post_process_DeltaFlags::f_auto_exposure_enabled;
    if (cur.exposure_min != base.exposure_min) flags = flags | post_process_DeltaFlags::f_exposure_min;
    if (cur.exposure_max != base.exposure_max) flags = flags | post_process_DeltaFlags::f_exposure_max;
    if (cur.adaptation_speed_up != base.adaptation_speed_up) flags = flags | post_process_DeltaFlags::f_adaptation_speed_up;
    if (cur.adaptation_speed_down != base.adaptation_speed_down) flags = flags | post_process_DeltaFlags::f_adaptation_speed_down;
    if (cur.exposure_compensation != base.exposure_compensation) flags = flags | post_process_DeltaFlags::f_exposure_compensation;
    if (cur.color_lut_intensity != base.color_lut_intensity) flags = flags | post_process_DeltaFlags::f_color_lut_intensity;
    if (cur.vignette_enabled != base.vignette_enabled) flags = flags | post_process_DeltaFlags::f_vignette_enabled;
    if (cur.vignette_intensity != base.vignette_intensity) flags = flags | post_process_DeltaFlags::f_vignette_intensity;
    if (cur.vignette_radius != base.vignette_radius) flags = flags | post_process_DeltaFlags::f_vignette_radius;
    if (cur.vignette_softness != base.vignette_softness) flags = flags | post_process_DeltaFlags::f_vignette_softness;
    if (cur.film_grain_enabled != base.film_grain_enabled) flags = flags | post_process_DeltaFlags::f_film_grain_enabled;
    if (cur.film_grain_intensity != base.film_grain_intensity) flags = flags | post_process_DeltaFlags::f_film_grain_intensity;
    if (cur.film_grain_time_scale != base.film_grain_time_scale) flags = flags | post_process_DeltaFlags::f_film_grain_time_scale;
    if (cur.fxaa_enabled != base.fxaa_enabled) flags = flags | post_process_DeltaFlags::f_fxaa_enabled;
    if (cur.taa_enabled != base.taa_enabled) flags = flags | post_process_DeltaFlags::f_taa_enabled;
    if (cur.taa_blend_factor != base.taa_blend_factor) flags = flags | post_process_DeltaFlags::f_taa_blend_factor;
    if (cur.contact_shadow_enabled != base.contact_shadow_enabled) flags = flags | post_process_DeltaFlags::f_contact_shadow_enabled;
    if (cur.contact_shadow_strength != base.contact_shadow_strength) flags = flags | post_process_DeltaFlags::f_contact_shadow_strength;
    if (cur.contact_shadow_steps != base.contact_shadow_steps) flags = flags | post_process_DeltaFlags::f_contact_shadow_steps;
    if (cur.contact_shadow_step_size != base.contact_shadow_step_size) flags = flags | post_process_DeltaFlags::f_contact_shadow_step_size;
    if (cur.dof_enabled != base.dof_enabled) flags = flags | post_process_DeltaFlags::f_dof_enabled;
    if (cur.dof_focus_distance != base.dof_focus_distance) flags = flags | post_process_DeltaFlags::f_dof_focus_distance;
    if (cur.dof_focus_range != base.dof_focus_range) flags = flags | post_process_DeltaFlags::f_dof_focus_range;
    if (cur.dof_bokeh_radius != base.dof_bokeh_radius) flags = flags | post_process_DeltaFlags::f_dof_bokeh_radius;
    if (cur.motion_blur_enabled != base.motion_blur_enabled) flags = flags | post_process_DeltaFlags::f_motion_blur_enabled;
    if (cur.motion_blur_intensity != base.motion_blur_intensity) flags = flags | post_process_DeltaFlags::f_motion_blur_intensity;
    if (cur.motion_blur_samples != base.motion_blur_samples) flags = flags | post_process_DeltaFlags::f_motion_blur_samples;
    if (cur.ssr_enabled != base.ssr_enabled) flags = flags | post_process_DeltaFlags::f_ssr_enabled;
    if (cur.ssr_max_distance != base.ssr_max_distance) flags = flags | post_process_DeltaFlags::f_ssr_max_distance;
    if (cur.ssr_thickness != base.ssr_thickness) flags = flags | post_process_DeltaFlags::f_ssr_thickness;
    if (cur.ssr_step_size != base.ssr_step_size) flags = flags | post_process_DeltaFlags::f_ssr_step_size;
    if (cur.ssr_max_steps != base.ssr_max_steps) flags = flags | post_process_DeltaFlags::f_ssr_max_steps;
    if (cur.ssr_fade_distance != base.ssr_fade_distance) flags = flags | post_process_DeltaFlags::f_ssr_fade_distance;
    if (cur.ssr_max_roughness != base.ssr_max_roughness) flags = flags | post_process_DeltaFlags::f_ssr_max_roughness;
    if (cur.outline_enabled != base.outline_enabled) flags = flags | post_process_DeltaFlags::f_outline_enabled;
    if (cur.outline_color.x != base.outline_color.x || cur.outline_color.y != base.outline_color.y || cur.outline_color.z != base.outline_color.z) flags = flags | post_process_DeltaFlags::f_outline_color;
    if (cur.outline_thickness != base.outline_thickness) flags = flags | post_process_DeltaFlags::f_outline_thickness;
    if (cur.outline_depth_threshold != base.outline_depth_threshold) flags = flags | post_process_DeltaFlags::f_outline_depth_threshold;
    if (cur.outline_normal_threshold != base.outline_normal_threshold) flags = flags | post_process_DeltaFlags::f_outline_normal_threshold;
    if (cur.light_shaft_enabled != base.light_shaft_enabled) flags = flags | post_process_DeltaFlags::f_light_shaft_enabled;
    if (cur.light_shaft_color.x != base.light_shaft_color.x || cur.light_shaft_color.y != base.light_shaft_color.y || cur.light_shaft_color.z != base.light_shaft_color.z) flags = flags | post_process_DeltaFlags::f_light_shaft_color;
    if (cur.light_shaft_density != base.light_shaft_density) flags = flags | post_process_DeltaFlags::f_light_shaft_density;
    if (cur.light_shaft_weight != base.light_shaft_weight) flags = flags | post_process_DeltaFlags::f_light_shaft_weight;
    if (cur.light_shaft_decay != base.light_shaft_decay) flags = flags | post_process_DeltaFlags::f_light_shaft_decay;
    if (cur.light_shaft_exposure != base.light_shaft_exposure) flags = flags | post_process_DeltaFlags::f_light_shaft_exposure;
    if (cur.light_shaft_intensity != base.light_shaft_intensity) flags = flags | post_process_DeltaFlags::f_light_shaft_intensity;
    if (cur.light_shaft_samples != base.light_shaft_samples) flags = flags | post_process_DeltaFlags::f_light_shaft_samples;
    if (cur.fog_enabled != base.fog_enabled) flags = flags | post_process_DeltaFlags::f_fog_enabled;
    if (cur.fog_color.x != base.fog_color.x || cur.fog_color.y != base.fog_color.y || cur.fog_color.z != base.fog_color.z) flags = flags | post_process_DeltaFlags::f_fog_color;
    if (cur.fog_density != base.fog_density) flags = flags | post_process_DeltaFlags::f_fog_density;
    if (cur.fog_height_falloff != base.fog_height_falloff) flags = flags | post_process_DeltaFlags::f_fog_height_falloff;
    if (cur.fog_height_offset != base.fog_height_offset) flags = flags | post_process_DeltaFlags::f_fog_height_offset;
    if (cur.fog_start != base.fog_start) flags = flags | post_process_DeltaFlags::f_fog_start;
    if (cur.fog_end != base.fog_end) flags = flags | post_process_DeltaFlags::f_fog_end;
    if (cur.fog_steps != base.fog_steps) flags = flags | post_process_DeltaFlags::f_fog_steps;
    if (cur.fog_sun_scatter != base.fog_sun_scatter) flags = flags | post_process_DeltaFlags::f_fog_sun_scatter;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_post_process(ByteWriter& w, const dse::PostProcessComponent& c, post_process_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, post_process_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_bloom_enabled)) { w.WriteU8(c.bloom_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_bloom_threshold)) { w.WriteF32(c.bloom_threshold); }
    if (HasFlag(flags, post_process_DeltaFlags::f_bloom_intensity)) { w.WriteF32(c.bloom_intensity); }
    if (HasFlag(flags, post_process_DeltaFlags::f_bloom_knee)) { w.WriteF32(c.bloom_knee); }
    if (HasFlag(flags, post_process_DeltaFlags::f_bloom_mip_weight)) { w.WriteF32(c.bloom_mip_weight); }
    if (HasFlag(flags, post_process_DeltaFlags::f_color_grading_enabled)) { w.WriteU8(c.color_grading_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_exposure)) { w.WriteF32(c.exposure); }
    if (HasFlag(flags, post_process_DeltaFlags::f_gamma)) { w.WriteF32(c.gamma); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_enabled)) { w.WriteU8(c.ssao_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_radius)) { w.WriteF32(c.ssao_radius); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_bias)) { w.WriteF32(c.ssao_bias); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_sample_count)) { w.WriteU32(static_cast<uint32_t>(c.ssao_sample_count)); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_power)) { w.WriteF32(c.ssao_power); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_intensity)) { w.WriteF32(c.ssao_intensity); }
    if (HasFlag(flags, post_process_DeltaFlags::f_auto_exposure_enabled)) { w.WriteU8(c.auto_exposure_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_exposure_min)) { w.WriteF32(c.exposure_min); }
    if (HasFlag(flags, post_process_DeltaFlags::f_exposure_max)) { w.WriteF32(c.exposure_max); }
    if (HasFlag(flags, post_process_DeltaFlags::f_adaptation_speed_up)) { w.WriteF32(c.adaptation_speed_up); }
    if (HasFlag(flags, post_process_DeltaFlags::f_adaptation_speed_down)) { w.WriteF32(c.adaptation_speed_down); }
    if (HasFlag(flags, post_process_DeltaFlags::f_exposure_compensation)) { w.WriteF32(c.exposure_compensation); }
    if (HasFlag(flags, post_process_DeltaFlags::f_color_lut_intensity)) { w.WriteF32(c.color_lut_intensity); }
    if (HasFlag(flags, post_process_DeltaFlags::f_vignette_enabled)) { w.WriteU8(c.vignette_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_vignette_intensity)) { w.WriteF32(c.vignette_intensity); }
    if (HasFlag(flags, post_process_DeltaFlags::f_vignette_radius)) { w.WriteF32(c.vignette_radius); }
    if (HasFlag(flags, post_process_DeltaFlags::f_vignette_softness)) { w.WriteF32(c.vignette_softness); }
    if (HasFlag(flags, post_process_DeltaFlags::f_film_grain_enabled)) { w.WriteU8(c.film_grain_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_film_grain_intensity)) { w.WriteF32(c.film_grain_intensity); }
    if (HasFlag(flags, post_process_DeltaFlags::f_film_grain_time_scale)) { w.WriteF32(c.film_grain_time_scale); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fxaa_enabled)) { w.WriteU8(c.fxaa_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_taa_enabled)) { w.WriteU8(c.taa_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_taa_blend_factor)) { w.WriteF32(c.taa_blend_factor); }
    if (HasFlag(flags, post_process_DeltaFlags::f_contact_shadow_enabled)) { w.WriteU8(c.contact_shadow_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_contact_shadow_strength)) { w.WriteF32(c.contact_shadow_strength); }
    if (HasFlag(flags, post_process_DeltaFlags::f_contact_shadow_steps)) { w.WriteU32(static_cast<uint32_t>(c.contact_shadow_steps)); }
    if (HasFlag(flags, post_process_DeltaFlags::f_contact_shadow_step_size)) { w.WriteF32(c.contact_shadow_step_size); }
    if (HasFlag(flags, post_process_DeltaFlags::f_dof_enabled)) { w.WriteU8(c.dof_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_dof_focus_distance)) { w.WriteF32(c.dof_focus_distance); }
    if (HasFlag(flags, post_process_DeltaFlags::f_dof_focus_range)) { w.WriteF32(c.dof_focus_range); }
    if (HasFlag(flags, post_process_DeltaFlags::f_dof_bokeh_radius)) { w.WriteF32(c.dof_bokeh_radius); }
    if (HasFlag(flags, post_process_DeltaFlags::f_motion_blur_enabled)) { w.WriteU8(c.motion_blur_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_motion_blur_intensity)) { w.WriteF32(c.motion_blur_intensity); }
    if (HasFlag(flags, post_process_DeltaFlags::f_motion_blur_samples)) { w.WriteU32(static_cast<uint32_t>(c.motion_blur_samples)); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_enabled)) { w.WriteU8(c.ssr_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_max_distance)) { w.WriteF32(c.ssr_max_distance); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_thickness)) { w.WriteF32(c.ssr_thickness); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_step_size)) { w.WriteF32(c.ssr_step_size); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_max_steps)) { w.WriteU32(static_cast<uint32_t>(c.ssr_max_steps)); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_fade_distance)) { w.WriteF32(c.ssr_fade_distance); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_max_roughness)) { w.WriteF32(c.ssr_max_roughness); }
    if (HasFlag(flags, post_process_DeltaFlags::f_outline_enabled)) { w.WriteU8(c.outline_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_outline_color)) { w.WriteF32(c.outline_color.x); w.WriteF32(c.outline_color.y); w.WriteF32(c.outline_color.z); }
    if (HasFlag(flags, post_process_DeltaFlags::f_outline_thickness)) { w.WriteF32(c.outline_thickness); }
    if (HasFlag(flags, post_process_DeltaFlags::f_outline_depth_threshold)) { w.WriteF32(c.outline_depth_threshold); }
    if (HasFlag(flags, post_process_DeltaFlags::f_outline_normal_threshold)) { w.WriteF32(c.outline_normal_threshold); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_enabled)) { w.WriteU8(c.light_shaft_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_color)) { w.WriteF32(c.light_shaft_color.x); w.WriteF32(c.light_shaft_color.y); w.WriteF32(c.light_shaft_color.z); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_density)) { w.WriteF32(c.light_shaft_density); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_weight)) { w.WriteF32(c.light_shaft_weight); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_decay)) { w.WriteF32(c.light_shaft_decay); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_exposure)) { w.WriteF32(c.light_shaft_exposure); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_intensity)) { w.WriteF32(c.light_shaft_intensity); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_samples)) { w.WriteU32(static_cast<uint32_t>(c.light_shaft_samples)); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_enabled)) { w.WriteU8(c.fog_enabled ? 1 : 0); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_color)) { w.WriteF32(c.fog_color.x); w.WriteF32(c.fog_color.y); w.WriteF32(c.fog_color.z); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_density)) { w.WriteF32(c.fog_density); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_height_falloff)) { w.WriteF32(c.fog_height_falloff); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_height_offset)) { w.WriteF32(c.fog_height_offset); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_start)) { w.WriteF32(c.fog_start); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_end)) { w.WriteF32(c.fog_end); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_steps)) { w.WriteU32(static_cast<uint32_t>(c.fog_steps)); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_sun_scatter)) { w.WriteF32(c.fog_sun_scatter); }
}

/// Read delta and apply to component.
inline void ReadDelta_post_process(ByteReader& r, dse::PostProcessComponent& c) {
    auto flags = static_cast<post_process_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, post_process_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_bloom_enabled)) { c.bloom_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_bloom_threshold)) { c.bloom_threshold = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_bloom_intensity)) { c.bloom_intensity = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_bloom_knee)) { c.bloom_knee = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_bloom_mip_weight)) { c.bloom_mip_weight = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_color_grading_enabled)) { c.color_grading_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_exposure)) { c.exposure = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_gamma)) { c.gamma = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_enabled)) { c.ssao_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_radius)) { c.ssao_radius = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_bias)) { c.ssao_bias = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_sample_count)) { c.ssao_sample_count = static_cast<int>(r.ReadU32()); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_power)) { c.ssao_power = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssao_intensity)) { c.ssao_intensity = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_auto_exposure_enabled)) { c.auto_exposure_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_exposure_min)) { c.exposure_min = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_exposure_max)) { c.exposure_max = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_adaptation_speed_up)) { c.adaptation_speed_up = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_adaptation_speed_down)) { c.adaptation_speed_down = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_exposure_compensation)) { c.exposure_compensation = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_color_lut_intensity)) { c.color_lut_intensity = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_vignette_enabled)) { c.vignette_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_vignette_intensity)) { c.vignette_intensity = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_vignette_radius)) { c.vignette_radius = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_vignette_softness)) { c.vignette_softness = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_film_grain_enabled)) { c.film_grain_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_film_grain_intensity)) { c.film_grain_intensity = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_film_grain_time_scale)) { c.film_grain_time_scale = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fxaa_enabled)) { c.fxaa_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_taa_enabled)) { c.taa_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_taa_blend_factor)) { c.taa_blend_factor = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_contact_shadow_enabled)) { c.contact_shadow_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_contact_shadow_strength)) { c.contact_shadow_strength = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_contact_shadow_steps)) { c.contact_shadow_steps = static_cast<int>(r.ReadU32()); }
    if (HasFlag(flags, post_process_DeltaFlags::f_contact_shadow_step_size)) { c.contact_shadow_step_size = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_dof_enabled)) { c.dof_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_dof_focus_distance)) { c.dof_focus_distance = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_dof_focus_range)) { c.dof_focus_range = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_dof_bokeh_radius)) { c.dof_bokeh_radius = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_motion_blur_enabled)) { c.motion_blur_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_motion_blur_intensity)) { c.motion_blur_intensity = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_motion_blur_samples)) { c.motion_blur_samples = static_cast<int>(r.ReadU32()); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_enabled)) { c.ssr_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_max_distance)) { c.ssr_max_distance = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_thickness)) { c.ssr_thickness = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_step_size)) { c.ssr_step_size = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_max_steps)) { c.ssr_max_steps = static_cast<int>(r.ReadU32()); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_fade_distance)) { c.ssr_fade_distance = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_ssr_max_roughness)) { c.ssr_max_roughness = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_outline_enabled)) { c.outline_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_outline_color)) { c.outline_color.x = r.ReadF32(); c.outline_color.y = r.ReadF32(); c.outline_color.z = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_outline_thickness)) { c.outline_thickness = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_outline_depth_threshold)) { c.outline_depth_threshold = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_outline_normal_threshold)) { c.outline_normal_threshold = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_enabled)) { c.light_shaft_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_color)) { c.light_shaft_color.x = r.ReadF32(); c.light_shaft_color.y = r.ReadF32(); c.light_shaft_color.z = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_density)) { c.light_shaft_density = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_weight)) { c.light_shaft_weight = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_decay)) { c.light_shaft_decay = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_exposure)) { c.light_shaft_exposure = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_intensity)) { c.light_shaft_intensity = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_light_shaft_samples)) { c.light_shaft_samples = static_cast<int>(r.ReadU32()); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_enabled)) { c.fog_enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_color)) { c.fog_color.x = r.ReadF32(); c.fog_color.y = r.ReadF32(); c.fog_color.z = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_density)) { c.fog_density = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_height_falloff)) { c.fog_height_falloff = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_height_offset)) { c.fog_height_offset = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_start)) { c.fog_start = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_end)) { c.fog_end = r.ReadF32(); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_steps)) { c.fog_steps = static_cast<int>(r.ReadU32()); }
    if (HasFlag(flags, post_process_DeltaFlags::f_fog_sun_scatter)) { c.fog_sun_scatter = r.ReadF32(); }
}
// ═══════════════════════════════════════════════════════════════════════════════
// Animator3DComponent (prefix: animator3d)
// ═══════════════════════════════════════════════════════════════════════════════

/// Delta flags — one bit per replicable field.
enum class animator3d_DeltaFlags : uint32_t {
    None = 0,
    f_enabled = (1u << 0),
    f_speed = (1u << 1),
    f_loop = (1u << 2),
    f_use_anim_tree = (1u << 3),
    f_blend_parameter_value = (1u << 4),
    All = 0x1fu
};

inline animator3d_DeltaFlags operator|(animator3d_DeltaFlags a, animator3d_DeltaFlags b) {
    return static_cast<animator3d_DeltaFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}
inline bool HasFlag(animator3d_DeltaFlags flags, animator3d_DeltaFlags bit) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(bit)) != 0;
}

/// Full snapshot write.
inline void WriteSnapshot_animator3d(ByteWriter& w, const dse::Animator3DComponent& c) {
    w.WriteU8(c.enabled ? 1 : 0);
    w.WriteF32(c.speed);
    w.WriteU8(c.loop ? 1 : 0);
    w.WriteU8(c.use_anim_tree ? 1 : 0);
    w.WriteF32(c.blend_parameter_value);
}

/// Full snapshot read.
inline void ReadSnapshot_animator3d(ByteReader& r, dse::Animator3DComponent& c) {
    c.enabled = r.ReadU8() != 0;
    c.speed = r.ReadF32();
    c.loop = r.ReadU8() != 0;
    c.use_anim_tree = r.ReadU8() != 0;
    c.blend_parameter_value = r.ReadF32();
}

/// Compute delta between current and baseline.
inline animator3d_DeltaFlags ComputeDelta_animator3d(
        const dse::Animator3DComponent& cur,
        const dse::Animator3DComponent& base) {
    animator3d_DeltaFlags flags = animator3d_DeltaFlags::None;
    if (cur.enabled != base.enabled) flags = flags | animator3d_DeltaFlags::f_enabled;
    if (cur.speed != base.speed) flags = flags | animator3d_DeltaFlags::f_speed;
    if (cur.loop != base.loop) flags = flags | animator3d_DeltaFlags::f_loop;
    if (cur.use_anim_tree != base.use_anim_tree) flags = flags | animator3d_DeltaFlags::f_use_anim_tree;
    if (cur.blend_parameter_value != base.blend_parameter_value) flags = flags | animator3d_DeltaFlags::f_blend_parameter_value;
    return flags;
}

/// Write only changed fields (delta).
inline void WriteDelta_animator3d(ByteWriter& w, const dse::Animator3DComponent& c, animator3d_DeltaFlags flags) {
    w.WriteU32(static_cast<uint32_t>(flags));
    if (HasFlag(flags, animator3d_DeltaFlags::f_enabled)) { w.WriteU8(c.enabled ? 1 : 0); }
    if (HasFlag(flags, animator3d_DeltaFlags::f_speed)) { w.WriteF32(c.speed); }
    if (HasFlag(flags, animator3d_DeltaFlags::f_loop)) { w.WriteU8(c.loop ? 1 : 0); }
    if (HasFlag(flags, animator3d_DeltaFlags::f_use_anim_tree)) { w.WriteU8(c.use_anim_tree ? 1 : 0); }
    if (HasFlag(flags, animator3d_DeltaFlags::f_blend_parameter_value)) { w.WriteF32(c.blend_parameter_value); }
}

/// Read delta and apply to component.
inline void ReadDelta_animator3d(ByteReader& r, dse::Animator3DComponent& c) {
    auto flags = static_cast<animator3d_DeltaFlags>(r.ReadU32());
    if (HasFlag(flags, animator3d_DeltaFlags::f_enabled)) { c.enabled = r.ReadU8() != 0; }
    if (HasFlag(flags, animator3d_DeltaFlags::f_speed)) { c.speed = r.ReadF32(); }
    if (HasFlag(flags, animator3d_DeltaFlags::f_loop)) { c.loop = r.ReadU8() != 0; }
    if (HasFlag(flags, animator3d_DeltaFlags::f_use_anim_tree)) { c.use_anim_tree = r.ReadU8() != 0; }
    if (HasFlag(flags, animator3d_DeltaFlags::f_blend_parameter_value)) { c.blend_parameter_value = r.ReadF32(); }
}

// ─── Archetype Registry ──────────────────────────────────────────────────────

enum class ReplArchetypeId : uint16_t {
    transform = 0,
    camera3d = 1,
    mesh_renderer = 2,
    dir_light = 3,
    point_light = 4,
    spot_light = 5,
    sky_light = 6,
    tree = 7,
    terrain_tile = 8,
    dyn_obstacle = 9,
    navmesh_rebake = 10,
    post_process = 11,
    animator3d = 12,
    Count
};

} // namespace dse::net::repl

#endif // DSE_NET_REPLICATION_REPL_CODEC_GEN_H
