// <auto-generated>
//   来源：tools/codegen/binding_defs.json — 勿手动修改
// </auto-generated>

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace DSEngine {

/// <summary>Mono InternalCall 声明 — 对应 dse_api.h C ABI</summary>
internal static class Native {

    // ---- TransformComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_transform_get_position(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_transform_set_position(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_transform_get_rotation(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_transform_set_rotation(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_transform_get_scale(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_transform_set_scale(uint e, float x, float y, float z);


    // ---- Camera3DComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_camera3d_get_fov(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_camera3d_set_fov(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_camera3d_get_near_clip(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_camera3d_set_near_clip(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_camera3d_get_far_clip(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_camera3d_set_far_clip(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_camera3d_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_camera3d_set_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_camera3d_get_priority(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_camera3d_set_priority(uint e, int v);


    // ---- MeshRendererComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_mesh_renderer_get_color(uint e, out float x, out float y, out float z, out float w);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_mesh_renderer_set_color(uint e, float x, float y, float z, float w);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_mesh_renderer_get_visible(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_mesh_renderer_set_visible(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_mesh_renderer_get_metallic(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_mesh_renderer_set_metallic(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_mesh_renderer_get_roughness(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_mesh_renderer_set_roughness(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_mesh_renderer_get_emissive(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_mesh_renderer_set_emissive(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_mesh_renderer_get_receive_shadow(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_mesh_renderer_set_receive_shadow(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_mesh_renderer_set_mesh_path(uint e,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_mesh_renderer_get_mesh_path(uint e, byte[] buf, int buf_size);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_mesh_renderer_set_shader_variant(uint e,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_mesh_renderer_get_shader_variant(uint e, byte[] buf, int buf_size);


    // ---- DirectionalLight3DComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dir_light_get_direction(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dir_light_set_direction(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dir_light_get_color(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dir_light_set_color(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_dir_light_get_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dir_light_set_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_dir_light_get_ambient_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dir_light_set_ambient_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_dir_light_get_cast_shadow(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dir_light_set_cast_shadow(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_dir_light_get_shadow_strength(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dir_light_set_shadow_strength(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_dir_light_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dir_light_set_enabled(uint e, int v);


    // ---- PointLightComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_point_light_get_color(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_point_light_set_color(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_point_light_get_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_point_light_set_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_point_light_get_radius(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_point_light_set_radius(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_point_light_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_point_light_set_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_point_light_get_cast_shadow(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_point_light_set_cast_shadow(uint e, int v);


    // ---- SpotLightComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_spot_light_get_color(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_spot_light_set_color(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_spot_light_get_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_spot_light_set_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_spot_light_get_radius(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_spot_light_set_radius(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_spot_light_get_inner_cone_angle(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_spot_light_set_inner_cone_angle(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_spot_light_get_outer_cone_angle(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_spot_light_set_outer_cone_angle(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_spot_light_get_direction(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_spot_light_set_direction(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_spot_light_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_spot_light_set_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_spot_light_get_cast_shadow(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_spot_light_set_cast_shadow(uint e, int v);


    // ---- SkyLightComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_sky_light_get_up_color(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_sky_light_set_up_color(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_sky_light_get_down_color(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_sky_light_set_down_color(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_sky_light_get_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_sky_light_set_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_sky_light_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_sky_light_set_enabled(uint e, int v);


    // ---- TreeComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_tree_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_density(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_density(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_spawn_radius(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_spawn_radius(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_chunk_size(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_chunk_size(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_min_scale(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_min_scale(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_max_scale(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_max_scale(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_lod1_distance(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_lod1_distance(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_cull_distance(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_cull_distance(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_wind_strength(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_wind_strength(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_wind_speed(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_wind_speed(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_tree_get_cast_shadow(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_cast_shadow(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_shadow_distance(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_shadow_distance(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_tree_get_seed(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_seed(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_height_variation(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_height_variation(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_tree_get_random_rotation(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_random_rotation(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_tree_get_billboard_distance(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_billboard_distance(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_mesh_path(uint e,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_tree_get_mesh_path(uint e, byte[] buf, int buf_size);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_lod1_mesh_path(uint e,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_tree_get_lod1_mesh_path(uint e, byte[] buf, int buf_size);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_tree_set_billboard_texture_path(uint e,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_tree_get_billboard_texture_path(uint e, byte[] buf, int buf_size);


    // ---- TerrainTileManagerComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_terrain_tile_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_terrain_tile_set_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_terrain_tile_get_tile_world_size(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_terrain_tile_set_tile_world_size(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_terrain_tile_get_tile_resolution(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_terrain_tile_set_tile_resolution(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_terrain_tile_get_max_height(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_terrain_tile_set_max_height(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_terrain_tile_get_load_radius(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_terrain_tile_set_load_radius(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_terrain_tile_get_unload_radius(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_terrain_tile_set_unload_radius(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_terrain_tile_get_use_procedural(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_terrain_tile_set_use_procedural(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_terrain_tile_get_procedural_base_height(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_terrain_tile_set_procedural_base_height(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_terrain_tile_get_max_lod_levels(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_terrain_tile_set_max_lod_levels(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_terrain_tile_get_lod_distance_factor(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_terrain_tile_set_lod_distance_factor(uint e, float v);


    // ---- DynamicObstacleComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_dyn_obstacle_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dyn_obstacle_set_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_dyn_obstacle_get_shape(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dyn_obstacle_set_shape(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dyn_obstacle_get_box_extents(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dyn_obstacle_set_box_extents(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_dyn_obstacle_get_cylinder_radius(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dyn_obstacle_set_cylinder_radius(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_dyn_obstacle_get_cylinder_height(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_dyn_obstacle_set_cylinder_height(uint e, float v);


    // ---- NavMeshAutoRebakeComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_navmesh_rebake_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_navmesh_rebake_get_tile_size(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_tile_size(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_navmesh_rebake_get_rebake_cooldown(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_rebake_cooldown(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_navmesh_rebake_get_collect_terrain(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_collect_terrain(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_navmesh_rebake_get_collect_mesh_renderers(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_collect_mesh_renderers(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_navmesh_rebake_get_agent_height(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_agent_height(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_navmesh_rebake_get_agent_radius(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_agent_radius(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_navmesh_rebake_get_agent_max_climb(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_agent_max_climb(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_navmesh_rebake_get_agent_max_slope(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_agent_max_slope(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_navmesh_rebake_get_cell_size(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_cell_size(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_navmesh_rebake_get_cell_height(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_navmesh_rebake_set_cell_height(uint e, float v);


    // ---- PostProcessComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_bloom_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_bloom_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_bloom_threshold(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_bloom_threshold(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_bloom_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_bloom_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_bloom_knee(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_bloom_knee(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_bloom_mip_weight(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_bloom_mip_weight(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_color_grading_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_color_grading_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_exposure(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_exposure(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_gamma(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_gamma(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_ssao_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssao_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_ssao_radius(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssao_radius(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_ssao_bias(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssao_bias(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_ssao_sample_count(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssao_sample_count(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_ssao_power(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssao_power(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_ssao_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssao_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_auto_exposure_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_auto_exposure_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_exposure_min(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_exposure_min(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_exposure_max(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_exposure_max(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_adaptation_speed_up(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_adaptation_speed_up(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_adaptation_speed_down(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_adaptation_speed_down(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_exposure_compensation(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_exposure_compensation(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_color_lut_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_color_lut_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_vignette_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_vignette_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_vignette_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_vignette_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_vignette_radius(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_vignette_radius(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_vignette_softness(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_vignette_softness(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_film_grain_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_film_grain_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_film_grain_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_film_grain_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_film_grain_time_scale(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_film_grain_time_scale(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_fxaa_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_fxaa_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_taa_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_taa_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_taa_blend_factor(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_taa_blend_factor(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_contact_shadow_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_contact_shadow_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_contact_shadow_strength(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_contact_shadow_strength(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_contact_shadow_steps(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_contact_shadow_steps(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_contact_shadow_step_size(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_contact_shadow_step_size(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_dof_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_dof_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_dof_focus_distance(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_dof_focus_distance(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_dof_focus_range(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_dof_focus_range(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_dof_bokeh_radius(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_dof_bokeh_radius(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_motion_blur_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_motion_blur_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_motion_blur_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_motion_blur_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_motion_blur_samples(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_motion_blur_samples(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_ssr_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssr_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_ssr_max_distance(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssr_max_distance(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_ssr_thickness(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssr_thickness(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_ssr_step_size(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssr_step_size(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_ssr_max_steps(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssr_max_steps(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_ssr_fade_distance(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssr_fade_distance(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_ssr_max_roughness(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_ssr_max_roughness(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_outline_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_outline_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_get_outline_color(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_outline_color(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_outline_thickness(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_outline_thickness(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_outline_depth_threshold(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_outline_depth_threshold(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_outline_normal_threshold(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_outline_normal_threshold(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_light_shaft_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_light_shaft_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_get_light_shaft_color(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_light_shaft_color(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_light_shaft_density(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_light_shaft_density(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_light_shaft_weight(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_light_shaft_weight(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_light_shaft_decay(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_light_shaft_decay(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_light_shaft_exposure(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_light_shaft_exposure(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_light_shaft_intensity(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_light_shaft_intensity(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_light_shaft_samples(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_light_shaft_samples(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_fog_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_fog_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_get_fog_color(uint e, out float x, out float y, out float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_fog_color(uint e, float x, float y, float z);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_fog_density(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_fog_density(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_fog_height_falloff(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_fog_height_falloff(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_fog_height_offset(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_fog_height_offset(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_fog_start(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_fog_start(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_fog_end(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_fog_end(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_post_process_get_fog_steps(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_fog_steps(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_post_process_get_fog_sun_scatter(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_post_process_set_fog_sun_scatter(uint e, float v);


    // ---- Animator3DComponent ----
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_animator3d_get_enabled(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_animator3d_set_enabled(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_animator3d_set_danim_path(uint e,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_animator3d_get_danim_path(uint e, byte[] buf, int buf_size);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_animator3d_set_dskel_path(uint e,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_animator3d_get_dskel_path(uint e, byte[] buf, int buf_size);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_animator3d_get_speed(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_animator3d_set_speed(uint e, float v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_animator3d_get_loop(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_animator3d_set_loop(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_animator3d_get_use_anim_tree(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_animator3d_set_use_anim_tree(uint e, int v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_animator3d_set_blend_parameter(uint e,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string v);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern int dse_animator3d_get_blend_parameter(uint e, byte[] buf, int buf_size);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern float dse_animator3d_get_blend_parameter_value(uint e);

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern void dse_animator3d_set_blend_parameter_value(uint e, float v);


} // class Native

} // namespace DSEngine
