#!/usr/bin/env python3
"""Regenerate templates/topdown_3d/scripts/cjk_chars.lua.

The generated module contains every non-ASCII character appearing in the
topdown_3d Lua scripts.  It is fed to dse.font.load_text so the CJK SDF atlas
only contains glyphs that are actually used by the template.
"""
from __future__ import annotations

from pathlib import Path


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    script_dir = repo_root / "templates" / "topdown_3d" / "scripts"
    output = script_dir / "cjk_chars.lua"

    chars: set[str] = set()
    for lua_path in sorted(script_dir.glob("*.lua")):
        if lua_path.name == "cjk_chars.lua":
            continue
        for ch in lua_path.read_text(encoding="utf-8"):
            cp = ord(ch)
            if cp > 0x7F and cp != 0xFEFF:
                chars.add(ch)

    ordered = "".join(sorted(chars, key=ord))
    escaped = (
        ordered.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    output.write_text(
        "-- Auto-generated by tools/audit/generate_topdown_cjk_chars.py.\n"
        "-- Non-ASCII character set passed to dse.font.load_text for the CJK SDF atlas.\n"
        'return "' + escaped + '"\n',
        encoding="utf-8",
    )
    print(f"wrote {output} ({len(ordered)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
