#!/usr/bin/env python3
"""Reconcile "TEST macros written in source" against "cases that actually run".

Why this exists
---------------
The engine README/status material has quoted the raw count of `TEST(...)` macros
(e.g. 4688) as if it were the number of tests that run.  It is not:

  * a suite wrapped in `#if` (physics backend, allocator backend, ...) writes
    macros that are simply not compiled in the current configuration;
  * a suite generated by a macro (e.g. DEFINE_..._TEST) never appears as a
    literal `TEST(` and is invisible to a text scan, yet it does run.

Neither is a bug by itself, but quoting the wrong one silently overstates
coverage.  This tool prints the reconciliation and, more importantly, FAILS when
a suite that is *not* behind any preprocessor guard is missing from every
binary -- that would mean a test was dropped without explanation.

Usage
-----
    python tools/audit/test_inventory.py [--bin-dir bin] [--json out.json]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

TEST_MACRO = re.compile(
    r"^\s*TEST(?:_F)?\s*\(\s*([A-Za-z0-9_]+)\s*,\s*([^\s,)]+)\s*\)", re.M
)
GUARD = re.compile(r"^\s*#\s*(?:if|ifdef|ifndef|elif)\b[^\n]*", re.M)

BINARIES = [
    ("unit", "dse_gtest_unit_tests.exe"),
    ("integration", "dse_gtest_integration_tests.exe"),
    ("smoke", "dse_gtest_smoke_tests.exe"),
]


def find_binary(bin_dir: Path, name: str) -> Path | None:
    direct = bin_dir / name
    if direct.is_file():
        return direct
    hits = sorted(bin_dir.rglob(name))
    return hits[0] if hits else None


def list_suites(exe: Path) -> tuple[set, int]:
    """Return (suite names, case count) the binary advertises."""
    proc = subprocess.run(
        [str(exe), "--gtest_list_tests"],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    suites, cases, current = set(), 0, ""
    for line in proc.stdout.splitlines():
        if not line.strip():
            continue
        if line.startswith("  "):
            if current:
                suites.add(current)
            cases += 1
        else:
            current = line.strip().rstrip(".")
    if current:
        suites.add(current)
    return suites, cases


def scan_sources() -> dict:
    """suite -> {file, cases, guard} for every literal TEST macro under tests/gtest."""
    found: dict = {}
    for path in sorted((ROOT / "tests" / "gtest").rglob("*.cpp")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in TEST_MACRO.finditer(text):
            suite, case = match.group(1), match.group(2)
            guards = GUARD.findall(text)
            rel = path.relative_to(ROOT).as_posix()
            entry = found.setdefault(suite, {"file": rel, "cases": [], "guard": guards[0].strip() if guards else ""})
            entry["cases"].append(f"{suite}.{case}")
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--bin-dir", default="bin", help="directory that holds the gtest executables")
    parser.add_argument("--json", dest="json_out", default=None)
    args = parser.parse_args()

    bin_dir = (ROOT / args.bin_dir) if not Path(args.bin_dir).is_absolute() else Path(args.bin_dir)
    if not bin_dir.is_dir():
        print(f"test-inventory: bin dir not found: {bin_dir}", file=sys.stderr)
        return 2

    sources = scan_sources()
    source_macros = sum(len(v["cases"]) for v in sources.values())

    report: dict = {"source_suites": len(sources), "source_macros": source_macros, "binaries": []}
    all_listed: set = set()

    for label, exe_name in BINARIES:
        exe = find_binary(bin_dir, exe_name)
        if exe is None:
            print(f"test-inventory: {exe_name} not found under {bin_dir}", file=sys.stderr)
            return 2
        suites, cases = list_suites(exe)
        all_listed |= suites
        report["binaries"].append({"label": label, "exe": exe.name, "listed_cases": cases, "listed_suites": len(suites)})
        print(f"test-inventory: {label:<12} binary lists {cases:>5} cases in {len(suites):>3} suites")

    total_listed = sum(b["listed_cases"] for b in report["binaries"])
    not_built = {s: v for s, v in sources.items() if s not in all_listed}
    generated = sorted(s for s in all_listed if s not in sources)

    unexplained = {s: v for s, v in not_built.items() if not v["guard"]}

    print(f"test-inventory: source scan sees {source_macros} literal TEST macros in {len(sources)} suites")
    print(f"test-inventory: binaries advertise {total_listed} cases total")

    guarded_cases = sum(len(v["cases"]) for v in not_built.values() if v["guard"])
    if not_built:
        print(f"test-inventory: not compiled in this configuration: {len(not_built)} suites / {guarded_cases} cases")
        for suite, info in sorted(not_built.items()):
            reason = info["guard"] if info["guard"] else "NO PREPROCESSOR GUARD"
            print(f"test-inventory:   - {suite:<38} {reason}")
    if generated:
        print(f"test-inventory: generated suites (macro-built, invisible to the text scan): {len(generated)}")
        for suite in generated[:10]:
            print(f"test-inventory:   + {suite}")

    # Close the books: literal macros minus compiled-out cases should equal the
    # advertised total; a positive remainder is cases produced by generator macros
    # (which never appear as a literal TEST( in the text scan).
    expected_from_literals = source_macros - guarded_cases
    generated_cases = total_listed - expected_from_literals
    print(f"test-inventory: arithmetic: {source_macros} literal macros - {guarded_cases} compiled out "
          f"= {expected_from_literals} expected, binaries advertise {total_listed} "
          f"(+{generated_cases} from generator macros)")

    report["not_compiled_suites"] = sorted(not_built)
    report["guarded_cases"] = guarded_cases
    report["generated_suites"] = generated
    report["generated_cases"] = generated_cases
    report["unexplained_suites"] = sorted(unexplained)
    report["total_listed_cases"] = total_listed

    if args.json_out:
        out = Path(args.json_out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"test-inventory: wrote {out}")

    if unexplained:
        print("test-inventory: FAILED - these suites exist in source with no preprocessor guard "
              "but are in no binary (a test was dropped without explanation):", file=sys.stderr)
        for suite, info in sorted(unexplained.items()):
            print(f"test-inventory:   ! {suite} ({info['file']})", file=sys.stderr)
        return 1

    print(f"test-inventory: OK - every unguarded source suite is present in a binary; "
          f"{total_listed} cases are the number to quote, not {source_macros}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
