#include "catch/catch.hpp"
#include "engine/ecs/components_3d.h"

TEST_CASE("Given_MeshRendererComponent_When_AssigningMaterialFields_Then_PbrAndSelectionFieldsArePreserved", "[engine][unit][3d][material]") {
    dse::MeshRendererComponent mesh;
    mesh.mesh_path = "assets/meshes/test.fbx";
    mesh.material_instance_id = 42;
    mesh.shader_variant = "MESH_PBR";
    mesh.color = glm::vec4(0.8f, 0.7f, 0.6f, 1.0f);
    mesh.emissive = glm::vec3(0.1f, 0.2f, 0.3f);
    mesh.metallic = 0.5f;
    mesh.roughness = 0.25f;
    mesh.ao = 0.9f;
    mesh.normal_strength = 1.5f;
    mesh.albedo_texture_handle = 101;
    mesh.normal_texture_handle = 102;
    mesh.metallic_roughness_texture_handle = 103;
    mesh.emissive_texture_handle = 104;
    mesh.occlusion_texture_handle = 105;
    mesh.receive_shadow = false;
    mesh.visible = true;
    mesh.material_alpha_cutoff = 0.33f;
    mesh.material_alpha_test = true;
    mesh.material_double_sided = true;
    mesh.sorting_layer = 2;
    mesh.order_in_layer = 7;
    mesh.material_data_source = dse::MeshRendererComponent::MaterialDataSource::MaterialInstance;

    REQUIRE(mesh.material_instance_id == 42);
    REQUIRE(mesh.shader_variant == "MESH_PBR");
    REQUIRE(mesh.color.r == Approx(0.8f));
    REQUIRE(mesh.emissive.z == Approx(0.3f));
    REQUIRE(mesh.metallic == Approx(0.5f));
    REQUIRE(mesh.roughness == Approx(0.25f));
    REQUIRE(mesh.ao == Approx(0.9f));
    REQUIRE(mesh.normal_strength == Approx(1.5f));
    REQUIRE(mesh.albedo_texture_handle == 101);
    REQUIRE(mesh.normal_texture_handle == 102);
    REQUIRE(mesh.metallic_roughness_texture_handle == 103);
    REQUIRE(mesh.emissive_texture_handle == 104);
    REQUIRE(mesh.occlusion_texture_handle == 105);
    REQUIRE(mesh.receive_shadow == false);
    REQUIRE(mesh.visible == true);
    REQUIRE(mesh.material_alpha_cutoff == Approx(0.33f));
    REQUIRE(mesh.material_alpha_test == true);
    REQUIRE(mesh.material_double_sided == true);
    REQUIRE(mesh.sorting_layer == 2);
    REQUIRE(mesh.order_in_layer == 7);
    REQUIRE(mesh.material_data_source == dse::MeshRendererComponent::MaterialDataSource::MaterialInstance);
}

TEST_CASE("Given_MeshRendererComponent_When_CopyingMaterialFields_Then_ComponentFieldsStayConsistent", "[engine][unit][3d][material]") {
    dse::MeshRendererComponent source;
    source.material_instance_id = 7;
    source.shader_variant = "MESH_UNLIT";
    source.color = glm::vec4(0.2f, 0.3f, 0.4f, 1.0f);
    source.emissive = glm::vec3(1.0f, 0.0f, 0.0f);
    source.metallic = 0.8f;
    source.roughness = 0.1f;
    source.ao = 0.6f;
    source.normal_strength = 2.0f;
    source.albedo_texture_handle = 201;
    source.normal_texture_handle = 202;
    source.metallic_roughness_texture_handle = 203;
    source.emissive_texture_handle = 204;
    source.occlusion_texture_handle = 205;
    source.receive_shadow = false;
    source.visible = false;
    source.material_alpha_cutoff = 0.66f;
    source.material_alpha_test = true;
    source.material_double_sided = true;
    source.sorting_layer = 4;
    source.order_in_layer = 9;
    source.material_data_source = dse::MeshRendererComponent::MaterialDataSource::MaterialInstance;

    dse::MeshRendererComponent mesh;
    mesh.material_instance_id = source.material_instance_id;
    mesh.shader_variant = source.shader_variant;
    mesh.color = source.color;
    mesh.emissive = source.emissive;
    mesh.metallic = source.metallic;
    mesh.roughness = source.roughness;
    mesh.ao = source.ao;
    mesh.normal_strength = source.normal_strength;
    mesh.albedo_texture_handle = source.albedo_texture_handle;
    mesh.normal_texture_handle = source.normal_texture_handle;
    mesh.metallic_roughness_texture_handle = source.metallic_roughness_texture_handle;
    mesh.emissive_texture_handle = source.emissive_texture_handle;
    mesh.occlusion_texture_handle = source.occlusion_texture_handle;
    mesh.receive_shadow = source.receive_shadow;
    mesh.visible = source.visible;
    mesh.material_alpha_cutoff = source.material_alpha_cutoff;
    mesh.material_alpha_test = source.material_alpha_test;
    mesh.material_double_sided = source.material_double_sided;
    mesh.sorting_layer = source.sorting_layer;
    mesh.order_in_layer = source.order_in_layer;
    mesh.material_data_source = source.material_data_source;

    REQUIRE(mesh.material_instance_id == 7);
    REQUIRE(mesh.shader_variant == "MESH_UNLIT");
    REQUIRE(mesh.color.g == Approx(0.3f));
    REQUIRE(mesh.emissive.x == Approx(1.0f));
    REQUIRE(mesh.metallic == Approx(0.8f));
    REQUIRE(mesh.roughness == Approx(0.1f));
    REQUIRE(mesh.ao == Approx(0.6f));
    REQUIRE(mesh.normal_strength == Approx(2.0f));
    REQUIRE(mesh.albedo_texture_handle == 201);
    REQUIRE(mesh.normal_texture_handle == 202);
    REQUIRE(mesh.metallic_roughness_texture_handle == 203);
    REQUIRE(mesh.emissive_texture_handle == 204);
    REQUIRE(mesh.occlusion_texture_handle == 205);
    REQUIRE(mesh.receive_shadow == false);
    REQUIRE(mesh.visible == false);
    REQUIRE(mesh.material_alpha_cutoff == Approx(0.66f));
    REQUIRE(mesh.material_alpha_test == true);
    REQUIRE(mesh.material_double_sided == true);
    REQUIRE(mesh.sorting_layer == 4);
    REQUIRE(mesh.order_in_layer == 9);
    REQUIRE(mesh.material_data_source == dse::MeshRendererComponent::MaterialDataSource::MaterialInstance);
}
