local M = {}
M._meta = { name = "3D Environment Query System", category = "ai" }

local ecs = dse.ecs
local state = { elapsed = 0 }

function M.Setup(config)
    -- Camera
    local cam = ecs.create_entity()
    ecs.add_transform(cam, 0, 20, -20, 1, 1, 1)
    ecs.add_camera3d(cam, 60.0, 0.1, 100.0)

    -- Ground
    local ground = ecs.create_entity()
    ecs.add_transform(ground, 0, 0, 0, 50, 0.1, 50)
    ecs.add_mesh_renderer(ground, "cube")

    -- AI agent using EQS to find positions
    local agent = ecs.create_entity()
    ecs.add_transform(agent, 0, 1, 0, 1, 2, 1)
    ecs.add_mesh_renderer(agent, "capsule")
    dse.ai.add_eqs(agent)
    dse.ai.eqs_set_query_radius(agent, 15.0)
    dse.ai.eqs_set_query_spacing(agent, 3.0)
    state.agent = agent

    -- Obstacles that affect EQS queries
    local obstacles = {}
    for i = 1, 12 do
        local obs = ecs.create_entity()
        local x = math.cos(i * 0.52) * (4.0 + i * 1.0)
        local z = math.sin(i * 0.52) * (4.0 + i * 1.0)
        local h = 1.0 + math.random() * 2.0
        ecs.add_transform(obs, x, h * 0.5, z, 1.5, h, 1.5)
        ecs.add_mesh_renderer(obs, "cube")
        ecs.add_rigidbody3d(obs, 0)
        ecs.add_box_collider3d(obs, 1.5, h, 1.5)
        table.insert(obstacles, obs)
    end

    -- Cover points (generated by EQS)
    for i = 1, 8 do
        local cp = ecs.create_entity()
        local angle = (i / 8) * math.pi * 2
        local r = 8.0 + math.random() * 4.0
        ecs.add_transform(cp, math.cos(angle) * r, 0.1, math.sin(angle) * r, 0.4, 0.1, 0.4)
        ecs.add_mesh_renderer(cp, "cube")
    end

    -- Light
    local light = ecs.create_entity()
    ecs.add_transform(light, 0, 20, 0, 1, 1, 1)
    ecs.add_dir_light(light, 1.0, 0.95, 0.9, 1.4)
end

function M.Update(dt)
    state.elapsed = state.elapsed + dt
end

return M