---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")

--- @class BoxCollider : Collider @碰撞盒子
BoxCollider=class("BoxCollider",Collider)

function BoxCollider:ctor()
    BoxCollider.super.ctor(self)
end

function BoxCollider:InitCppComponent()
    ---@type Cpp.BoxCollider
    self.cpp_component_instance_=Cpp.BoxCollider() --创建对应的C++实例
end

function BoxCollider:set_size(size)
    self.cpp_component_instance_:set_size(size)
end

function BoxCollider:size()
    return self.cpp_component_instance_:size()
end
