---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")

--- @class SphereCollider : Collider @球体碰撞器
SphereCollider=class("SphereCollider",Collider)

function SphereCollider:ctor()
    SphereCollider.super.ctor(self)
end

function SphereCollider:InitCppComponent()
    ---@type Cpp.SphereCollider
    self.cpp_component_instance_=Cpp.SphereCollider() --创建对应的C++实例
end

function SphereCollider:set_radius(radius)
    self.cpp_component_instance_:set_radius(radius)
end

function SphereCollider:radius()
    return self.cpp_component_instance_:radius()
end
