// <auto-generated>
//   Source: tools/codegen/binding_defs.json -- do not edit manually
//   Unified scene JSON serialization dispatch -- eliminates hand-written per-component JSON code
// </auto-generated>
#ifndef DSE_SCENE_JSON_CODEC_GEN_H
#define DSE_SCENE_JSON_CODEC_GEN_H

#include "engine/reflect/reflect.h"
#include "engine/reflect/reflect_json.h"
#include "engine/reflect/component_reflection.h"
#include "engine/ecs/transform.h"
#include "engine/ecs/components_3d.h"
#include "engine/ecs/components_3d_tree.h"
#include "engine/ecs/components_3d_terrain_tile.h"
#include "engine/ecs/components_3d_navmesh.h"
#include "engine/ecs/components_3d_render.h"
#include "engine/ecs/components_3d_foliage.h"
#include "engine/ecs/components_3d_physics.h"
#include "engine/ecs/components_3d_sky.h"
#include "engine/ecs/components_3d_impostor.h"
#include "engine/scene/world_partition.h"
#include "engine/render/hlod/hlod_system.h"
#include "engine/render/virtual_texture/virtual_texture.h"
#include "engine/render/gi/lightmap_baker.h"
#include "engine/ecs/components_3d_character.h"
#include "engine/render/particles/gpu_particle_system.h"

#include <rapidjson/document.h>
#include <functional>
#include <string>
#include <unordered_map>

namespace dse::scene_codec {

using SerializeFn = std::function<bool(const entt::registry&, entt::entity,
                                       rapidjson::Value& components,
                                       rapidjson::Document::AllocatorType&)>;
using DeserializeFn = std::function<void(entt::registry&, entt::entity,
                                         const rapidjson::Value&)>;

struct ComponentCodec {
    SerializeFn   serialize;
    DeserializeFn deserialize;
};

inline bool Serialize_transform(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<TransformComponent>(e)) return false;
    const auto& c = reg.get<TransformComponent>(e);
    const auto* ti = reflect::Reflection::Find<TransformComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("TransformComponent", json, alloc);
    return true;
}

inline void Deserialize_transform(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<TransformComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<TransformComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_camera3d(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::Camera3DComponent>(e)) return false;
    const auto& c = reg.get<dse::Camera3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::Camera3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("Camera3DComponent", json, alloc);
    return true;
}

inline void Deserialize_camera3d(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::Camera3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::Camera3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_mesh_renderer(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::MeshRendererComponent>(e)) return false;
    const auto& c = reg.get<dse::MeshRendererComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::MeshRendererComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("MeshRendererComponent", json, alloc);
    return true;
}

inline void Deserialize_mesh_renderer(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::MeshRendererComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::MeshRendererComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_dir_light(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::DirectionalLight3DComponent>(e)) return false;
    const auto& c = reg.get<dse::DirectionalLight3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::DirectionalLight3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("DirectionalLight3DComponent", json, alloc);
    return true;
}

inline void Deserialize_dir_light(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::DirectionalLight3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::DirectionalLight3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_point_light(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::PointLightComponent>(e)) return false;
    const auto& c = reg.get<dse::PointLightComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::PointLightComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("PointLightComponent", json, alloc);
    return true;
}

inline void Deserialize_point_light(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::PointLightComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::PointLightComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_spot_light(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::SpotLightComponent>(e)) return false;
    const auto& c = reg.get<dse::SpotLightComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::SpotLightComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("SpotLightComponent", json, alloc);
    return true;
}

inline void Deserialize_spot_light(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::SpotLightComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::SpotLightComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_sky_light(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::SkyLightComponent>(e)) return false;
    const auto& c = reg.get<dse::SkyLightComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::SkyLightComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("SkyLightComponent", json, alloc);
    return true;
}

inline void Deserialize_sky_light(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::SkyLightComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::SkyLightComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_tree(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::TreeComponent>(e)) return false;
    const auto& c = reg.get<dse::TreeComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::TreeComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("TreeComponent", json, alloc);
    return true;
}

inline void Deserialize_tree(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::TreeComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::TreeComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_terrain_tile(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::TerrainTileManagerComponent>(e)) return false;
    const auto& c = reg.get<dse::TerrainTileManagerComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::TerrainTileManagerComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("TerrainTileManagerComponent", json, alloc);
    return true;
}

inline void Deserialize_terrain_tile(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::TerrainTileManagerComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::TerrainTileManagerComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_dyn_obstacle(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::DynamicObstacleComponent>(e)) return false;
    const auto& c = reg.get<dse::DynamicObstacleComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::DynamicObstacleComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("DynamicObstacleComponent", json, alloc);
    return true;
}

inline void Deserialize_dyn_obstacle(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::DynamicObstacleComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::DynamicObstacleComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_navmesh_rebake(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::NavMeshAutoRebakeComponent>(e)) return false;
    const auto& c = reg.get<dse::NavMeshAutoRebakeComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::NavMeshAutoRebakeComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("NavMeshAutoRebakeComponent", json, alloc);
    return true;
}

inline void Deserialize_navmesh_rebake(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::NavMeshAutoRebakeComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::NavMeshAutoRebakeComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_post_process(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::PostProcessComponent>(e)) return false;
    const auto& c = reg.get<dse::PostProcessComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::PostProcessComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("PostProcessComponent", json, alloc);
    return true;
}

inline void Deserialize_post_process(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::PostProcessComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::PostProcessComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_animator3d(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::Animator3DComponent>(e)) return false;
    const auto& c = reg.get<dse::Animator3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::Animator3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("Animator3DComponent", json, alloc);
    return true;
}

inline void Deserialize_animator3d(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::Animator3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::Animator3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_decal(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::DecalComponent>(e)) return false;
    const auto& c = reg.get<dse::DecalComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::DecalComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("DecalComponent", json, alloc);
    return true;
}

inline void Deserialize_decal(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::DecalComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::DecalComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_skybox(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::SkyboxComponent>(e)) return false;
    const auto& c = reg.get<dse::SkyboxComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::SkyboxComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("SkyboxComponent", json, alloc);
    return true;
}

inline void Deserialize_skybox(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::SkyboxComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::SkyboxComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_free_camera(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::FreeCameraControllerComponent>(e)) return false;
    const auto& c = reg.get<dse::FreeCameraControllerComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::FreeCameraControllerComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("FreeCameraControllerComponent", json, alloc);
    return true;
}

inline void Deserialize_free_camera(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::FreeCameraControllerComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::FreeCameraControllerComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_sub_scene(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::SubSceneComponent>(e)) return false;
    const auto& c = reg.get<dse::SubSceneComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::SubSceneComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("SubSceneComponent", json, alloc);
    return true;
}

inline void Deserialize_sub_scene(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::SubSceneComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::SubSceneComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_bounding_box(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::BoundingBoxComponent>(e)) return false;
    const auto& c = reg.get<dse::BoundingBoxComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::BoundingBoxComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("BoundingBoxComponent", json, alloc);
    return true;
}

inline void Deserialize_bounding_box(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::BoundingBoxComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::BoundingBoxComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_water(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::WaterComponent>(e)) return false;
    const auto& c = reg.get<dse::WaterComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::WaterComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("WaterComponent", json, alloc);
    return true;
}

inline void Deserialize_water(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::WaterComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::WaterComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_light_probe(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::LightProbeComponent>(e)) return false;
    const auto& c = reg.get<dse::LightProbeComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::LightProbeComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("LightProbeComponent", json, alloc);
    return true;
}

inline void Deserialize_light_probe(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::LightProbeComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::LightProbeComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_reflection_probe(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::ReflectionProbeComponent>(e)) return false;
    const auto& c = reg.get<dse::ReflectionProbeComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::ReflectionProbeComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("ReflectionProbeComponent", json, alloc);
    return true;
}

inline void Deserialize_reflection_probe(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::ReflectionProbeComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::ReflectionProbeComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_gi_probe(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::GIProbeVolumeComponent>(e)) return false;
    const auto& c = reg.get<dse::GIProbeVolumeComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::GIProbeVolumeComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("GIProbeVolumeComponent", json, alloc);
    return true;
}

inline void Deserialize_gi_probe(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::GIProbeVolumeComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::GIProbeVolumeComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_foliage(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::FoliageComponent>(e)) return false;
    const auto& c = reg.get<dse::FoliageComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::FoliageComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("FoliageComponent", json, alloc);
    return true;
}

inline void Deserialize_foliage(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::FoliageComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::FoliageComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_rigidbody3d(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::RigidBody3DComponent>(e)) return false;
    const auto& c = reg.get<dse::RigidBody3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::RigidBody3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("RigidBody3DComponent", json, alloc);
    return true;
}

inline void Deserialize_rigidbody3d(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::RigidBody3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::RigidBody3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_box_collider3d(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::BoxCollider3DComponent>(e)) return false;
    const auto& c = reg.get<dse::BoxCollider3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::BoxCollider3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("BoxCollider3DComponent", json, alloc);
    return true;
}

inline void Deserialize_box_collider3d(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::BoxCollider3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::BoxCollider3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_sphere_collider3d(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::SphereCollider3DComponent>(e)) return false;
    const auto& c = reg.get<dse::SphereCollider3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::SphereCollider3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("SphereCollider3DComponent", json, alloc);
    return true;
}

inline void Deserialize_sphere_collider3d(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::SphereCollider3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::SphereCollider3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_capsule_collider3d(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::CapsuleCollider3DComponent>(e)) return false;
    const auto& c = reg.get<dse::CapsuleCollider3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::CapsuleCollider3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("CapsuleCollider3DComponent", json, alloc);
    return true;
}

inline void Deserialize_capsule_collider3d(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::CapsuleCollider3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::CapsuleCollider3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_mesh_collider3d(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::MeshCollider3DComponent>(e)) return false;
    const auto& c = reg.get<dse::MeshCollider3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::MeshCollider3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("MeshCollider3DComponent", json, alloc);
    return true;
}

inline void Deserialize_mesh_collider3d(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::MeshCollider3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::MeshCollider3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_character_ctrl3d(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::CharacterController3DComponent>(e)) return false;
    const auto& c = reg.get<dse::CharacterController3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::CharacterController3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("CharacterController3DComponent", json, alloc);
    return true;
}

inline void Deserialize_character_ctrl3d(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::CharacterController3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::CharacterController3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_joint3d(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::Joint3DComponent>(e)) return false;
    const auto& c = reg.get<dse::Joint3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::Joint3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("Joint3DComponent", json, alloc);
    return true;
}

inline void Deserialize_joint3d(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::Joint3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::Joint3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_ragdoll(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::RagdollComponent>(e)) return false;
    const auto& c = reg.get<dse::RagdollComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::RagdollComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("RagdollComponent", json, alloc);
    return true;
}

inline void Deserialize_ragdoll(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::RagdollComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::RagdollComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_soft_body(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::SoftBodyComponent>(e)) return false;
    const auto& c = reg.get<dse::SoftBodyComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::SoftBodyComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("SoftBodyComponent", json, alloc);
    return true;
}

inline void Deserialize_soft_body(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::SoftBodyComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::SoftBodyComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_vehicle(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::VehicleComponent>(e)) return false;
    const auto& c = reg.get<dse::VehicleComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::VehicleComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("VehicleComponent", json, alloc);
    return true;
}

inline void Deserialize_vehicle(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::VehicleComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::VehicleComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_rope(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::RopeComponent>(e)) return false;
    const auto& c = reg.get<dse::RopeComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::RopeComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("RopeComponent", json, alloc);
    return true;
}

inline void Deserialize_rope(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::RopeComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::RopeComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_buoyancy(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::BuoyancyComponent>(e)) return false;
    const auto& c = reg.get<dse::BuoyancyComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::BuoyancyComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("BuoyancyComponent", json, alloc);
    return true;
}

inline void Deserialize_buoyancy(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::BuoyancyComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::BuoyancyComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_atmosphere(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::AtmosphereComponent>(e)) return false;
    const auto& c = reg.get<dse::AtmosphereComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::AtmosphereComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("AtmosphereComponent", json, alloc);
    return true;
}

inline void Deserialize_atmosphere(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::AtmosphereComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::AtmosphereComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_volumetric_cloud(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::VolumetricCloudComponent>(e)) return false;
    const auto& c = reg.get<dse::VolumetricCloudComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::VolumetricCloudComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("VolumetricCloudComponent", json, alloc);
    return true;
}

inline void Deserialize_volumetric_cloud(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::VolumetricCloudComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::VolumetricCloudComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_day_night(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::DayNightCycleComponent>(e)) return false;
    const auto& c = reg.get<dse::DayNightCycleComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::DayNightCycleComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("DayNightCycleComponent", json, alloc);
    return true;
}

inline void Deserialize_day_night(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::DayNightCycleComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::DayNightCycleComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_hair(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::HairComponent>(e)) return false;
    const auto& c = reg.get<dse::HairComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::HairComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("HairComponent", json, alloc);
    return true;
}

inline void Deserialize_hair(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::HairComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::HairComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_impostor(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::ImpostorComponent>(e)) return false;
    const auto& c = reg.get<dse::ImpostorComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::ImpostorComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("ImpostorComponent", json, alloc);
    return true;
}

inline void Deserialize_impostor(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::ImpostorComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::ImpostorComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_streaming_origin(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::StreamingOriginComponent>(e)) return false;
    const auto& c = reg.get<dse::StreamingOriginComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::StreamingOriginComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("StreamingOriginComponent", json, alloc);
    return true;
}

inline void Deserialize_streaming_origin(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::StreamingOriginComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::StreamingOriginComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_world_partition(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::WorldPartitionConfigComponent>(e)) return false;
    const auto& c = reg.get<dse::WorldPartitionConfigComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::WorldPartitionConfigComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("WorldPartitionConfigComponent", json, alloc);
    return true;
}

inline void Deserialize_world_partition(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::WorldPartitionConfigComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::WorldPartitionConfigComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_hlod_config(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::render::HLODConfigComponent>(e)) return false;
    const auto& c = reg.get<dse::render::HLODConfigComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::render::HLODConfigComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("HLODConfigComponent", json, alloc);
    return true;
}

inline void Deserialize_hlod_config(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::render::HLODConfigComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::render::HLODConfigComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_virtual_texture(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::vt::VirtualTextureComponent>(e)) return false;
    const auto& c = reg.get<dse::vt::VirtualTextureComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::vt::VirtualTextureComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("VirtualTextureComponent", json, alloc);
    return true;
}

inline void Deserialize_virtual_texture(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::vt::VirtualTextureComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::vt::VirtualTextureComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_lightmap(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::render::LightmapComponent>(e)) return false;
    const auto& c = reg.get<dse::render::LightmapComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::render::LightmapComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("LightmapComponent", json, alloc);
    return true;
}

inline void Deserialize_lightmap(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::render::LightmapComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::render::LightmapComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_character_movement_cfg(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::CharacterMovementConfig>(e)) return false;
    const auto& c = reg.get<dse::CharacterMovementConfig>(e);
    const auto* ti = reflect::Reflection::Find<dse::CharacterMovementConfig>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("CharacterMovementConfig", json, alloc);
    return true;
}

inline void Deserialize_character_movement_cfg(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::CharacterMovementConfig>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::CharacterMovementConfig>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_character_movement(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::CharacterMovementState>(e)) return false;
    const auto& c = reg.get<dse::CharacterMovementState>(e);
    const auto* ti = reflect::Reflection::Find<dse::CharacterMovementState>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("CharacterMovementState", json, alloc);
    return true;
}

inline void Deserialize_character_movement(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::CharacterMovementState>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::CharacterMovementState>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_spring_arm(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::SpringArm3DComponent>(e)) return false;
    const auto& c = reg.get<dse::SpringArm3DComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::SpringArm3DComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("SpringArm3DComponent", json, alloc);
    return true;
}

inline void Deserialize_spring_arm(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::SpringArm3DComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::SpringArm3DComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_player_controller(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::PlayerControllerComponent>(e)) return false;
    const auto& c = reg.get<dse::PlayerControllerComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::PlayerControllerComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("PlayerControllerComponent", json, alloc);
    return true;
}

inline void Deserialize_player_controller(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::PlayerControllerComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::PlayerControllerComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_GrassComponent(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::GrassComponent>(e)) return false;
    const auto& c = reg.get<dse::GrassComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::GrassComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("GrassComponent", json, alloc);
    return true;
}

inline void Deserialize_GrassComponent(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::GrassComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::GrassComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_LODGroupComponent(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::LODGroupComponent>(e)) return false;
    const auto& c = reg.get<dse::LODGroupComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::LODGroupComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("LODGroupComponent", json, alloc);
    return true;
}

inline void Deserialize_LODGroupComponent(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::LODGroupComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::LODGroupComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_MorphTargetComponent(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::MorphTargetComponent>(e)) return false;
    const auto& c = reg.get<dse::MorphTargetComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::MorphTargetComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("MorphTargetComponent", json, alloc);
    return true;
}

inline void Deserialize_MorphTargetComponent(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::MorphTargetComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::MorphTargetComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_GpuParticleComponent(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::render::GpuParticleComponent>(e)) return false;
    const auto& c = reg.get<dse::render::GpuParticleComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::render::GpuParticleComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("GpuParticleComponent", json, alloc);
    return true;
}

inline void Deserialize_GpuParticleComponent(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::render::GpuParticleComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::render::GpuParticleComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}

inline bool Serialize_HLODMemberComponent(const entt::registry& reg, entt::entity e,
                                    rapidjson::Value& components,
                                    rapidjson::Document::AllocatorType& alloc) {
    if (!reg.all_of<dse::render::HLODMemberComponent>(e)) return false;
    const auto& c = reg.get<dse::render::HLODMemberComponent>(e);
    const auto* ti = reflect::Reflection::Find<dse::render::HLODMemberComponent>();
    if (!ti) return false;
    rapidjson::Value json(rapidjson::kObjectType);
    reflect::SerializeReflected(*ti, &c, json, alloc);
    components.AddMember("HLODMemberComponent", json, alloc);
    return true;
}

inline void Deserialize_HLODMemberComponent(entt::registry& reg, entt::entity e,
                                      const rapidjson::Value& json) {
    const auto* ti = reflect::Reflection::Find<dse::render::HLODMemberComponent>();
    if (!ti) return;
    auto& c = reg.get_or_emplace<dse::render::HLODMemberComponent>(e);
    reflect::DeserializeReflected(*ti, &c, json);
}


inline const std::unordered_map<std::string, ComponentCodec>& GetCodecTable() {
    static const std::unordered_map<std::string, ComponentCodec> table = {
        {"TransformComponent", {Serialize_transform, Deserialize_transform}},
        {"Camera3DComponent", {Serialize_camera3d, Deserialize_camera3d}},
        {"MeshRendererComponent", {Serialize_mesh_renderer, Deserialize_mesh_renderer}},
        {"DirectionalLight3DComponent", {Serialize_dir_light, Deserialize_dir_light}},
        {"PointLightComponent", {Serialize_point_light, Deserialize_point_light}},
        {"SpotLightComponent", {Serialize_spot_light, Deserialize_spot_light}},
        {"SkyLightComponent", {Serialize_sky_light, Deserialize_sky_light}},
        {"TreeComponent", {Serialize_tree, Deserialize_tree}},
        {"TerrainTileManagerComponent", {Serialize_terrain_tile, Deserialize_terrain_tile}},
        {"DynamicObstacleComponent", {Serialize_dyn_obstacle, Deserialize_dyn_obstacle}},
        {"NavMeshAutoRebakeComponent", {Serialize_navmesh_rebake, Deserialize_navmesh_rebake}},
        {"PostProcessComponent", {Serialize_post_process, Deserialize_post_process}},
        {"Animator3DComponent", {Serialize_animator3d, Deserialize_animator3d}},
        {"DecalComponent", {Serialize_decal, Deserialize_decal}},
        {"SkyboxComponent", {Serialize_skybox, Deserialize_skybox}},
        {"FreeCameraControllerComponent", {Serialize_free_camera, Deserialize_free_camera}},
        {"SubSceneComponent", {Serialize_sub_scene, Deserialize_sub_scene}},
        {"BoundingBoxComponent", {Serialize_bounding_box, Deserialize_bounding_box}},
        {"WaterComponent", {Serialize_water, Deserialize_water}},
        {"LightProbeComponent", {Serialize_light_probe, Deserialize_light_probe}},
        {"ReflectionProbeComponent", {Serialize_reflection_probe, Deserialize_reflection_probe}},
        {"GIProbeVolumeComponent", {Serialize_gi_probe, Deserialize_gi_probe}},
        {"FoliageComponent", {Serialize_foliage, Deserialize_foliage}},
        {"RigidBody3DComponent", {Serialize_rigidbody3d, Deserialize_rigidbody3d}},
        {"BoxCollider3DComponent", {Serialize_box_collider3d, Deserialize_box_collider3d}},
        {"SphereCollider3DComponent", {Serialize_sphere_collider3d, Deserialize_sphere_collider3d}},
        {"CapsuleCollider3DComponent", {Serialize_capsule_collider3d, Deserialize_capsule_collider3d}},
        {"MeshCollider3DComponent", {Serialize_mesh_collider3d, Deserialize_mesh_collider3d}},
        {"CharacterController3DComponent", {Serialize_character_ctrl3d, Deserialize_character_ctrl3d}},
        {"Joint3DComponent", {Serialize_joint3d, Deserialize_joint3d}},
        {"RagdollComponent", {Serialize_ragdoll, Deserialize_ragdoll}},
        {"SoftBodyComponent", {Serialize_soft_body, Deserialize_soft_body}},
        {"VehicleComponent", {Serialize_vehicle, Deserialize_vehicle}},
        {"RopeComponent", {Serialize_rope, Deserialize_rope}},
        {"BuoyancyComponent", {Serialize_buoyancy, Deserialize_buoyancy}},
        {"AtmosphereComponent", {Serialize_atmosphere, Deserialize_atmosphere}},
        {"VolumetricCloudComponent", {Serialize_volumetric_cloud, Deserialize_volumetric_cloud}},
        {"DayNightCycleComponent", {Serialize_day_night, Deserialize_day_night}},
        {"HairComponent", {Serialize_hair, Deserialize_hair}},
        {"ImpostorComponent", {Serialize_impostor, Deserialize_impostor}},
        {"StreamingOriginComponent", {Serialize_streaming_origin, Deserialize_streaming_origin}},
        {"WorldPartitionConfigComponent", {Serialize_world_partition, Deserialize_world_partition}},
        {"HLODConfigComponent", {Serialize_hlod_config, Deserialize_hlod_config}},
        {"VirtualTextureComponent", {Serialize_virtual_texture, Deserialize_virtual_texture}},
        {"LightmapComponent", {Serialize_lightmap, Deserialize_lightmap}},
        {"CharacterMovementConfig", {Serialize_character_movement_cfg, Deserialize_character_movement_cfg}},
        {"CharacterMovementState", {Serialize_character_movement, Deserialize_character_movement}},
        {"SpringArm3DComponent", {Serialize_spring_arm, Deserialize_spring_arm}},
        {"PlayerControllerComponent", {Serialize_player_controller, Deserialize_player_controller}},
        {"GrassComponent", {Serialize_GrassComponent, Deserialize_GrassComponent}},
        {"LODGroupComponent", {Serialize_LODGroupComponent, Deserialize_LODGroupComponent}},
        {"MorphTargetComponent", {Serialize_MorphTargetComponent, Deserialize_MorphTargetComponent}},
        {"GpuParticleComponent", {Serialize_GpuParticleComponent, Deserialize_GpuParticleComponent}},
        {"HLODMemberComponent", {Serialize_HLODMemberComponent, Deserialize_HLODMemberComponent}},
    };
    return table;
}

inline void SerializeAllComponents(const entt::registry& reg, entt::entity e,
                                   rapidjson::Value& components,
                                   rapidjson::Document::AllocatorType& alloc) {
    for (const auto& [name, codec] : GetCodecTable()) {
        codec.serialize(reg, e, components, alloc);
    }
}

inline void DeserializeComponents(entt::registry& reg, entt::entity e,
                                  const rapidjson::Value& components) {
    if (!components.IsObject()) return;
    const auto& table = GetCodecTable();
    for (auto it = components.MemberBegin(); it != components.MemberEnd(); ++it) {
        auto codec_it = table.find(it->name.GetString());
        if (codec_it != table.end()) {
            codec_it->second.deserialize(reg, e, it->value);
        }
    }
}

} // namespace dse::scene_codec

#endif // DSE_SCENE_JSON_CODEC_GEN_H
