#include "editor_visual_script_compiler.h"

#include <cstdio>
#include <sstream>
#include <unordered_map>
#include <unordered_set>

namespace dse::editor::vs {

namespace {

class Compiler {
public:
    explicit Compiler(const Graph& g) : g_(g) {}

    std::string Run() {
        std::ostringstream out;
        out << "-- Generated by DSEngine Visual Script Editor\n";
        out << "-- Do not edit manually\n\n";

        // 事件输出数据 pin（如 On Update 的 dt）以参数名直接可用。
        for (const auto& n : g_.nodes) {
            if (n.category != "Event") continue;
            for (const auto& p : n.outputs) {
                if (p.type != PinType::Flow) pin_expr_[p.id] = p.name;
            }
        }

        bool any_event = false;
        for (const auto& n : g_.nodes) {
            if (n.category != "Event") continue;
            any_event = true;
            EmitEvent(out, n);
            out << "\n";
        }

        // 无事件入口时，退化为按数据依赖输出纯数据节点的局部变量，避免简单数据图无输出。
        if (!any_event) {
            for (const auto& n : g_.nodes) {
                if (!IsPureData(n) || n.outputs.empty()) continue;
                const PinData& o = n.outputs.front();
                if (o.type == PinType::Flow) continue;
                out << "local " << FreshVar() << " = " << InlineExpr(n, o.id) << "\n";
            }
        }
        return out.str();
    }

private:
    const Graph& g_;
    std::unordered_map<int, std::string> pin_expr_;  // 输出 pin id -> 已绑定表达式/变量名
    std::unordered_set<int> inline_guard_;           // 内联求值环路保护
    int var_counter_ = 0;

    std::string FreshVar() { return "v" + std::to_string(var_counter_++); }

    const NodeData* FindOwner(int pin_id) const {
        for (const auto& n : g_.nodes) {
            for (const auto& p : n.inputs) if (p.id == pin_id) return &n;
            for (const auto& p : n.outputs) if (p.id == pin_id) return &n;
        }
        return nullptr;
    }

    const PinData* FindPin(int pin_id) const {
        for (const auto& n : g_.nodes) {
            for (const auto& p : n.inputs) if (p.id == pin_id) return &p;
            for (const auto& p : n.outputs) if (p.id == pin_id) return &p;
        }
        return nullptr;
    }

    // 输入 pin 的源输出 pin（数据连线）。
    int LinkedOutput(int input_pin_id) const {
        for (const auto& l : g_.links) if (l.to_pin == input_pin_id) return l.from_pin;
        return -1;
    }

    // 输出 Flow pin 连到的下游输入 pin。
    int LinkedInput(int output_pin_id) const {
        for (const auto& l : g_.links) if (l.from_pin == output_pin_id) return l.to_pin;
        return -1;
    }

    static bool IsPureData(const NodeData& n) {
        for (const auto& p : n.inputs) if (p.type == PinType::Flow) return false;
        for (const auto& p : n.outputs) if (p.type == PinType::Flow) return false;
        return n.category != "Event";
    }

    static const PinData* FindOutputByName(const NodeData& n, const char* name) {
        for (const auto& p : n.outputs) if (p.name == name) return &p;
        return nullptr;
    }

    static const PinData* FirstFlowOutput(const NodeData& n) {
        for (const auto& p : n.outputs) if (p.type == PinType::Flow) return &p;
        return nullptr;
    }

    static std::string DefaultLiteral(const PinData& p) {
        switch (p.type) {
            case PinType::Float: {
                char buf[32];
                snprintf(buf, sizeof(buf), "%g", p.default_float);
                return buf;
            }
            case PinType::Vec3: {
                char buf[64];
                snprintf(buf, sizeof(buf), "vec3(%g, %g, %g)",
                         p.default_vec3[0], p.default_vec3[1], p.default_vec3[2]);
                return buf;
            }
            case PinType::String: return std::string("\"") + p.default_string + "\"";
            case PinType::Bool:   return p.default_bool ? "true" : "false";
            case PinType::Entity: return "nil";
            default:              return "nil";
        }
    }

    static void ReplaceAll(std::string& s, const std::string& from, const std::string& to) {
        size_t pos;
        while ((pos = s.find(from)) != std::string::npos) s.replace(pos, from.size(), to);
    }

    // 解析数据输入：优先已绑定变量（事件参数 / Flow 节点输出 / 循环索引），否则内联纯数据表达式，否则字面量。
    std::string ResolveInput(const PinData& in) {
        const int from = LinkedOutput(in.id);
        if (from < 0) return DefaultLiteral(in);
        auto it = pin_expr_.find(from);
        if (it != pin_expr_.end()) return it->second;
        const NodeData* owner = FindOwner(from);
        if (owner && IsPureData(*owner)) return InlineExpr(*owner, from);
        return DefaultLiteral(in);
    }

    // 纯数据节点的某个输出 pin 的内联表达式。
    std::string InlineExpr(const NodeData& n, int output_pin_id) {
        auto cached = pin_expr_.find(output_pin_id);
        if (cached != pin_expr_.end()) return cached->second;
        if (inline_guard_.count(n.id)) return "nil";  // 环路保护
        inline_guard_.insert(n.id);

        std::string expr;
        if (n.code_template.empty()) {
            // 无模板：常量节点，用其输出默认值。
            const PinData* o = FindPin(output_pin_id);
            expr = o ? DefaultLiteral(*o) : "nil";
        } else {
            // 模板形如 "{output0} = EXPR"，取 EXPR 部分。
            expr = n.code_template;
            const size_t eq = expr.find(" = ");
            if (expr.rfind("{output", 0) == 0 && eq != std::string::npos) {
                expr = expr.substr(eq + 3);
            }
            for (size_t i = 0; i < n.inputs.size(); ++i) {
                ReplaceAll(expr, "{input" + std::to_string(i) + "}", ResolveInput(n.inputs[i]));
            }
            expr = "(" + expr + ")";
        }

        inline_guard_.erase(n.id);
        return expr;
    }

    void EmitEvent(std::ostringstream& out, const NodeData& ev) {
        std::ostringstream body;
        if (const PinData* exec = FirstFlowOutput(ev)) {
            std::unordered_set<int> visited;
            EmitFlow(body, exec->id, 1, visited);
        }
        std::string body_str = body.str();
        if (!body_str.empty() && body_str.back() == '\n') body_str.pop_back();
        if (body_str.empty()) body_str = "  -- (empty)";

        std::string code = ev.code_template;
        if (code.empty()) code = "function _event()\n{body}\nend";
        ReplaceAll(code, "{body}", body_str);
        out << code << "\n";
    }

    static void Indent(std::ostringstream& out, int depth) {
        for (int i = 0; i < depth; ++i) out << "  ";
    }

    // 沿执行连线从给定输出 Flow pin 向下生成语句。
    void EmitFlow(std::ostringstream& out, int exec_output_pin, int depth,
                  std::unordered_set<int>& visited) {
        int to = LinkedInput(exec_output_pin);
        if (to < 0) return;
        const NodeData* node = FindOwner(to);
        if (!node) return;
        if (visited.count(node->id)) return;  // 防止执行环
        visited.insert(node->id);

        if (node->name == "Branch") {
            EmitBranch(out, *node, depth, visited);
        } else if (node->name == "For Loop") {
            EmitForLoop(out, *node, depth, visited);
        } else {
            EmitStatement(out, *node, depth);
            if (const PinData* exec_out = FirstFlowOutput(*node)) {
                EmitFlow(out, exec_out->id, depth, visited);
            }
        }
    }

    void EmitBranch(std::ostringstream& out, const NodeData& node, int depth,
                    std::unordered_set<int>& visited) {
        // 约定：inputs[1] 为 Condition（inputs[0] 为 Exec）。
        std::string cond = "false";
        for (const auto& in : node.inputs) {
            if (in.type == PinType::Bool || in.name == "Condition") { cond = ResolveInput(in); break; }
        }
        Indent(out, depth); out << "if " << cond << " then\n";
        if (const PinData* t = FindOutputByName(node, "True")) {
            auto branch_visited = visited;
            EmitFlow(out, t->id, depth + 1, branch_visited);
        }
        Indent(out, depth); out << "else\n";
        if (const PinData* f = FindOutputByName(node, "False")) {
            auto branch_visited = visited;
            EmitFlow(out, f->id, depth + 1, branch_visited);
        }
        Indent(out, depth); out << "end\n";
    }

    void EmitForLoop(std::ostringstream& out, const NodeData& node, int depth,
                     std::unordered_set<int>& visited) {
        // 约定：inputs[1]=Start, inputs[2]=End（inputs[0]=Exec）。
        std::string start = "0", end = "0";
        int data_seen = 0;
        for (const auto& in : node.inputs) {
            if (in.type == PinType::Flow) continue;
            if (data_seen == 0) start = ResolveInput(in);
            else if (data_seen == 1) end = ResolveInput(in);
            ++data_seen;
        }
        std::string idx = "i" + std::to_string(var_counter_++);
        if (const PinData* index_pin = FindOutputByName(node, "Index")) {
            pin_expr_[index_pin->id] = idx;
        }
        Indent(out, depth); out << "for " << idx << " = " << start << ", " << end << " do\n";
        if (const PinData* body = FindOutputByName(node, "Body")) {
            auto body_visited = visited;
            EmitFlow(out, body->id, depth + 1, body_visited);
        }
        Indent(out, depth); out << "end\n";
        if (const PinData* done = FindOutputByName(node, "Done")) {
            EmitFlow(out, done->id, depth, visited);
        }
    }

    // 普通 Flow 语句节点：替换模板的 {inputN}/{outputN}，必要时为数据输出加 local。
    void EmitStatement(std::ostringstream& out, const NodeData& node, int depth) {
        if (node.code_template.empty()) return;
        std::string code = node.code_template;

        bool has_data_output = false;
        for (const auto& o : node.outputs) {
            if (o.type == PinType::Flow) continue;
            has_data_output = true;
            if (!pin_expr_.count(o.id)) pin_expr_[o.id] = FreshVar();
        }

        for (size_t i = 0; i < node.inputs.size(); ++i) {
            ReplaceAll(code, "{input" + std::to_string(i) + "}", ResolveInput(node.inputs[i]));
        }
        for (size_t i = 0; i < node.outputs.size(); ++i) {
            const PinData& o = node.outputs[i];
            std::string val = (o.type == PinType::Flow) ? "_" : pin_expr_[o.id];
            ReplaceAll(code, "{output" + std::to_string(i) + "}", val);
        }

        Indent(out, depth);
        if (has_data_output) out << "local ";
        out << code << "\n";
    }
};

}  // namespace

std::string CompileVisualScript(const Graph& graph) {
    Compiler c(graph);
    return c.Run();
}

}  // namespace dse::editor::vs
